name: chumian_ai
description: "初眠AI - 智能AI助手"
publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  dio: ^5.7.0
  flutter_markdown: ^0.7.4
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  flutter_local_notifications: ^17.2.2
  mobile_scanner: ^5.1.1
  timezone: ^0.9.4
  open_filex: ^4.4.0
  path_provider: ^2.1.4
  markdown: ^7.2.2
  video_player: ^2.9.2
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
