import 'package:flutter/material.dart';

/// 全局间距规范
class AppSpacing {
  AppSpacing._();
  static const double xxs = 2;
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 16;
  static const double xl = 20;
  static const double xxl = 24;
  static const double xxxl = 32;
  static const double xxxxl = 40;
  static const double huge = 56;
  static const double massive = 72;

  static const EdgeInsets page = EdgeInsets.symmetric(horizontal: lg, vertical: md);
  static const EdgeInsets pageHorizontal = EdgeInsets.symmetric(horizontal: lg);
  static const EdgeInsets cardPadding = EdgeInsets.all(lg);
  static const EdgeInsets cardInner = EdgeInsets.all(md);
  static const EdgeInsets listSection = EdgeInsets.only(top: xxl, bottom: md);
  static const EdgeInsets buttonPadding = EdgeInsets.symmetric(horizontal: xl, vertical: md);
  static const EdgeInsets inputPadding = EdgeInsets.symmetric(horizontal: lg, vertical: md);
  static const EdgeInsets dialogPadding = EdgeInsets.all(xxl);
  static const EdgeInsets sheetPadding = EdgeInsets.fromLTRB(lg, lg, lg, xxxl);
  static const EdgeInsets appBarContent = EdgeInsets.symmetric(horizontal: lg);
  static const EdgeInsets sectionHeader = EdgeInsets.fromLTRB(lg, xl, lg, sm);
  static const EdgeInsets gridPadding = EdgeInsets.all(sm);
  static const EdgeInsets chipPadding = EdgeInsets.symmetric(horizontal: md, vertical: xs);
  static const EdgeInsets tagPadding = EdgeInsets.symmetric(horizontal: sm, vertical: xs);
  static const EdgeInsets badgePadding = EdgeInsets.symmetric(horizontal: sm, vertical: 1);
  static const EdgeInsets avatarPadding = EdgeInsets.all(2);
  static const EdgeInsets iconButtonPadding = EdgeInsets.all(sm);
  static const EdgeInsets tabPadding = EdgeInsets.symmetric(horizontal: md, vertical: sm);
  static const EdgeInsets segmentedPadding = EdgeInsets.all(xs);
  static const EdgeInsets stepperPadding = EdgeInsets.symmetric(horizontal: md, vertical: sm);
  static const EdgeInsets timelinePadding = EdgeInsets.only(left: lg, top: md, bottom: md);
  static const EdgeInsets carouselPadding = EdgeInsets.symmetric(vertical: md);
  static const EdgeInsets parallaxPadding = EdgeInsets.zero;
  static const EdgeInsets heroPadding = EdgeInsets.all(xxl);
  static const EdgeInsets floatingPadding = EdgeInsets.all(lg);
  static const EdgeInsets snackbarPadding = EdgeInsets.symmetric(horizontal: lg, vertical: md);
  static const EdgeInsets tooltipPadding = EdgeInsets.symmetric(horizontal: md, vertical: sm);
  static const EdgeInsets bannerPadding = EdgeInsets.symmetric(horizontal: lg, vertical: md);
  static const EdgeInsets cardHeaderPadding = EdgeInsets.fromLTRB(lg, lg, lg, sm);
  static const EdgeInsets cardFooterPadding = EdgeInsets.fromLTRB(lg, sm, lg, lg);
  static const EdgeInsets cardBodyPadding = EdgeInsets.symmetric(horizontal: lg, vertical: sm);
  static const EdgeInsets cardActionsPadding = EdgeInsets.fromLTRB(lg, sm, lg, lg);
  static const EdgeInsets expansionTilePadding = EdgeInsets.symmetric(horizontal: lg);
  static const EdgeInsets expansionTileChildrenPadding = EdgeInsets.fromLTRB(lg, 0, lg, lg);
  static const EdgeInsets listTilePadding = EdgeInsets.symmetric(horizontal: lg, vertical: sm);
  static const EdgeInsets listTileContentPadding = EdgeInsets.symmetric(horizontal: lg);
  static const EdgeInsets drawerPadding = EdgeInsets.symmetric(vertical: lg);
  static const EdgeInsets drawerHeaderPadding = EdgeInsets.all(xxl);
  static const EdgeInsets endDrawerPadding = EdgeInsets.symmetric(vertical: lg);
  static const EdgeInsets bottomSheetHeaderPadding = EdgeInsets.fromLTRB(lg, lg, lg, sm);
  static const EdgeInsets bottomSheetBodyPadding = EdgeInsets.symmetric(horizontal: lg);
  static const EdgeInsets bottomSheetFooterPadding = EdgeInsets.fromLTRB(lg, sm, lg, xxxl);
  static const EdgeInsets alertDialogPadding = EdgeInsets.all(xxl);
  static const EdgeInsets alertDialogTitlePadding = EdgeInsets.fromLTRB(xxl, xxl, xxl, sm);
  static const EdgeInsets alertDialogContentPadding = EdgeInsets.fromLTRB(xxl, sm, xxl, sm);
  static const EdgeInsets alertDialogActionsPadding = EdgeInsets.fromLTRB(xxl, sm, xxl, lg);
  static const EdgeInsets simpleDialogPadding = EdgeInsets.all(xxl);
  static const EdgeInsets simpleDialogTitlePadding = EdgeInsets.fromLTRB(xxl, xxl, xxl, sm);
  static const EdgeInsets simpleDialogOptionPadding = EdgeInsets.symmetric(horizontal: xxl, vertical: lg);
  static const EdgeInsets aboutDialogPadding = EdgeInsets.all(xxl);
  static const EdgeInsets licensePagePadding = EdgeInsets.all(lg);
  static const EdgeInsets licenseTilePadding = EdgeInsets.symmetric(horizontal: lg, vertical: sm);
}
