import 'package:flutter/material.dart';

/// 动画时长常量
class AppDurations {
  AppDurations._();
  static const Duration instant = Duration(milliseconds: 50);
  static const Duration fastest = Duration(milliseconds: 100);
  static const Duration faster = Duration(milliseconds: 150);
  static const Duration fast = Duration(milliseconds: 200);
  static const Duration normal = Duration(milliseconds: 300);
  static const Duration slow = Duration(milliseconds: 400);
  static const Duration slower = Duration(milliseconds: 500);
  static const Duration slowest = Duration(milliseconds: 600);
  static const Duration pageTransition = Duration(milliseconds: 450);
  static const Duration navSwitch = Duration(milliseconds: 500);
  static const Duration dialog = Duration(milliseconds: 300);
  static const Duration bottomSheet = Duration(milliseconds: 350);
  static const Duration snackbar = Duration(milliseconds: 250);
  static const Duration tooltip = Duration(milliseconds: 200);
  static const Duration buttonPress = Duration(milliseconds: 100);
  static const Duration buttonRelease = Duration(milliseconds: 150);
  static const Duration ripple = Duration(milliseconds: 400);
  static const Duration shimmer = Duration(milliseconds: 1200);
  static const Duration pulse = Duration(milliseconds: 1000);
  static const Duration spin = Duration(milliseconds: 800);
  static const Duration bounce = Duration(milliseconds: 500);
  static const Duration shake = Duration(milliseconds: 400);
  static const Duration flip = Duration(milliseconds: 600);
  static const Duration rotate = Duration(milliseconds: 1000);
  static const Duration scale = Duration(milliseconds: 300);
  static const Duration fade = Duration(milliseconds: 250);
  static const Duration slide = Duration(milliseconds: 300);
  static const Duration staggerItem = Duration(milliseconds: 50);
  static const Duration typingChar = Duration(milliseconds: 30);
  static const Duration imageFade = Duration(milliseconds: 300);
  static const Duration listItem = Duration(milliseconds: 350);
  static const Duration cardHover = Duration(milliseconds: 200);
  static const Duration expansion = Duration(milliseconds: 300);
  static const Duration hero = Duration(milliseconds: 500);
  static const Duration tabSwitch = Duration(milliseconds: 300);
  static const Duration loader = Duration(milliseconds: 1200);
  static const Duration progress = Duration(milliseconds: 500);
  static const Duration countUp = Duration(milliseconds: 800);
  static const Duration marquee = Duration(seconds: 10);
  static const Duration particle = Duration(milliseconds: 1500);
  static const Duration confetti = Duration(seconds: 2);
  static const Duration fireworks = Duration(seconds: 3);
  static const Duration rippleEffect = Duration(milliseconds: 600);
  static const Duration glowPulse = Duration(milliseconds: 2000);
  static const Duration breathe = Duration(milliseconds: 3000);
  static const Duration wave = Duration(milliseconds: 1200);
  static const Duration orbit = Duration(milliseconds: 2000);
  static const Duration morph = Duration(milliseconds: 800);
  static const Duration liquid = Duration(milliseconds: 1500);
  static const Duration spring = Duration(milliseconds: 500);
  static const Duration damping = Duration(milliseconds: 600);
  static const Duration stiffness = Duration(milliseconds: 400);
}

/// 动画曲线常量
class AppCurves {
  AppCurves._();
  static const Curve standard = Curves.easeInOutCubic;
  static const Curve decelerate = Curves.decelerate;
  static const Curve accelerate = Curves.easeInCubic;
  static const Curve sharp = Curves.easeInQuart;
  static const Curve smooth = Curves.easeOutCubic;
  static const Curve emphasized = Curves.easeOutBack;
  static const Curve emphasizedDecelerate = Curves.easeOutBack;
  static const Curve emphasizedAccelerate = Curves.easeInBack;
  static const Curve elasticOut = Curves.elasticOut;
  static const Curve elasticIn = Curves.elasticIn;
  static const Curve elasticInOut = Curves.elasticInOut;
  static const Curve bounceOut = Curves.bounceOut;
  static const Curve bounceIn = Curves.bounceIn;
  static const Curve bounceInOut = Curves.bounceInOut;
  static const Curve fastOutSlowIn = Curves.fastOutSlowIn;
  static const Curve fastLinearToSlowEaseIn = Curves.fastLinearToSlowEaseIn;
  static const Curve slowMiddle = Curves.slowMiddle;
  static const Curve linear = Curves.linear;
  static const Curve ease = Curves.ease;
  static const Curve easeIn = Curves.easeIn;
  static const Curve easeOut = Curves.easeOut;
  static const Curve easeInOut = Curves.easeInOut;
  static const Curve easeInQuad = Curves.easeInQuad;
  static const Curve easeOutQuad = Curves.easeOutQuad;
  static const Curve easeInOutQuad = Curves.easeInOutQuad;
  static const Curve easeInCubic = Curves.easeInCubic;
  static const Curve easeOutCubic = Curves.easeOutCubic;
  static const Curve easeInOutCubic = Curves.easeInOutCubic;
  static const Curve easeInQuart = Curves.easeInQuart;
  static const Curve easeOutQuart = Curves.easeOutQuart;
  static const Curve easeInOutQuart = Curves.easeInOutQuart;
  static const Curve easeInQuint = Curves.easeInQuint;
  static const Curve easeOutQuint = Curves.easeOutQuint;
  static const Curve easeInOutQuint = Curves.easeInOutQuint;
  static const Curve easeInSine = Curves.easeInSine;
  static const Curve easeOutSine = Curves.easeOutSine;
  static const Curve easeInOutSine = Curves.easeInOutSine;
  static const Curve easeInExpo = Curves.easeInExpo;
  static const Curve easeOutExpo = Curves.easeOutExpo;
  static const Curve easeInOutExpo = Curves.easeInOutExpo;
  static const Curve easeInCirc = Curves.easeInCirc;
  static const Curve easeOutCirc = Curves.easeOutCirc;
  static const Curve easeInOutCirc = Curves.easeInOutCirc;
  // 导航栏切换专用：先极小再弹性放大
  static const Curve navScaleIn = Curves.elasticOut;
  static const Curve navScaleOut = Curves.easeIn;
  static const Curve navFade = Curves.easeOut;
}
