import 'dart:convert';

/// ChatMessage 数据模型
class ChatMessage {
  String id;
  String conversationId;
  String userId;
  String role;
  String content;
  String text;
  List<Map<String,dynamic>> parts;
  List<String> images;
  List<String> files;
  List<String> mentions;
  String model;
  String modelVersion;
  Map<String,dynamic> metadata;
  Map<String,dynamic> usage;
  int promptTokens;
  int completionTokens;
  int totalTokens;
  double cost;
  String finishReason;
  bool isStreaming;
  bool isComplete;
  bool isError;
  String error;
  DateTime createdAt;
  DateTime updatedAt;
  DateTime completedAt;
  int latencyMs;
  int firstTokenMs;
  double tokensPerSecond;
  bool isEdited;
  String originalContent;
  DateTime editedAt;
  bool isDeleted;
  DateTime deletedAt;
  bool isPinned;
  bool isBookmarked;
  bool isStarred;
  bool isLiked;
  int likeCount;
  List<String> reactions;
  Map<String,List<String>> reactionMap;
  bool isShared;
  String shareLink;
  int shareCount;
  int viewCount;
  int copyCount;
  bool isCopied;
  DateTime lastCopiedAt;
  bool isQuoted;
  String quotedMessageId;
  String quotedContent;
  bool isReply;
  String replyToId;
  String replyToContent;
  String replyToUserId;
  bool isForwarded;
  String forwardedFrom;
  bool isSystem;
  String systemType;
  bool isHidden;
  bool isSpoiler;
  bool isNSFW;
  bool isFlagged;
  String flagReason;
  bool isReviewed;
  String reviewStatus;
  String reviewerId;
  DateTime reviewedAt;
  bool isTranslated;
  String translatedContent;
  String sourceLanguage;
  String targetLanguage;
  double translationConfidence;
  bool isSummarized;
  String summary;
  List<String> keyPoints;
  bool isAnalyzed;
  String sentiment;
  double sentimentScore;
  List<String> topics;
  List<String> entities;
  List<String> keywords;
  String language;
  bool isCode;
  String codeLanguage;
  String codeContent;
  bool isCodeExecuted;
  String codeOutput;
  int codeExitCode;
  int codeExecutionTimeMs;
  bool isTable;
  List<List<String>> tableData;
  List<String> tableHeaders;
  bool isList;
  List<String> listItems;
  bool isOrdered;
  bool isQuote;
  String quoteContent;
  String quoteAuthor;
  bool isLink;
  String linkUrl;
  String linkTitle;
  String linkDescription;
  String linkImage;
  bool linkPreviewGenerated;
  bool isImage;
  String imageUrl;
  int imageWidth;
  int imageHeight;
  String imageFormat;
  int imageSize;
  bool imageLoaded;
  bool imageFailed;
  String imageError;
  bool isVideo;
  String videoUrl;
  String videoThumbnail;
  int videoDuration;
  int videoWidth;
  int videoHeight;
  String videoFormat;
  int videoSize;
  bool videoPlayed;
  int videoPlayCount;
  bool isAudio;
  String audioUrl;
  String audioTitle;
  String audioArtist;
  int audioDuration;
  String audioFormat;
  int audioSize;
  bool audioPlayed;
  int audioPlayCount;
  bool isFile;
  String fileName;
  int fileSize;
  String fileType;
  String fileExtension;
  String fileUrl;
  bool fileDownloaded;
  int fileDownloadCount;
  bool filePreviewAvailable;
  String filePreviewUrl;
  int filePages;
  bool isLocation;
  double latitude;
  double longitude;
  String address;
  String placeName;
  String placeId;
  bool isContact;
  String contactName;
  String contactPhone;
  String contactEmail;
  String contactAvatar;
  bool isPoll;
  String pollQuestion;
  List<Map<String,dynamic>> pollOptions;
  bool pollMultiple;
  bool pollAnonymous;
  DateTime pollEndsAt;
  int pollTotalVotes;
  List<String> pollUserVotes;
  bool pollEnded;
  bool isEvent;
  String eventTitle;
  String eventDescription;
  DateTime eventStart;
  DateTime eventEnd;
  String eventLocation;
  bool eventAllDay;
  String eventTimezone;
  int eventAttendeeCount;
  List<String> eventAttendees;
  String eventStatus;
  bool isTask;
  String taskTitle;
  String taskDescription;
  bool taskCompleted;
  DateTime taskDueDate;
  int taskPriority;
  List<String> taskAssignees;
  List<String> taskLabels;
  String taskStatus;
  String taskProject;
  String taskSection;
  int taskOrder;
  DateTime taskCompletedAt;
  String taskCompletedBy;
  bool isSticker;
  String stickerId;
  String stickerUrl;
  String stickerPack;
  bool isGif;
  String gifUrl;
  String gifPreview;
  int gifWidth;
  int gifHeight;
  bool isEmoji;
  String emoji;
  List<String> emojiList;
  bool isVoice;
  String voiceUrl;
  int voiceDuration;
  int voiceSize;
  String voiceFormat;
  bool voicePlayed;
  double voicePlaybackPosition;
  bool voiceTranscribed;
  String voiceTranscript;
  double voiceConfidence;
  bool isWhiteboard;
  String whiteboardUrl;
  String whiteboardData;
  int whiteboardWidth;
  int whiteboardHeight;
  bool isCanvas;
  String canvasUrl;
  String canvasData;
  bool isMindmap;
  String mindmapUrl;
  String mindmapData;
  bool isFlowchart;
  String flowchartUrl;
  String flowchartData;
  bool isTimeline;
  String timelineUrl;
  String timelineData;
  bool isChart;
  String chartType;
  String chartData;
  String chartConfig;
  bool isDiagram;
  String diagramType;
  String diagramData;
  bool isFormula;
  String formula;
  String formulaLatex;
  bool formulaRendered;
  String formulaImage;
  bool isMentionAll;
  bool isMentionHere;
  List<String> mentionedUserIds;
  List<String> mentionedGroupIds;
  bool isSilent;
  bool isImportant;
  bool isUrgent;
  int priority;
  String priorityLabel;
  bool isScheduled;
  DateTime scheduledAt;
  bool isDelayed;
  DateTime delayedUntil;
  bool isExpired;
  DateTime expiresAt;
  bool isEphemeral;
  int ephemeralDuration;
  bool isSelfDestruct;
  DateTime selfDestructAt;
  bool isBurned;
  DateTime burnedAt;
  bool isEncrypted;
  String encryptionAlgorithm;
  String encryptionKeyId;
  bool isSigned;
  String signature;
  String signatureAlgorithm;
  String signerId;
  DateTime signedAt;
  bool signatureVerified;
  bool isVerified;
  String verificationStatus;
  String verifierId;
  DateTime verifiedAt;
  bool isApproved;
  String approverId;
  DateTime approvedAt;
  bool isRejected;
  String rejectReason;
  String rejecterId;
  DateTime rejectedAt;
  bool isPending;
  DateTime pendingSince;
  bool isArchived2;
  DateTime archivedAt;
  bool isRestored;
  DateTime restoredAt;
  String restoredBy;

  ChatMessage({
    required this.id, required this.conversationId, required this.userId, required this.role, required this.content, required this.text, required this.parts, required this.images, required this.files, required this.mentions, required this.model, required this.modelVersion, required this.metadata, required this.usage, required this.promptTokens, required this.completionTokens, required this.totalTokens, required this.cost, required this.finishReason, required this.isStreaming, required this.isComplete, required this.isError, required this.error, required this.createdAt, required this.updatedAt, required this.completedAt, required this.latencyMs, required this.firstTokenMs, required this.tokensPerSecond, required this.isEdited, required this.originalContent, required this.editedAt, required this.isDeleted, required this.deletedAt, required this.isPinned, required this.isBookmarked, required this.isStarred, required this.isLiked, required this.likeCount, required this.reactions, required this.reactionMap, required this.isShared, required this.shareLink, required this.shareCount, required this.viewCount, required this.copyCount, required this.isCopied, required this.lastCopiedAt, required this.isQuoted, required this.quotedMessageId, required this.quotedContent, required this.isReply, required this.replyToId, required this.replyToContent, required this.replyToUserId, required this.isForwarded, required this.forwardedFrom, required this.isSystem, required this.systemType, required this.isHidden, required this.isSpoiler, required this.isNSFW, required this.isFlagged, required this.flagReason, required this.isReviewed, required this.reviewStatus, required this.reviewerId, required this.reviewedAt, required this.isTranslated, required this.translatedContent, required this.sourceLanguage, required this.targetLanguage, required this.translationConfidence, required this.isSummarized, required this.summary, required this.keyPoints, required this.isAnalyzed, required this.sentiment, required this.sentimentScore, required this.topics, required this.entities, required this.keywords, required this.language, required this.isCode, required this.codeLanguage, required this.codeContent, required this.isCodeExecuted, required this.codeOutput, required this.codeExitCode, required this.codeExecutionTimeMs, required this.isTable, required this.tableData, required this.tableHeaders, required this.isList, required this.listItems, required this.isOrdered, required this.isQuote, required this.quoteContent, required this.quoteAuthor, required this.isLink, required this.linkUrl, required this.linkTitle, required this.linkDescription, required this.linkImage, required this.linkPreviewGenerated, required this.isImage, required this.imageUrl, required this.imageWidth, required this.imageHeight, required this.imageFormat, required this.imageSize, required this.imageLoaded, required this.imageFailed, required this.imageError, required this.isVideo, required this.videoUrl, required this.videoThumbnail, required this.videoDuration, required this.videoWidth, required this.videoHeight, required this.videoFormat, required this.videoSize, required this.videoPlayed, required this.videoPlayCount, required this.isAudio, required this.audioUrl, required this.audioTitle, required this.audioArtist, required this.audioDuration, required this.audioFormat, required this.audioSize, required this.audioPlayed, required this.audioPlayCount, required this.isFile, required this.fileName, required this.fileSize, required this.fileType, required this.fileExtension, required this.fileUrl, required this.fileDownloaded, required this.fileDownloadCount, required this.filePreviewAvailable, required this.filePreviewUrl, required this.filePages, required this.isLocation, required this.latitude, required this.longitude, required this.address, required this.placeName, required this.placeId, required this.isContact, required this.contactName, required this.contactPhone, required this.contactEmail, required this.contactAvatar, required this.isPoll, required this.pollQuestion, required this.pollOptions, required this.pollMultiple, required this.pollAnonymous, required this.pollEndsAt, required this.pollTotalVotes, required this.pollUserVotes, required this.pollEnded, required this.isEvent, required this.eventTitle, required this.eventDescription, required this.eventStart, required this.eventEnd, required this.eventLocation, required this.eventAllDay, required this.eventTimezone, required this.eventAttendeeCount, required this.eventAttendees, required this.eventStatus, required this.isTask, required this.taskTitle, required this.taskDescription, required this.taskCompleted, required this.taskDueDate, required this.taskPriority, required this.taskAssignees, required this.taskLabels, required this.taskStatus, required this.taskProject, required this.taskSection, required this.taskOrder, required this.taskCompletedAt, required this.taskCompletedBy, required this.isSticker, required this.stickerId, required this.stickerUrl, required this.stickerPack, required this.isGif, required this.gifUrl, required this.gifPreview, required this.gifWidth, required this.gifHeight, required this.isEmoji, required this.emoji, required this.emojiList, required this.isVoice, required this.voiceUrl, required this.voiceDuration, required this.voiceSize, required this.voiceFormat, required this.voicePlayed, required this.voicePlaybackPosition, required this.voiceTranscribed, required this.voiceTranscript, required this.voiceConfidence, required this.isWhiteboard, required this.whiteboardUrl, required this.whiteboardData, required this.whiteboardWidth, required this.whiteboardHeight, required this.isCanvas, required this.canvasUrl, required this.canvasData, required this.isMindmap, required this.mindmapUrl, required this.mindmapData, required this.isFlowchart, required this.flowchartUrl, required this.flowchartData, required this.isTimeline, required this.timelineUrl, required this.timelineData, required this.isChart, required this.chartType, required this.chartData, required this.chartConfig, required this.isDiagram, required this.diagramType, required this.diagramData, required this.isFormula, required this.formula, required this.formulaLatex, required this.formulaRendered, required this.formulaImage, required this.isMentionAll, required this.isMentionHere, required this.mentionedUserIds, required this.mentionedGroupIds, required this.isSilent, required this.isImportant, required this.isUrgent, required this.priority, required this.priorityLabel, required this.isScheduled, required this.scheduledAt, required this.isDelayed, required this.delayedUntil, required this.isExpired, required this.expiresAt, required this.isEphemeral, required this.ephemeralDuration, required this.isSelfDestruct, required this.selfDestructAt, required this.isBurned, required this.burnedAt, required this.isEncrypted, required this.encryptionAlgorithm, required this.encryptionKeyId, required this.isSigned, required this.signature, required this.signatureAlgorithm, required this.signerId, required this.signedAt, required this.signatureVerified, required this.isVerified, required this.verificationStatus, required this.verifierId, required this.verifiedAt, required this.isApproved, required this.approverId, required this.approvedAt, required this.isRejected, required this.rejectReason, required this.rejecterId, required this.rejectedAt, required this.isPending, required this.pendingSince, required this.isArchived2, required this.archivedAt, required this.isRestored, required this.restoredAt, required this.restoredBy,
  });

  factory ChatMessage.empty() => ChatMessage(
    id: '',
    conversationId: '',
    userId: '',
    role: user,
    content: '',
    text: '',
    parts: [],
    images: [],
    files: [],
    mentions: [],
    model: '',
    modelVersion: '',
    metadata: {},
    usage: {},
    promptTokens: 0,
    completionTokens: 0,
    totalTokens: 0,
    cost: 0.0,
    finishReason: '',
    isStreaming: false,
    isComplete: true,
    isError: false,
    error: '',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    completedAt: DateTime.now(),
    latencyMs: 0,
    firstTokenMs: 0,
    tokensPerSecond: 0.0,
    isEdited: false,
    originalContent: '',
    editedAt: DateTime.now(),
    isDeleted: false,
    deletedAt: DateTime.now(),
    isPinned: false,
    isBookmarked: false,
    isStarred: false,
    isLiked: false,
    likeCount: 0,
    reactions: [],
    reactionMap: {},
    isShared: false,
    shareLink: '',
    shareCount: 0,
    viewCount: 0,
    copyCount: 0,
    isCopied: false,
    lastCopiedAt: DateTime.now(),
    isQuoted: false,
    quotedMessageId: '',
    quotedContent: '',
    isReply: false,
    replyToId: '',
    replyToContent: '',
    replyToUserId: '',
    isForwarded: false,
    forwardedFrom: '',
    isSystem: false,
    systemType: '',
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isFlagged: false,
    flagReason: '',
    isReviewed: false,
    reviewStatus: '',
    reviewerId: '',
    reviewedAt: DateTime.now(),
    isTranslated: false,
    translatedContent: '',
    sourceLanguage: '',
    targetLanguage: '',
    translationConfidence: 0.0,
    isSummarized: false,
    summary: '',
    keyPoints: [],
    isAnalyzed: false,
    sentiment: neutral,
    sentimentScore: 0.0,
    topics: [],
    entities: [],
    keywords: [],
    language: zh,
    isCode: false,
    codeLanguage: '',
    codeContent: '',
    isCodeExecuted: false,
    codeOutput: '',
    codeExitCode: 0,
    codeExecutionTimeMs: 0,
    isTable: false,
    tableData: [],
    tableHeaders: [],
    isList: false,
    listItems: [],
    isOrdered: false,
    isQuote: false,
    quoteContent: '',
    quoteAuthor: '',
    isLink: false,
    linkUrl: '',
    linkTitle: '',
    linkDescription: '',
    linkImage: '',
    linkPreviewGenerated: false,
    isImage: false,
    imageUrl: '',
    imageWidth: 0,
    imageHeight: 0,
    imageFormat: '',
    imageSize: 0,
    imageLoaded: false,
    imageFailed: false,
    imageError: '',
    isVideo: false,
    videoUrl: '',
    videoThumbnail: '',
    videoDuration: 0,
    videoWidth: 0,
    videoHeight: 0,
    videoFormat: '',
    videoSize: 0,
    videoPlayed: false,
    videoPlayCount: 0,
    isAudio: false,
    audioUrl: '',
    audioTitle: '',
    audioArtist: '',
    audioDuration: 0,
    audioFormat: '',
    audioSize: 0,
    audioPlayed: false,
    audioPlayCount: 0,
    isFile: false,
    fileName: '',
    fileSize: 0,
    fileType: '',
    fileExtension: '',
    fileUrl: '',
    fileDownloaded: false,
    fileDownloadCount: 0,
    filePreviewAvailable: false,
    filePreviewUrl: '',
    filePages: 0,
    isLocation: false,
    latitude: 0.0,
    longitude: 0.0,
    address: '',
    placeName: '',
    placeId: '',
    isContact: false,
    contactName: '',
    contactPhone: '',
    contactEmail: '',
    contactAvatar: '',
    isPoll: false,
    pollQuestion: '',
    pollOptions: [],
    pollMultiple: false,
    pollAnonymous: false,
    pollEndsAt: DateTime.now(),
    pollTotalVotes: 0,
    pollUserVotes: [],
    pollEnded: false,
    isEvent: false,
    eventTitle: '',
    eventDescription: '',
    eventStart: DateTime.now(),
    eventEnd: DateTime.now(),
    eventLocation: '',
    eventAllDay: false,
    eventTimezone: '',
    eventAttendeeCount: 0,
    eventAttendees: [],
    eventStatus: '',
    isTask: false,
    taskTitle: '',
    taskDescription: '',
    taskCompleted: false,
    taskDueDate: DateTime.now(),
    taskPriority: 0,
    taskAssignees: [],
    taskLabels: [],
    taskStatus: '',
    taskProject: '',
    taskSection: '',
    taskOrder: 0,
    taskCompletedAt: DateTime.now(),
    taskCompletedBy: '',
    isSticker: false,
    stickerId: '',
    stickerUrl: '',
    stickerPack: '',
    isGif: false,
    gifUrl: '',
    gifPreview: '',
    gifWidth: 0,
    gifHeight: 0,
    isEmoji: false,
    emoji: '',
    emojiList: [],
    isVoice: false,
    voiceUrl: '',
    voiceDuration: 0,
    voiceSize: 0,
    voiceFormat: '',
    voicePlayed: false,
    voicePlaybackPosition: 0.0,
    voiceTranscribed: false,
    voiceTranscript: '',
    voiceConfidence: 0.0,
    isWhiteboard: false,
    whiteboardUrl: '',
    whiteboardData: '',
    whiteboardWidth: 0,
    whiteboardHeight: 0,
    isCanvas: false,
    canvasUrl: '',
    canvasData: '',
    isMindmap: false,
    mindmapUrl: '',
    mindmapData: '',
    isFlowchart: false,
    flowchartUrl: '',
    flowchartData: '',
    isTimeline: false,
    timelineUrl: '',
    timelineData: '',
    isChart: false,
    chartType: '',
    chartData: '',
    chartConfig: '',
    isDiagram: false,
    diagramType: '',
    diagramData: '',
    isFormula: false,
    formula: '',
    formulaLatex: '',
    formulaRendered: false,
    formulaImage: '',
    isMentionAll: false,
    isMentionHere: false,
    mentionedUserIds: [],
    mentionedGroupIds: [],
    isSilent: false,
    isImportant: false,
    isUrgent: false,
    priority: 0,
    priorityLabel: '',
    isScheduled: false,
    scheduledAt: DateTime.now(),
    isDelayed: false,
    delayedUntil: DateTime.now(),
    isExpired: false,
    expiresAt: DateTime.now(),
    isEphemeral: false,
    ephemeralDuration: 0,
    isSelfDestruct: false,
    selfDestructAt: DateTime.now(),
    isBurned: false,
    burnedAt: DateTime.now(),
    isEncrypted: false,
    encryptionAlgorithm: '',
    encryptionKeyId: '',
    isSigned: false,
    signature: '',
    signatureAlgorithm: '',
    signerId: '',
    signedAt: DateTime.now(),
    signatureVerified: false,
    isVerified: false,
    verificationStatus: '',
    verifierId: '',
    verifiedAt: DateTime.now(),
    isApproved: false,
    approverId: '',
    approvedAt: DateTime.now(),
    isRejected: false,
    rejectReason: '',
    rejecterId: '',
    rejectedAt: DateTime.now(),
    isPending: false,
    pendingSince: DateTime.now(),
    isArchived2: false,
    archivedAt: DateTime.now(),
    isRestored: false,
    restoredAt: DateTime.now(),
    restoredBy: '',
  );

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
    id: json['id'] ?? '',
    conversationId: json['conversationId'] ?? '',
    userId: json['userId'] ?? '',
    role: json['role'] ?? '',
    content: json['content'] ?? '',
    text: json['text'] ?? '',
    parts: json['parts'] != null ? List<Map>.from(json['parts']) : [],
    images: json['images'] != null ? List<String>.from(json['images']) : [],
    files: json['files'] != null ? List<String>.from(json['files']) : [],
    mentions: json['mentions'] != null ? List<String>.from(json['mentions']) : [],
    model: json['model'] ?? '',
    modelVersion: json['modelVersion'] ?? '',
    metadata: json['metadata'] != null ? Map<String,dynamic>.from(json['metadata']) : {},
    usage: json['usage'] != null ? Map<String,dynamic>.from(json['usage']) : {},
    promptTokens: json['promptTokens'] ?? 0,
    completionTokens: json['completionTokens'] ?? 0,
    totalTokens: json['totalTokens'] ?? 0,
    cost: (json['cost'] ?? 0.0).toDouble(),
    finishReason: json['finishReason'] ?? '',
    isStreaming: json['isStreaming'] ?? false,
    isComplete: json['isComplete'] ?? false,
    isError: json['isError'] ?? false,
    error: json['error'] ?? '',
    createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : DateTime.now(),
    updatedAt: json['updatedAt'] != null ? DateTime.parse(json['updatedAt']) : DateTime.now(),
    completedAt: json['completedAt'] != null ? DateTime.parse(json['completedAt']) : DateTime.now(),
    latencyMs: json['latencyMs'] ?? 0,
    firstTokenMs: json['firstTokenMs'] ?? 0,
    tokensPerSecond: (json['tokensPerSecond'] ?? 0.0).toDouble(),
    isEdited: json['isEdited'] ?? false,
    originalContent: json['originalContent'] ?? '',
    editedAt: json['editedAt'] != null ? DateTime.parse(json['editedAt']) : DateTime.now(),
    isDeleted: json['isDeleted'] ?? false,
    deletedAt: json['deletedAt'] != null ? DateTime.parse(json['deletedAt']) : DateTime.now(),
    isPinned: json['isPinned'] ?? false,
    isBookmarked: json['isBookmarked'] ?? false,
    isStarred: json['isStarred'] ?? false,
    isLiked: json['isLiked'] ?? false,
    likeCount: json['likeCount'] ?? 0,
    reactions: json['reactions'] != null ? List<String>.from(json['reactions']) : [],
    reactionMap: json['reactionMap'] != null ? Map<String,dynamic>.from(json['reactionMap']) : {},
    isShared: json['isShared'] ?? false,
    shareLink: json['shareLink'] ?? '',
    shareCount: json['shareCount'] ?? 0,
    viewCount: json['viewCount'] ?? 0,
    copyCount: json['copyCount'] ?? 0,
    isCopied: json['isCopied'] ?? false,
    lastCopiedAt: json['lastCopiedAt'] != null ? DateTime.parse(json['lastCopiedAt']) : DateTime.now(),
    isQuoted: json['isQuoted'] ?? false,
    quotedMessageId: json['quotedMessageId'] ?? '',
    quotedContent: json['quotedContent'] ?? '',
    isReply: json['isReply'] ?? false,
    replyToId: json['replyToId'] ?? '',
    replyToContent: json['replyToContent'] ?? '',
    replyToUserId: json['replyToUserId'] ?? '',
    isForwarded: json['isForwarded'] ?? false,
    forwardedFrom: json['forwardedFrom'] ?? '',
    isSystem: json['isSystem'] ?? false,
    systemType: json['systemType'] ?? '',
    isHidden: json['isHidden'] ?? false,
    isSpoiler: json['isSpoiler'] ?? false,
    isNSFW: json['isNSFW'] ?? false,
    isFlagged: json['isFlagged'] ?? false,
    flagReason: json['flagReason'] ?? '',
    isReviewed: json['isReviewed'] ?? false,
    reviewStatus: json['reviewStatus'] ?? '',
    reviewerId: json['reviewerId'] ?? '',
    reviewedAt: json['reviewedAt'] != null ? DateTime.parse(json['reviewedAt']) : DateTime.now(),
    isTranslated: json['isTranslated'] ?? false,
    translatedContent: json['translatedContent'] ?? '',
    sourceLanguage: json['sourceLanguage'] ?? '',
    targetLanguage: json['targetLanguage'] ?? '',
    translationConfidence: (json['translationConfidence'] ?? 0.0).toDouble(),
    isSummarized: json['isSummarized'] ?? false,
    summary: json['summary'] ?? '',
    keyPoints: json['keyPoints'] != null ? List<String>.from(json['keyPoints']) : [],
    isAnalyzed: json['isAnalyzed'] ?? false,
    sentiment: json['sentiment'] ?? '',
    sentimentScore: (json['sentimentScore'] ?? 0.0).toDouble(),
    topics: json['topics'] != null ? List<String>.from(json['topics']) : [],
    entities: json['entities'] != null ? List<String>.from(json['entities']) : [],
    keywords: json['keywords'] != null ? List<String>.from(json['keywords']) : [],
    language: json['language'] ?? '',
    isCode: json['isCode'] ?? false,
    codeLanguage: json['codeLanguage'] ?? '',
    codeContent: json['codeContent'] ?? '',
    isCodeExecuted: json['isCodeExecuted'] ?? false,
    codeOutput: json['codeOutput'] ?? '',
    codeExitCode: json['codeExitCode'] ?? 0,
    codeExecutionTimeMs: json['codeExecutionTimeMs'] ?? 0,
    isTable: json['isTable'] ?? false,
    tableData: json['tableData'] != null ? List<List>.from(json['tableData']) : [],
    tableHeaders: json['tableHeaders'] != null ? List<String>.from(json['tableHeaders']) : [],
    isList: json['isList'] ?? false,
    listItems: json['listItems'] != null ? List<String>.from(json['listItems']) : [],
    isOrdered: json['isOrdered'] ?? false,
    isQuote: json['isQuote'] ?? false,
    quoteContent: json['quoteContent'] ?? '',
    quoteAuthor: json['quoteAuthor'] ?? '',
    isLink: json['isLink'] ?? false,
    linkUrl: json['linkUrl'] ?? '',
    linkTitle: json['linkTitle'] ?? '',
    linkDescription: json['linkDescription'] ?? '',
    linkImage: json['linkImage'] ?? '',
    linkPreviewGenerated: json['linkPreviewGenerated'] ?? false,
    isImage: json['isImage'] ?? false,
    imageUrl: json['imageUrl'] ?? '',
    imageWidth: json['imageWidth'] ?? 0,
    imageHeight: json['imageHeight'] ?? 0,
    imageFormat: json['imageFormat'] ?? '',
    imageSize: json['imageSize'] ?? 0,
    imageLoaded: json['imageLoaded'] ?? false,
    imageFailed: json['imageFailed'] ?? false,
    imageError: json['imageError'] ?? '',
    isVideo: json['isVideo'] ?? false,
    videoUrl: json['videoUrl'] ?? '',
    videoThumbnail: json['videoThumbnail'] ?? '',
    videoDuration: json['videoDuration'] ?? 0,
    videoWidth: json['videoWidth'] ?? 0,
    videoHeight: json['videoHeight'] ?? 0,
    videoFormat: json['videoFormat'] ?? '',
    videoSize: json['videoSize'] ?? 0,
    videoPlayed: json['videoPlayed'] ?? false,
    videoPlayCount: json['videoPlayCount'] ?? 0,
    isAudio: json['isAudio'] ?? false,
    audioUrl: json['audioUrl'] ?? '',
    audioTitle: json['audioTitle'] ?? '',
    audioArtist: json['audioArtist'] ?? '',
    audioDuration: json['audioDuration'] ?? 0,
    audioFormat: json['audioFormat'] ?? '',
    audioSize: json['audioSize'] ?? 0,
    audioPlayed: json['audioPlayed'] ?? false,
    audioPlayCount: json['audioPlayCount'] ?? 0,
    isFile: json['isFile'] ?? false,
    fileName: json['fileName'] ?? '',
    fileSize: json['fileSize'] ?? 0,
    fileType: json['fileType'] ?? '',
    fileExtension: json['fileExtension'] ?? '',
    fileUrl: json['fileUrl'] ?? '',
    fileDownloaded: json['fileDownloaded'] ?? false,
    fileDownloadCount: json['fileDownloadCount'] ?? 0,
    filePreviewAvailable: json['filePreviewAvailable'] ?? false,
    filePreviewUrl: json['filePreviewUrl'] ?? '',
    filePages: json['filePages'] ?? 0,
    isLocation: json['isLocation'] ?? false,
    latitude: (json['latitude'] ?? 0.0).toDouble(),
    longitude: (json['longitude'] ?? 0.0).toDouble(),
    address: json['address'] ?? '',
    placeName: json['placeName'] ?? '',
    placeId: json['placeId'] ?? '',
    isContact: json['isContact'] ?? false,
    contactName: json['contactName'] ?? '',
    contactPhone: json['contactPhone'] ?? '',
    contactEmail: json['contactEmail'] ?? '',
    contactAvatar: json['contactAvatar'] ?? '',
    isPoll: json['isPoll'] ?? false,
    pollQuestion: json['pollQuestion'] ?? '',
    pollOptions: json['pollOptions'] != null ? List<Map>.from(json['pollOptions']) : [],
    pollMultiple: json['pollMultiple'] ?? false,
    pollAnonymous: json['pollAnonymous'] ?? false,
    pollEndsAt: json['pollEndsAt'] != null ? DateTime.parse(json['pollEndsAt']) : DateTime.now(),
    pollTotalVotes: json['pollTotalVotes'] ?? 0,
    pollUserVotes: json['pollUserVotes'] != null ? List<String>.from(json['pollUserVotes']) : [],
    pollEnded: json['pollEnded'] ?? false,
    isEvent: json['isEvent'] ?? false,
    eventTitle: json['eventTitle'] ?? '',
    eventDescription: json['eventDescription'] ?? '',
    eventStart: json['eventStart'] != null ? DateTime.parse(json['eventStart']) : DateTime.now(),
    eventEnd: json['eventEnd'] != null ? DateTime.parse(json['eventEnd']) : DateTime.now(),
    eventLocation: json['eventLocation'] ?? '',
    eventAllDay: json['eventAllDay'] ?? false,
    eventTimezone: json['eventTimezone'] ?? '',
    eventAttendeeCount: json['eventAttendeeCount'] ?? 0,
    eventAttendees: json['eventAttendees'] != null ? List<String>.from(json['eventAttendees']) : [],
    eventStatus: json['eventStatus'] ?? '',
    isTask: json['isTask'] ?? false,
    taskTitle: json['taskTitle'] ?? '',
    taskDescription: json['taskDescription'] ?? '',
    taskCompleted: json['taskCompleted'] ?? false,
    taskDueDate: json['taskDueDate'] != null ? DateTime.parse(json['taskDueDate']) : DateTime.now(),
    taskPriority: json['taskPriority'] ?? 0,
    taskAssignees: json['taskAssignees'] != null ? List<String>.from(json['taskAssignees']) : [],
    taskLabels: json['taskLabels'] != null ? List<String>.from(json['taskLabels']) : [],
    taskStatus: json['taskStatus'] ?? '',
    taskProject: json['taskProject'] ?? '',
    taskSection: json['taskSection'] ?? '',
    taskOrder: json['taskOrder'] ?? 0,
    taskCompletedAt: json['taskCompletedAt'] != null ? DateTime.parse(json['taskCompletedAt']) : DateTime.now(),
    taskCompletedBy: json['taskCompletedBy'] ?? '',
    isSticker: json['isSticker'] ?? false,
    stickerId: json['stickerId'] ?? '',
    stickerUrl: json['stickerUrl'] ?? '',
    stickerPack: json['stickerPack'] ?? '',
    isGif: json['isGif'] ?? false,
    gifUrl: json['gifUrl'] ?? '',
    gifPreview: json['gifPreview'] ?? '',
    gifWidth: json['gifWidth'] ?? 0,
    gifHeight: json['gifHeight'] ?? 0,
    isEmoji: json['isEmoji'] ?? false,
    emoji: json['emoji'] ?? '',
    emojiList: json['emojiList'] != null ? List<String>.from(json['emojiList']) : [],
    isVoice: json['isVoice'] ?? false,
    voiceUrl: json['voiceUrl'] ?? '',
    voiceDuration: json['voiceDuration'] ?? 0,
    voiceSize: json['voiceSize'] ?? 0,
    voiceFormat: json['voiceFormat'] ?? '',
    voicePlayed: json['voicePlayed'] ?? false,
    voicePlaybackPosition: (json['voicePlaybackPosition'] ?? 0.0).toDouble(),
    voiceTranscribed: json['voiceTranscribed'] ?? false,
    voiceTranscript: json['voiceTranscript'] ?? '',
    voiceConfidence: (json['voiceConfidence'] ?? 0.0).toDouble(),
    isWhiteboard: json['isWhiteboard'] ?? false,
    whiteboardUrl: json['whiteboardUrl'] ?? '',
    whiteboardData: json['whiteboardData'] ?? '',
    whiteboardWidth: json['whiteboardWidth'] ?? 0,
    whiteboardHeight: json['whiteboardHeight'] ?? 0,
    isCanvas: json['isCanvas'] ?? false,
    canvasUrl: json['canvasUrl'] ?? '',
    canvasData: json['canvasData'] ?? '',
    isMindmap: json['isMindmap'] ?? false,
    mindmapUrl: json['mindmapUrl'] ?? '',
    mindmapData: json['mindmapData'] ?? '',
    isFlowchart: json['isFlowchart'] ?? false,
    flowchartUrl: json['flowchartUrl'] ?? '',
    flowchartData: json['flowchartData'] ?? '',
    isTimeline: json['isTimeline'] ?? false,
    timelineUrl: json['timelineUrl'] ?? '',
    timelineData: json['timelineData'] ?? '',
    isChart: json['isChart'] ?? false,
    chartType: json['chartType'] ?? '',
    chartData: json['chartData'] ?? '',
    chartConfig: json['chartConfig'] ?? '',
    isDiagram: json['isDiagram'] ?? false,
    diagramType: json['diagramType'] ?? '',
    diagramData: json['diagramData'] ?? '',
    isFormula: json['isFormula'] ?? false,
    formula: json['formula'] ?? '',
    formulaLatex: json['formulaLatex'] ?? '',
    formulaRendered: json['formulaRendered'] ?? false,
    formulaImage: json['formulaImage'] ?? '',
    isMentionAll: json['isMentionAll'] ?? false,
    isMentionHere: json['isMentionHere'] ?? false,
    mentionedUserIds: json['mentionedUserIds'] != null ? List<String>.from(json['mentionedUserIds']) : [],
    mentionedGroupIds: json['mentionedGroupIds'] != null ? List<String>.from(json['mentionedGroupIds']) : [],
    isSilent: json['isSilent'] ?? false,
    isImportant: json['isImportant'] ?? false,
    isUrgent: json['isUrgent'] ?? false,
    priority: json['priority'] ?? 0,
    priorityLabel: json['priorityLabel'] ?? '',
    isScheduled: json['isScheduled'] ?? false,
    scheduledAt: json['scheduledAt'] != null ? DateTime.parse(json['scheduledAt']) : DateTime.now(),
    isDelayed: json['isDelayed'] ?? false,
    delayedUntil: json['delayedUntil'] != null ? DateTime.parse(json['delayedUntil']) : DateTime.now(),
    isExpired: json['isExpired'] ?? false,
    expiresAt: json['expiresAt'] != null ? DateTime.parse(json['expiresAt']) : DateTime.now(),
    isEphemeral: json['isEphemeral'] ?? false,
    ephemeralDuration: json['ephemeralDuration'] ?? 0,
    isSelfDestruct: json['isSelfDestruct'] ?? false,
    selfDestructAt: json['selfDestructAt'] != null ? DateTime.parse(json['selfDestructAt']) : DateTime.now(),
    isBurned: json['isBurned'] ?? false,
    burnedAt: json['burnedAt'] != null ? DateTime.parse(json['burnedAt']) : DateTime.now(),
    isEncrypted: json['isEncrypted'] ?? false,
    encryptionAlgorithm: json['encryptionAlgorithm'] ?? '',
    encryptionKeyId: json['encryptionKeyId'] ?? '',
    isSigned: json['isSigned'] ?? false,
    signature: json['signature'] ?? '',
    signatureAlgorithm: json['signatureAlgorithm'] ?? '',
    signerId: json['signerId'] ?? '',
    signedAt: json['signedAt'] != null ? DateTime.parse(json['signedAt']) : DateTime.now(),
    signatureVerified: json['signatureVerified'] ?? false,
    isVerified: json['isVerified'] ?? false,
    verificationStatus: json['verificationStatus'] ?? '',
    verifierId: json['verifierId'] ?? '',
    verifiedAt: json['verifiedAt'] != null ? DateTime.parse(json['verifiedAt']) : DateTime.now(),
    isApproved: json['isApproved'] ?? false,
    approverId: json['approverId'] ?? '',
    approvedAt: json['approvedAt'] != null ? DateTime.parse(json['approvedAt']) : DateTime.now(),
    isRejected: json['isRejected'] ?? false,
    rejectReason: json['rejectReason'] ?? '',
    rejecterId: json['rejecterId'] ?? '',
    rejectedAt: json['rejectedAt'] != null ? DateTime.parse(json['rejectedAt']) : DateTime.now(),
    isPending: json['isPending'] ?? false,
    pendingSince: json['pendingSince'] != null ? DateTime.parse(json['pendingSince']) : DateTime.now(),
    isArchived2: json['isArchived2'] ?? false,
    archivedAt: json['archivedAt'] != null ? DateTime.parse(json['archivedAt']) : DateTime.now(),
    isRestored: json['isRestored'] ?? false,
    restoredAt: json['restoredAt'] != null ? DateTime.parse(json['restoredAt']) : DateTime.now(),
    restoredBy: json['restoredBy'] ?? '',
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'conversationId': conversationId,
    'userId': userId,
    'role': role,
    'content': content,
    'text': text,
    'parts': parts,
    'images': images,
    'files': files,
    'mentions': mentions,
    'model': model,
    'modelVersion': modelVersion,
    'metadata': metadata,
    'usage': usage,
    'promptTokens': promptTokens,
    'completionTokens': completionTokens,
    'totalTokens': totalTokens,
    'cost': cost,
    'finishReason': finishReason,
    'isStreaming': isStreaming,
    'isComplete': isComplete,
    'isError': isError,
    'error': error,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'completedAt': completedAt.toIso8601String(),
    'latencyMs': latencyMs,
    'firstTokenMs': firstTokenMs,
    'tokensPerSecond': tokensPerSecond,
    'isEdited': isEdited,
    'originalContent': originalContent,
    'editedAt': editedAt.toIso8601String(),
    'isDeleted': isDeleted,
    'deletedAt': deletedAt.toIso8601String(),
    'isPinned': isPinned,
    'isBookmarked': isBookmarked,
    'isStarred': isStarred,
    'isLiked': isLiked,
    'likeCount': likeCount,
    'reactions': reactions,
    'reactionMap': reactionMap,
    'isShared': isShared,
    'shareLink': shareLink,
    'shareCount': shareCount,
    'viewCount': viewCount,
    'copyCount': copyCount,
    'isCopied': isCopied,
    'lastCopiedAt': lastCopiedAt.toIso8601String(),
    'isQuoted': isQuoted,
    'quotedMessageId': quotedMessageId,
    'quotedContent': quotedContent,
    'isReply': isReply,
    'replyToId': replyToId,
    'replyToContent': replyToContent,
    'replyToUserId': replyToUserId,
    'isForwarded': isForwarded,
    'forwardedFrom': forwardedFrom,
    'isSystem': isSystem,
    'systemType': systemType,
    'isHidden': isHidden,
    'isSpoiler': isSpoiler,
    'isNSFW': isNSFW,
    'isFlagged': isFlagged,
    'flagReason': flagReason,
    'isReviewed': isReviewed,
    'reviewStatus': reviewStatus,
    'reviewerId': reviewerId,
    'reviewedAt': reviewedAt.toIso8601String(),
    'isTranslated': isTranslated,
    'translatedContent': translatedContent,
    'sourceLanguage': sourceLanguage,
    'targetLanguage': targetLanguage,
    'translationConfidence': translationConfidence,
    'isSummarized': isSummarized,
    'summary': summary,
    'keyPoints': keyPoints,
    'isAnalyzed': isAnalyzed,
    'sentiment': sentiment,
    'sentimentScore': sentimentScore,
    'topics': topics,
    'entities': entities,
    'keywords': keywords,
    'language': language,
    'isCode': isCode,
    'codeLanguage': codeLanguage,
    'codeContent': codeContent,
    'isCodeExecuted': isCodeExecuted,
    'codeOutput': codeOutput,
    'codeExitCode': codeExitCode,
    'codeExecutionTimeMs': codeExecutionTimeMs,
    'isTable': isTable,
    'tableData': tableData,
    'tableHeaders': tableHeaders,
    'isList': isList,
    'listItems': listItems,
    'isOrdered': isOrdered,
    'isQuote': isQuote,
    'quoteContent': quoteContent,
    'quoteAuthor': quoteAuthor,
    'isLink': isLink,
    'linkUrl': linkUrl,
    'linkTitle': linkTitle,
    'linkDescription': linkDescription,
    'linkImage': linkImage,
    'linkPreviewGenerated': linkPreviewGenerated,
    'isImage': isImage,
    'imageUrl': imageUrl,
    'imageWidth': imageWidth,
    'imageHeight': imageHeight,
    'imageFormat': imageFormat,
    'imageSize': imageSize,
    'imageLoaded': imageLoaded,
    'imageFailed': imageFailed,
    'imageError': imageError,
    'isVideo': isVideo,
    'videoUrl': videoUrl,
    'videoThumbnail': videoThumbnail,
    'videoDuration': videoDuration,
    'videoWidth': videoWidth,
    'videoHeight': videoHeight,
    'videoFormat': videoFormat,
    'videoSize': videoSize,
    'videoPlayed': videoPlayed,
    'videoPlayCount': videoPlayCount,
    'isAudio': isAudio,
    'audioUrl': audioUrl,
    'audioTitle': audioTitle,
    'audioArtist': audioArtist,
    'audioDuration': audioDuration,
    'audioFormat': audioFormat,
    'audioSize': audioSize,
    'audioPlayed': audioPlayed,
    'audioPlayCount': audioPlayCount,
    'isFile': isFile,
    'fileName': fileName,
    'fileSize': fileSize,
    'fileType': fileType,
    'fileExtension': fileExtension,
    'fileUrl': fileUrl,
    'fileDownloaded': fileDownloaded,
    'fileDownloadCount': fileDownloadCount,
    'filePreviewAvailable': filePreviewAvailable,
    'filePreviewUrl': filePreviewUrl,
    'filePages': filePages,
    'isLocation': isLocation,
    'latitude': latitude,
    'longitude': longitude,
    'address': address,
    'placeName': placeName,
    'placeId': placeId,
    'isContact': isContact,
    'contactName': contactName,
    'contactPhone': contactPhone,
    'contactEmail': contactEmail,
    'contactAvatar': contactAvatar,
    'isPoll': isPoll,
    'pollQuestion': pollQuestion,
    'pollOptions': pollOptions,
    'pollMultiple': pollMultiple,
    'pollAnonymous': pollAnonymous,
    'pollEndsAt': pollEndsAt.toIso8601String(),
    'pollTotalVotes': pollTotalVotes,
    'pollUserVotes': pollUserVotes,
    'pollEnded': pollEnded,
    'isEvent': isEvent,
    'eventTitle': eventTitle,
    'eventDescription': eventDescription,
    'eventStart': eventStart.toIso8601String(),
    'eventEnd': eventEnd.toIso8601String(),
    'eventLocation': eventLocation,
    'eventAllDay': eventAllDay,
    'eventTimezone': eventTimezone,
    'eventAttendeeCount': eventAttendeeCount,
    'eventAttendees': eventAttendees,
    'eventStatus': eventStatus,
    'isTask': isTask,
    'taskTitle': taskTitle,
    'taskDescription': taskDescription,
    'taskCompleted': taskCompleted,
    'taskDueDate': taskDueDate.toIso8601String(),
    'taskPriority': taskPriority,
    'taskAssignees': taskAssignees,
    'taskLabels': taskLabels,
    'taskStatus': taskStatus,
    'taskProject': taskProject,
    'taskSection': taskSection,
    'taskOrder': taskOrder,
    'taskCompletedAt': taskCompletedAt.toIso8601String(),
    'taskCompletedBy': taskCompletedBy,
    'isSticker': isSticker,
    'stickerId': stickerId,
    'stickerUrl': stickerUrl,
    'stickerPack': stickerPack,
    'isGif': isGif,
    'gifUrl': gifUrl,
    'gifPreview': gifPreview,
    'gifWidth': gifWidth,
    'gifHeight': gifHeight,
    'isEmoji': isEmoji,
    'emoji': emoji,
    'emojiList': emojiList,
    'isVoice': isVoice,
    'voiceUrl': voiceUrl,
    'voiceDuration': voiceDuration,
    'voiceSize': voiceSize,
    'voiceFormat': voiceFormat,
    'voicePlayed': voicePlayed,
    'voicePlaybackPosition': voicePlaybackPosition,
    'voiceTranscribed': voiceTranscribed,
    'voiceTranscript': voiceTranscript,
    'voiceConfidence': voiceConfidence,
    'isWhiteboard': isWhiteboard,
    'whiteboardUrl': whiteboardUrl,
    'whiteboardData': whiteboardData,
    'whiteboardWidth': whiteboardWidth,
    'whiteboardHeight': whiteboardHeight,
    'isCanvas': isCanvas,
    'canvasUrl': canvasUrl,
    'canvasData': canvasData,
    'isMindmap': isMindmap,
    'mindmapUrl': mindmapUrl,
    'mindmapData': mindmapData,
    'isFlowchart': isFlowchart,
    'flowchartUrl': flowchartUrl,
    'flowchartData': flowchartData,
    'isTimeline': isTimeline,
    'timelineUrl': timelineUrl,
    'timelineData': timelineData,
    'isChart': isChart,
    'chartType': chartType,
    'chartData': chartData,
    'chartConfig': chartConfig,
    'isDiagram': isDiagram,
    'diagramType': diagramType,
    'diagramData': diagramData,
    'isFormula': isFormula,
    'formula': formula,
    'formulaLatex': formulaLatex,
    'formulaRendered': formulaRendered,
    'formulaImage': formulaImage,
    'isMentionAll': isMentionAll,
    'isMentionHere': isMentionHere,
    'mentionedUserIds': mentionedUserIds,
    'mentionedGroupIds': mentionedGroupIds,
    'isSilent': isSilent,
    'isImportant': isImportant,
    'isUrgent': isUrgent,
    'priority': priority,
    'priorityLabel': priorityLabel,
    'isScheduled': isScheduled,
    'scheduledAt': scheduledAt.toIso8601String(),
    'isDelayed': isDelayed,
    'delayedUntil': delayedUntil.toIso8601String(),
    'isExpired': isExpired,
    'expiresAt': expiresAt.toIso8601String(),
    'isEphemeral': isEphemeral,
    'ephemeralDuration': ephemeralDuration,
    'isSelfDestruct': isSelfDestruct,
    'selfDestructAt': selfDestructAt.toIso8601String(),
    'isBurned': isBurned,
    'burnedAt': burnedAt.toIso8601String(),
    'isEncrypted': isEncrypted,
    'encryptionAlgorithm': encryptionAlgorithm,
    'encryptionKeyId': encryptionKeyId,
    'isSigned': isSigned,
    'signature': signature,
    'signatureAlgorithm': signatureAlgorithm,
    'signerId': signerId,
    'signedAt': signedAt.toIso8601String(),
    'signatureVerified': signatureVerified,
    'isVerified': isVerified,
    'verificationStatus': verificationStatus,
    'verifierId': verifierId,
    'verifiedAt': verifiedAt.toIso8601String(),
    'isApproved': isApproved,
    'approverId': approverId,
    'approvedAt': approvedAt.toIso8601String(),
    'isRejected': isRejected,
    'rejectReason': rejectReason,
    'rejecterId': rejecterId,
    'rejectedAt': rejectedAt.toIso8601String(),
    'isPending': isPending,
    'pendingSince': pendingSince.toIso8601String(),
    'isArchived2': isArchived2,
    'archivedAt': archivedAt.toIso8601String(),
    'isRestored': isRestored,
    'restoredAt': restoredAt.toIso8601String(),
    'restoredBy': restoredBy,
  };

  ChatMessage copyWith({
    String? id,
    String? conversationId,
    String? userId,
    String? role,
    String? content,
    String? text,
    List<Map<String,dynamic>>? parts,
    List<String>? images,
    List<String>? files,
    List<String>? mentions,
    String? model,
    String? modelVersion,
    Map<String,dynamic>? metadata,
    Map<String,dynamic>? usage,
    int? promptTokens,
    int? completionTokens,
    int? totalTokens,
    double? cost,
    String? finishReason,
    bool? isStreaming,
    bool? isComplete,
    bool? isError,
    String? error,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? completedAt,
    int? latencyMs,
    int? firstTokenMs,
    double? tokensPerSecond,
    bool? isEdited,
    String? originalContent,
    DateTime? editedAt,
    bool? isDeleted,
    DateTime? deletedAt,
    bool? isPinned,
    bool? isBookmarked,
    bool? isStarred,
    bool? isLiked,
    int? likeCount,
    List<String>? reactions,
    Map<String,List<String>>? reactionMap,
    bool? isShared,
    String? shareLink,
    int? shareCount,
    int? viewCount,
    int? copyCount,
    bool? isCopied,
    DateTime? lastCopiedAt,
    bool? isQuoted,
    String? quotedMessageId,
    String? quotedContent,
    bool? isReply,
    String? replyToId,
    String? replyToContent,
    String? replyToUserId,
    bool? isForwarded,
    String? forwardedFrom,
    bool? isSystem,
    String? systemType,
    bool? isHidden,
    bool? isSpoiler,
    bool? isNSFW,
    bool? isFlagged,
    String? flagReason,
    bool? isReviewed,
    String? reviewStatus,
    String? reviewerId,
    DateTime? reviewedAt,
    bool? isTranslated,
    String? translatedContent,
    String? sourceLanguage,
    String? targetLanguage,
    double? translationConfidence,
    bool? isSummarized,
    String? summary,
    List<String>? keyPoints,
    bool? isAnalyzed,
    String? sentiment,
    double? sentimentScore,
    List<String>? topics,
    List<String>? entities,
    List<String>? keywords,
    String? language,
    bool? isCode,
    String? codeLanguage,
    String? codeContent,
    bool? isCodeExecuted,
    String? codeOutput,
    int? codeExitCode,
    int? codeExecutionTimeMs,
    bool? isTable,
    List<List<String>>? tableData,
    List<String>? tableHeaders,
    bool? isList,
    List<String>? listItems,
    bool? isOrdered,
    bool? isQuote,
    String? quoteContent,
    String? quoteAuthor,
    bool? isLink,
    String? linkUrl,
    String? linkTitle,
    String? linkDescription,
    String? linkImage,
    bool? linkPreviewGenerated,
    bool? isImage,
    String? imageUrl,
    int? imageWidth,
    int? imageHeight,
    String? imageFormat,
    int? imageSize,
    bool? imageLoaded,
    bool? imageFailed,
    String? imageError,
    bool? isVideo,
    String? videoUrl,
    String? videoThumbnail,
    int? videoDuration,
    int? videoWidth,
    int? videoHeight,
    String? videoFormat,
    int? videoSize,
    bool? videoPlayed,
    int? videoPlayCount,
    bool? isAudio,
    String? audioUrl,
    String? audioTitle,
    String? audioArtist,
    int? audioDuration,
    String? audioFormat,
    int? audioSize,
    bool? audioPlayed,
    int? audioPlayCount,
    bool? isFile,
    String? fileName,
    int? fileSize,
    String? fileType,
    String? fileExtension,
    String? fileUrl,
    bool? fileDownloaded,
    int? fileDownloadCount,
    bool? filePreviewAvailable,
    String? filePreviewUrl,
    int? filePages,
    bool? isLocation,
    double? latitude,
    double? longitude,
    String? address,
    String? placeName,
    String? placeId,
    bool? isContact,
    String? contactName,
    String? contactPhone,
    String? contactEmail,
    String? contactAvatar,
    bool? isPoll,
    String? pollQuestion,
    List<Map<String,dynamic>>? pollOptions,
    bool? pollMultiple,
    bool? pollAnonymous,
    DateTime? pollEndsAt,
    int? pollTotalVotes,
    List<String>? pollUserVotes,
    bool? pollEnded,
    bool? isEvent,
    String? eventTitle,
    String? eventDescription,
    DateTime? eventStart,
    DateTime? eventEnd,
    String? eventLocation,
    bool? eventAllDay,
    String? eventTimezone,
    int? eventAttendeeCount,
    List<String>? eventAttendees,
    String? eventStatus,
    bool? isTask,
    String? taskTitle,
    String? taskDescription,
    bool? taskCompleted,
    DateTime? taskDueDate,
    int? taskPriority,
    List<String>? taskAssignees,
    List<String>? taskLabels,
    String? taskStatus,
    String? taskProject,
    String? taskSection,
    int? taskOrder,
    DateTime? taskCompletedAt,
    String? taskCompletedBy,
    bool? isSticker,
    String? stickerId,
    String? stickerUrl,
    String? stickerPack,
    bool? isGif,
    String? gifUrl,
    String? gifPreview,
    int? gifWidth,
    int? gifHeight,
    bool? isEmoji,
    String? emoji,
    List<String>? emojiList,
    bool? isVoice,
    String? voiceUrl,
    int? voiceDuration,
    int? voiceSize,
    String? voiceFormat,
    bool? voicePlayed,
    double? voicePlaybackPosition,
    bool? voiceTranscribed,
    String? voiceTranscript,
    double? voiceConfidence,
    bool? isWhiteboard,
    String? whiteboardUrl,
    String? whiteboardData,
    int? whiteboardWidth,
    int? whiteboardHeight,
    bool? isCanvas,
    String? canvasUrl,
    String? canvasData,
    bool? isMindmap,
    String? mindmapUrl,
    String? mindmapData,
    bool? isFlowchart,
    String? flowchartUrl,
    String? flowchartData,
    bool? isTimeline,
    String? timelineUrl,
    String? timelineData,
    bool? isChart,
    String? chartType,
    String? chartData,
    String? chartConfig,
    bool? isDiagram,
    String? diagramType,
    String? diagramData,
    bool? isFormula,
    String? formula,
    String? formulaLatex,
    bool? formulaRendered,
    String? formulaImage,
    bool? isMentionAll,
    bool? isMentionHere,
    List<String>? mentionedUserIds,
    List<String>? mentionedGroupIds,
    bool? isSilent,
    bool? isImportant,
    bool? isUrgent,
    int? priority,
    String? priorityLabel,
    bool? isScheduled,
    DateTime? scheduledAt,
    bool? isDelayed,
    DateTime? delayedUntil,
    bool? isExpired,
    DateTime? expiresAt,
    bool? isEphemeral,
    int? ephemeralDuration,
    bool? isSelfDestruct,
    DateTime? selfDestructAt,
    bool? isBurned,
    DateTime? burnedAt,
    bool? isEncrypted,
    String? encryptionAlgorithm,
    String? encryptionKeyId,
    bool? isSigned,
    String? signature,
    String? signatureAlgorithm,
    String? signerId,
    DateTime? signedAt,
    bool? signatureVerified,
    bool? isVerified,
    String? verificationStatus,
    String? verifierId,
    DateTime? verifiedAt,
    bool? isApproved,
    String? approverId,
    DateTime? approvedAt,
    bool? isRejected,
    String? rejectReason,
    String? rejecterId,
    DateTime? rejectedAt,
    bool? isPending,
    DateTime? pendingSince,
    bool? isArchived2,
    DateTime? archivedAt,
    bool? isRestored,
    DateTime? restoredAt,
    String? restoredBy,
  }) => ChatMessage(
    id: id ?? this.id,
    conversationId: conversationId ?? this.conversationId,
    userId: userId ?? this.userId,
    role: role ?? this.role,
    content: content ?? this.content,
    text: text ?? this.text,
    parts: parts ?? this.parts,
    images: images ?? this.images,
    files: files ?? this.files,
    mentions: mentions ?? this.mentions,
    model: model ?? this.model,
    modelVersion: modelVersion ?? this.modelVersion,
    metadata: metadata ?? this.metadata,
    usage: usage ?? this.usage,
    promptTokens: promptTokens ?? this.promptTokens,
    completionTokens: completionTokens ?? this.completionTokens,
    totalTokens: totalTokens ?? this.totalTokens,
    cost: cost ?? this.cost,
    finishReason: finishReason ?? this.finishReason,
    isStreaming: isStreaming ?? this.isStreaming,
    isComplete: isComplete ?? this.isComplete,
    isError: isError ?? this.isError,
    error: error ?? this.error,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    completedAt: completedAt ?? this.completedAt,
    latencyMs: latencyMs ?? this.latencyMs,
    firstTokenMs: firstTokenMs ?? this.firstTokenMs,
    tokensPerSecond: tokensPerSecond ?? this.tokensPerSecond,
    isEdited: isEdited ?? this.isEdited,
    originalContent: originalContent ?? this.originalContent,
    editedAt: editedAt ?? this.editedAt,
    isDeleted: isDeleted ?? this.isDeleted,
    deletedAt: deletedAt ?? this.deletedAt,
    isPinned: isPinned ?? this.isPinned,
    isBookmarked: isBookmarked ?? this.isBookmarked,
    isStarred: isStarred ?? this.isStarred,
    isLiked: isLiked ?? this.isLiked,
    likeCount: likeCount ?? this.likeCount,
    reactions: reactions ?? this.reactions,
    reactionMap: reactionMap ?? this.reactionMap,
    isShared: isShared ?? this.isShared,
    shareLink: shareLink ?? this.shareLink,
    shareCount: shareCount ?? this.shareCount,
    viewCount: viewCount ?? this.viewCount,
    copyCount: copyCount ?? this.copyCount,
    isCopied: isCopied ?? this.isCopied,
    lastCopiedAt: lastCopiedAt ?? this.lastCopiedAt,
    isQuoted: isQuoted ?? this.isQuoted,
    quotedMessageId: quotedMessageId ?? this.quotedMessageId,
    quotedContent: quotedContent ?? this.quotedContent,
    isReply: isReply ?? this.isReply,
    replyToId: replyToId ?? this.replyToId,
    replyToContent: replyToContent ?? this.replyToContent,
    replyToUserId: replyToUserId ?? this.replyToUserId,
    isForwarded: isForwarded ?? this.isForwarded,
    forwardedFrom: forwardedFrom ?? this.forwardedFrom,
    isSystem: isSystem ?? this.isSystem,
    systemType: systemType ?? this.systemType,
    isHidden: isHidden ?? this.isHidden,
    isSpoiler: isSpoiler ?? this.isSpoiler,
    isNSFW: isNSFW ?? this.isNSFW,
    isFlagged: isFlagged ?? this.isFlagged,
    flagReason: flagReason ?? this.flagReason,
    isReviewed: isReviewed ?? this.isReviewed,
    reviewStatus: reviewStatus ?? this.reviewStatus,
    reviewerId: reviewerId ?? this.reviewerId,
    reviewedAt: reviewedAt ?? this.reviewedAt,
    isTranslated: isTranslated ?? this.isTranslated,
    translatedContent: translatedContent ?? this.translatedContent,
    sourceLanguage: sourceLanguage ?? this.sourceLanguage,
    targetLanguage: targetLanguage ?? this.targetLanguage,
    translationConfidence: translationConfidence ?? this.translationConfidence,
    isSummarized: isSummarized ?? this.isSummarized,
    summary: summary ?? this.summary,
    keyPoints: keyPoints ?? this.keyPoints,
    isAnalyzed: isAnalyzed ?? this.isAnalyzed,
    sentiment: sentiment ?? this.sentiment,
    sentimentScore: sentimentScore ?? this.sentimentScore,
    topics: topics ?? this.topics,
    entities: entities ?? this.entities,
    keywords: keywords ?? this.keywords,
    language: language ?? this.language,
    isCode: isCode ?? this.isCode,
    codeLanguage: codeLanguage ?? this.codeLanguage,
    codeContent: codeContent ?? this.codeContent,
    isCodeExecuted: isCodeExecuted ?? this.isCodeExecuted,
    codeOutput: codeOutput ?? this.codeOutput,
    codeExitCode: codeExitCode ?? this.codeExitCode,
    codeExecutionTimeMs: codeExecutionTimeMs ?? this.codeExecutionTimeMs,
    isTable: isTable ?? this.isTable,
    tableData: tableData ?? this.tableData,
    tableHeaders: tableHeaders ?? this.tableHeaders,
    isList: isList ?? this.isList,
    listItems: listItems ?? this.listItems,
    isOrdered: isOrdered ?? this.isOrdered,
    isQuote: isQuote ?? this.isQuote,
    quoteContent: quoteContent ?? this.quoteContent,
    quoteAuthor: quoteAuthor ?? this.quoteAuthor,
    isLink: isLink ?? this.isLink,
    linkUrl: linkUrl ?? this.linkUrl,
    linkTitle: linkTitle ?? this.linkTitle,
    linkDescription: linkDescription ?? this.linkDescription,
    linkImage: linkImage ?? this.linkImage,
    linkPreviewGenerated: linkPreviewGenerated ?? this.linkPreviewGenerated,
    isImage: isImage ?? this.isImage,
    imageUrl: imageUrl ?? this.imageUrl,
    imageWidth: imageWidth ?? this.imageWidth,
    imageHeight: imageHeight ?? this.imageHeight,
    imageFormat: imageFormat ?? this.imageFormat,
    imageSize: imageSize ?? this.imageSize,
    imageLoaded: imageLoaded ?? this.imageLoaded,
    imageFailed: imageFailed ?? this.imageFailed,
    imageError: imageError ?? this.imageError,
    isVideo: isVideo ?? this.isVideo,
    videoUrl: videoUrl ?? this.videoUrl,
    videoThumbnail: videoThumbnail ?? this.videoThumbnail,
    videoDuration: videoDuration ?? this.videoDuration,
    videoWidth: videoWidth ?? this.videoWidth,
    videoHeight: videoHeight ?? this.videoHeight,
    videoFormat: videoFormat ?? this.videoFormat,
    videoSize: videoSize ?? this.videoSize,
    videoPlayed: videoPlayed ?? this.videoPlayed,
    videoPlayCount: videoPlayCount ?? this.videoPlayCount,
    isAudio: isAudio ?? this.isAudio,
    audioUrl: audioUrl ?? this.audioUrl,
    audioTitle: audioTitle ?? this.audioTitle,
    audioArtist: audioArtist ?? this.audioArtist,
    audioDuration: audioDuration ?? this.audioDuration,
    audioFormat: audioFormat ?? this.audioFormat,
    audioSize: audioSize ?? this.audioSize,
    audioPlayed: audioPlayed ?? this.audioPlayed,
    audioPlayCount: audioPlayCount ?? this.audioPlayCount,
    isFile: isFile ?? this.isFile,
    fileName: fileName ?? this.fileName,
    fileSize: fileSize ?? this.fileSize,
    fileType: fileType ?? this.fileType,
    fileExtension: fileExtension ?? this.fileExtension,
    fileUrl: fileUrl ?? this.fileUrl,
    fileDownloaded: fileDownloaded ?? this.fileDownloaded,
    fileDownloadCount: fileDownloadCount ?? this.fileDownloadCount,
    filePreviewAvailable: filePreviewAvailable ?? this.filePreviewAvailable,
    filePreviewUrl: filePreviewUrl ?? this.filePreviewUrl,
    filePages: filePages ?? this.filePages,
    isLocation: isLocation ?? this.isLocation,
    latitude: latitude ?? this.latitude,
    longitude: longitude ?? this.longitude,
    address: address ?? this.address,
    placeName: placeName ?? this.placeName,
    placeId: placeId ?? this.placeId,
    isContact: isContact ?? this.isContact,
    contactName: contactName ?? this.contactName,
    contactPhone: contactPhone ?? this.contactPhone,
    contactEmail: contactEmail ?? this.contactEmail,
    contactAvatar: contactAvatar ?? this.contactAvatar,
    isPoll: isPoll ?? this.isPoll,
    pollQuestion: pollQuestion ?? this.pollQuestion,
    pollOptions: pollOptions ?? this.pollOptions,
    pollMultiple: pollMultiple ?? this.pollMultiple,
    pollAnonymous: pollAnonymous ?? this.pollAnonymous,
    pollEndsAt: pollEndsAt ?? this.pollEndsAt,
    pollTotalVotes: pollTotalVotes ?? this.pollTotalVotes,
    pollUserVotes: pollUserVotes ?? this.pollUserVotes,
    pollEnded: pollEnded ?? this.pollEnded,
    isEvent: isEvent ?? this.isEvent,
    eventTitle: eventTitle ?? this.eventTitle,
    eventDescription: eventDescription ?? this.eventDescription,
    eventStart: eventStart ?? this.eventStart,
    eventEnd: eventEnd ?? this.eventEnd,
    eventLocation: eventLocation ?? this.eventLocation,
    eventAllDay: eventAllDay ?? this.eventAllDay,
    eventTimezone: eventTimezone ?? this.eventTimezone,
    eventAttendeeCount: eventAttendeeCount ?? this.eventAttendeeCount,
    eventAttendees: eventAttendees ?? this.eventAttendees,
    eventStatus: eventStatus ?? this.eventStatus,
    isTask: isTask ?? this.isTask,
    taskTitle: taskTitle ?? this.taskTitle,
    taskDescription: taskDescription ?? this.taskDescription,
    taskCompleted: taskCompleted ?? this.taskCompleted,
    taskDueDate: taskDueDate ?? this.taskDueDate,
    taskPriority: taskPriority ?? this.taskPriority,
    taskAssignees: taskAssignees ?? this.taskAssignees,
    taskLabels: taskLabels ?? this.taskLabels,
    taskStatus: taskStatus ?? this.taskStatus,
    taskProject: taskProject ?? this.taskProject,
    taskSection: taskSection ?? this.taskSection,
    taskOrder: taskOrder ?? this.taskOrder,
    taskCompletedAt: taskCompletedAt ?? this.taskCompletedAt,
    taskCompletedBy: taskCompletedBy ?? this.taskCompletedBy,
    isSticker: isSticker ?? this.isSticker,
    stickerId: stickerId ?? this.stickerId,
    stickerUrl: stickerUrl ?? this.stickerUrl,
    stickerPack: stickerPack ?? this.stickerPack,
    isGif: isGif ?? this.isGif,
    gifUrl: gifUrl ?? this.gifUrl,
    gifPreview: gifPreview ?? this.gifPreview,
    gifWidth: gifWidth ?? this.gifWidth,
    gifHeight: gifHeight ?? this.gifHeight,
    isEmoji: isEmoji ?? this.isEmoji,
    emoji: emoji ?? this.emoji,
    emojiList: emojiList ?? this.emojiList,
    isVoice: isVoice ?? this.isVoice,
    voiceUrl: voiceUrl ?? this.voiceUrl,
    voiceDuration: voiceDuration ?? this.voiceDuration,
    voiceSize: voiceSize ?? this.voiceSize,
    voiceFormat: voiceFormat ?? this.voiceFormat,
    voicePlayed: voicePlayed ?? this.voicePlayed,
    voicePlaybackPosition: voicePlaybackPosition ?? this.voicePlaybackPosition,
    voiceTranscribed: voiceTranscribed ?? this.voiceTranscribed,
    voiceTranscript: voiceTranscript ?? this.voiceTranscript,
    voiceConfidence: voiceConfidence ?? this.voiceConfidence,
    isWhiteboard: isWhiteboard ?? this.isWhiteboard,
    whiteboardUrl: whiteboardUrl ?? this.whiteboardUrl,
    whiteboardData: whiteboardData ?? this.whiteboardData,
    whiteboardWidth: whiteboardWidth ?? this.whiteboardWidth,
    whiteboardHeight: whiteboardHeight ?? this.whiteboardHeight,
    isCanvas: isCanvas ?? this.isCanvas,
    canvasUrl: canvasUrl ?? this.canvasUrl,
    canvasData: canvasData ?? this.canvasData,
    isMindmap: isMindmap ?? this.isMindmap,
    mindmapUrl: mindmapUrl ?? this.mindmapUrl,
    mindmapData: mindmapData ?? this.mindmapData,
    isFlowchart: isFlowchart ?? this.isFlowchart,
    flowchartUrl: flowchartUrl ?? this.flowchartUrl,
    flowchartData: flowchartData ?? this.flowchartData,
    isTimeline: isTimeline ?? this.isTimeline,
    timelineUrl: timelineUrl ?? this.timelineUrl,
    timelineData: timelineData ?? this.timelineData,
    isChart: isChart ?? this.isChart,
    chartType: chartType ?? this.chartType,
    chartData: chartData ?? this.chartData,
    chartConfig: chartConfig ?? this.chartConfig,
    isDiagram: isDiagram ?? this.isDiagram,
    diagramType: diagramType ?? this.diagramType,
    diagramData: diagramData ?? this.diagramData,
    isFormula: isFormula ?? this.isFormula,
    formula: formula ?? this.formula,
    formulaLatex: formulaLatex ?? this.formulaLatex,
    formulaRendered: formulaRendered ?? this.formulaRendered,
    formulaImage: formulaImage ?? this.formulaImage,
    isMentionAll: isMentionAll ?? this.isMentionAll,
    isMentionHere: isMentionHere ?? this.isMentionHere,
    mentionedUserIds: mentionedUserIds ?? this.mentionedUserIds,
    mentionedGroupIds: mentionedGroupIds ?? this.mentionedGroupIds,
    isSilent: isSilent ?? this.isSilent,
    isImportant: isImportant ?? this.isImportant,
    isUrgent: isUrgent ?? this.isUrgent,
    priority: priority ?? this.priority,
    priorityLabel: priorityLabel ?? this.priorityLabel,
    isScheduled: isScheduled ?? this.isScheduled,
    scheduledAt: scheduledAt ?? this.scheduledAt,
    isDelayed: isDelayed ?? this.isDelayed,
    delayedUntil: delayedUntil ?? this.delayedUntil,
    isExpired: isExpired ?? this.isExpired,
    expiresAt: expiresAt ?? this.expiresAt,
    isEphemeral: isEphemeral ?? this.isEphemeral,
    ephemeralDuration: ephemeralDuration ?? this.ephemeralDuration,
    isSelfDestruct: isSelfDestruct ?? this.isSelfDestruct,
    selfDestructAt: selfDestructAt ?? this.selfDestructAt,
    isBurned: isBurned ?? this.isBurned,
    burnedAt: burnedAt ?? this.burnedAt,
    isEncrypted: isEncrypted ?? this.isEncrypted,
    encryptionAlgorithm: encryptionAlgorithm ?? this.encryptionAlgorithm,
    encryptionKeyId: encryptionKeyId ?? this.encryptionKeyId,
    isSigned: isSigned ?? this.isSigned,
    signature: signature ?? this.signature,
    signatureAlgorithm: signatureAlgorithm ?? this.signatureAlgorithm,
    signerId: signerId ?? this.signerId,
    signedAt: signedAt ?? this.signedAt,
    signatureVerified: signatureVerified ?? this.signatureVerified,
    isVerified: isVerified ?? this.isVerified,
    verificationStatus: verificationStatus ?? this.verificationStatus,
    verifierId: verifierId ?? this.verifierId,
    verifiedAt: verifiedAt ?? this.verifiedAt,
    isApproved: isApproved ?? this.isApproved,
    approverId: approverId ?? this.approverId,
    approvedAt: approvedAt ?? this.approvedAt,
    isRejected: isRejected ?? this.isRejected,
    rejectReason: rejectReason ?? this.rejectReason,
    rejecterId: rejecterId ?? this.rejecterId,
    rejectedAt: rejectedAt ?? this.rejectedAt,
    isPending: isPending ?? this.isPending,
    pendingSince: pendingSince ?? this.pendingSince,
    isArchived2: isArchived2 ?? this.isArchived2,
    archivedAt: archivedAt ?? this.archivedAt,
    isRestored: isRestored ?? this.isRestored,
    restoredAt: restoredAt ?? this.restoredAt,
    restoredBy: restoredBy ?? this.restoredBy,
  );

  ChatMessage merge(ChatMessage other) => copyWith(
    id: other.id,
    conversationId: other.conversationId,
    userId: other.userId,
    role: other.role,
    content: other.content,
    text: other.text,
    parts: other.parts,
    images: other.images,
    files: other.files,
    mentions: other.mentions,
    model: other.model,
    modelVersion: other.modelVersion,
    metadata: other.metadata,
    usage: other.usage,
    promptTokens: other.promptTokens,
    completionTokens: other.completionTokens,
    totalTokens: other.totalTokens,
    cost: other.cost,
    finishReason: other.finishReason,
    isStreaming: other.isStreaming,
    isComplete: other.isComplete,
    isError: other.isError,
    error: other.error,
    createdAt: other.createdAt,
    updatedAt: other.updatedAt,
    completedAt: other.completedAt,
    latencyMs: other.latencyMs,
    firstTokenMs: other.firstTokenMs,
    tokensPerSecond: other.tokensPerSecond,
    isEdited: other.isEdited,
    originalContent: other.originalContent,
    editedAt: other.editedAt,
    isDeleted: other.isDeleted,
    deletedAt: other.deletedAt,
    isPinned: other.isPinned,
    isBookmarked: other.isBookmarked,
    isStarred: other.isStarred,
    isLiked: other.isLiked,
    likeCount: other.likeCount,
    reactions: other.reactions,
    reactionMap: other.reactionMap,
    isShared: other.isShared,
    shareLink: other.shareLink,
    shareCount: other.shareCount,
    viewCount: other.viewCount,
    copyCount: other.copyCount,
    isCopied: other.isCopied,
    lastCopiedAt: other.lastCopiedAt,
    isQuoted: other.isQuoted,
    quotedMessageId: other.quotedMessageId,
    quotedContent: other.quotedContent,
    isReply: other.isReply,
    replyToId: other.replyToId,
    replyToContent: other.replyToContent,
    replyToUserId: other.replyToUserId,
    isForwarded: other.isForwarded,
    forwardedFrom: other.forwardedFrom,
    isSystem: other.isSystem,
    systemType: other.systemType,
    isHidden: other.isHidden,
    isSpoiler: other.isSpoiler,
    isNSFW: other.isNSFW,
    isFlagged: other.isFlagged,
    flagReason: other.flagReason,
    isReviewed: other.isReviewed,
    reviewStatus: other.reviewStatus,
    reviewerId: other.reviewerId,
    reviewedAt: other.reviewedAt,
    isTranslated: other.isTranslated,
    translatedContent: other.translatedContent,
    sourceLanguage: other.sourceLanguage,
    targetLanguage: other.targetLanguage,
    translationConfidence: other.translationConfidence,
    isSummarized: other.isSummarized,
    summary: other.summary,
    keyPoints: other.keyPoints,
    isAnalyzed: other.isAnalyzed,
    sentiment: other.sentiment,
    sentimentScore: other.sentimentScore,
    topics: other.topics,
    entities: other.entities,
    keywords: other.keywords,
    language: other.language,
    isCode: other.isCode,
    codeLanguage: other.codeLanguage,
    codeContent: other.codeContent,
    isCodeExecuted: other.isCodeExecuted,
    codeOutput: other.codeOutput,
    codeExitCode: other.codeExitCode,
    codeExecutionTimeMs: other.codeExecutionTimeMs,
    isTable: other.isTable,
    tableData: other.tableData,
    tableHeaders: other.tableHeaders,
    isList: other.isList,
    listItems: other.listItems,
    isOrdered: other.isOrdered,
    isQuote: other.isQuote,
    quoteContent: other.quoteContent,
    quoteAuthor: other.quoteAuthor,
    isLink: other.isLink,
    linkUrl: other.linkUrl,
    linkTitle: other.linkTitle,
    linkDescription: other.linkDescription,
    linkImage: other.linkImage,
    linkPreviewGenerated: other.linkPreviewGenerated,
    isImage: other.isImage,
    imageUrl: other.imageUrl,
    imageWidth: other.imageWidth,
    imageHeight: other.imageHeight,
    imageFormat: other.imageFormat,
    imageSize: other.imageSize,
    imageLoaded: other.imageLoaded,
    imageFailed: other.imageFailed,
    imageError: other.imageError,
    isVideo: other.isVideo,
    videoUrl: other.videoUrl,
    videoThumbnail: other.videoThumbnail,
    videoDuration: other.videoDuration,
    videoWidth: other.videoWidth,
    videoHeight: other.videoHeight,
    videoFormat: other.videoFormat,
    videoSize: other.videoSize,
    videoPlayed: other.videoPlayed,
    videoPlayCount: other.videoPlayCount,
    isAudio: other.isAudio,
    audioUrl: other.audioUrl,
    audioTitle: other.audioTitle,
    audioArtist: other.audioArtist,
    audioDuration: other.audioDuration,
    audioFormat: other.audioFormat,
    audioSize: other.audioSize,
    audioPlayed: other.audioPlayed,
    audioPlayCount: other.audioPlayCount,
    isFile: other.isFile,
    fileName: other.fileName,
    fileSize: other.fileSize,
    fileType: other.fileType,
    fileExtension: other.fileExtension,
    fileUrl: other.fileUrl,
    fileDownloaded: other.fileDownloaded,
    fileDownloadCount: other.fileDownloadCount,
    filePreviewAvailable: other.filePreviewAvailable,
    filePreviewUrl: other.filePreviewUrl,
    filePages: other.filePages,
    isLocation: other.isLocation,
    latitude: other.latitude,
    longitude: other.longitude,
    address: other.address,
    placeName: other.placeName,
    placeId: other.placeId,
    isContact: other.isContact,
    contactName: other.contactName,
    contactPhone: other.contactPhone,
    contactEmail: other.contactEmail,
    contactAvatar: other.contactAvatar,
    isPoll: other.isPoll,
    pollQuestion: other.pollQuestion,
    pollOptions: other.pollOptions,
    pollMultiple: other.pollMultiple,
    pollAnonymous: other.pollAnonymous,
    pollEndsAt: other.pollEndsAt,
    pollTotalVotes: other.pollTotalVotes,
    pollUserVotes: other.pollUserVotes,
    pollEnded: other.pollEnded,
    isEvent: other.isEvent,
    eventTitle: other.eventTitle,
    eventDescription: other.eventDescription,
    eventStart: other.eventStart,
    eventEnd: other.eventEnd,
    eventLocation: other.eventLocation,
    eventAllDay: other.eventAllDay,
    eventTimezone: other.eventTimezone,
    eventAttendeeCount: other.eventAttendeeCount,
    eventAttendees: other.eventAttendees,
    eventStatus: other.eventStatus,
    isTask: other.isTask,
    taskTitle: other.taskTitle,
    taskDescription: other.taskDescription,
    taskCompleted: other.taskCompleted,
    taskDueDate: other.taskDueDate,
    taskPriority: other.taskPriority,
    taskAssignees: other.taskAssignees,
    taskLabels: other.taskLabels,
    taskStatus: other.taskStatus,
    taskProject: other.taskProject,
    taskSection: other.taskSection,
    taskOrder: other.taskOrder,
    taskCompletedAt: other.taskCompletedAt,
    taskCompletedBy: other.taskCompletedBy,
    isSticker: other.isSticker,
    stickerId: other.stickerId,
    stickerUrl: other.stickerUrl,
    stickerPack: other.stickerPack,
    isGif: other.isGif,
    gifUrl: other.gifUrl,
    gifPreview: other.gifPreview,
    gifWidth: other.gifWidth,
    gifHeight: other.gifHeight,
    isEmoji: other.isEmoji,
    emoji: other.emoji,
    emojiList: other.emojiList,
    isVoice: other.isVoice,
    voiceUrl: other.voiceUrl,
    voiceDuration: other.voiceDuration,
    voiceSize: other.voiceSize,
    voiceFormat: other.voiceFormat,
    voicePlayed: other.voicePlayed,
    voicePlaybackPosition: other.voicePlaybackPosition,
    voiceTranscribed: other.voiceTranscribed,
    voiceTranscript: other.voiceTranscript,
    voiceConfidence: other.voiceConfidence,
    isWhiteboard: other.isWhiteboard,
    whiteboardUrl: other.whiteboardUrl,
    whiteboardData: other.whiteboardData,
    whiteboardWidth: other.whiteboardWidth,
    whiteboardHeight: other.whiteboardHeight,
    isCanvas: other.isCanvas,
    canvasUrl: other.canvasUrl,
    canvasData: other.canvasData,
    isMindmap: other.isMindmap,
    mindmapUrl: other.mindmapUrl,
    mindmapData: other.mindmapData,
    isFlowchart: other.isFlowchart,
    flowchartUrl: other.flowchartUrl,
    flowchartData: other.flowchartData,
    isTimeline: other.isTimeline,
    timelineUrl: other.timelineUrl,
    timelineData: other.timelineData,
    isChart: other.isChart,
    chartType: other.chartType,
    chartData: other.chartData,
    chartConfig: other.chartConfig,
    isDiagram: other.isDiagram,
    diagramType: other.diagramType,
    diagramData: other.diagramData,
    isFormula: other.isFormula,
    formula: other.formula,
    formulaLatex: other.formulaLatex,
    formulaRendered: other.formulaRendered,
    formulaImage: other.formulaImage,
    isMentionAll: other.isMentionAll,
    isMentionHere: other.isMentionHere,
    mentionedUserIds: other.mentionedUserIds,
    mentionedGroupIds: other.mentionedGroupIds,
    isSilent: other.isSilent,
    isImportant: other.isImportant,
    isUrgent: other.isUrgent,
    priority: other.priority,
    priorityLabel: other.priorityLabel,
    isScheduled: other.isScheduled,
    scheduledAt: other.scheduledAt,
    isDelayed: other.isDelayed,
    delayedUntil: other.delayedUntil,
    isExpired: other.isExpired,
    expiresAt: other.expiresAt,
    isEphemeral: other.isEphemeral,
    ephemeralDuration: other.ephemeralDuration,
    isSelfDestruct: other.isSelfDestruct,
    selfDestructAt: other.selfDestructAt,
    isBurned: other.isBurned,
    burnedAt: other.burnedAt,
    isEncrypted: other.isEncrypted,
    encryptionAlgorithm: other.encryptionAlgorithm,
    encryptionKeyId: other.encryptionKeyId,
    isSigned: other.isSigned,
    signature: other.signature,
    signatureAlgorithm: other.signatureAlgorithm,
    signerId: other.signerId,
    signedAt: other.signedAt,
    signatureVerified: other.signatureVerified,
    isVerified: other.isVerified,
    verificationStatus: other.verificationStatus,
    verifierId: other.verifierId,
    verifiedAt: other.verifiedAt,
    isApproved: other.isApproved,
    approverId: other.approverId,
    approvedAt: other.approvedAt,
    isRejected: other.isRejected,
    rejectReason: other.rejectReason,
    rejecterId: other.rejecterId,
    rejectedAt: other.rejectedAt,
    isPending: other.isPending,
    pendingSince: other.pendingSince,
    isArchived2: other.isArchived2,
    archivedAt: other.archivedAt,
    isRestored: other.isRestored,
    restoredAt: other.restoredAt,
    restoredBy: other.restoredBy,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'ChatMessage(id: $id)';

  ChatMessage clone() => ChatMessage.fromJson(toJson());

  bool get isEmpty => id.isEmpty;
  bool get isNotEmpty => id.isNotEmpty;

}
