import 'dart:convert';

/// Conversation 数据模型
class Conversation {
  String id;
  String title;
  String userId;
  String model;
  String systemPrompt;
  double temperature;
  int maxTokens;
  bool streaming;
  bool markdown;
  bool codeHighlight;
  bool autoTranslate;
  String targetLang;
  bool ttsEnabled;
  String ttsVoice;
  int messageCount;
  int tokenCount;
  int promptTokens;
  int completionTokens;
  double cost;
  String lastMessage;
  DateTime lastMessageAt;
  bool isPinned;
  bool isArchived;
  bool isMuted;
  bool isFavorite;
  String coverImage;
  String icon;
  String color;
  String category;
  List<String> tags;
  String agentId;
  bool agentEnabled;
  String knowledgeBaseId;
  bool knowledgeEnabled;
  bool webSearchEnabled;
  bool codeInterpreter;
  bool functionCalling;
  List<String> enabledTools;
  String mode;
  bool visionEnabled;
  bool audioEnabled;
  bool fileEnabled;
  int maxFileSize;
  int maxFiles;
  List<String> allowedFileTypes;
  DateTime createdAt;
  DateTime updatedAt;
  DateTime deletedAt;
  bool isDeleted;
  String deleteReason;
  bool autoDelete;
  int autoDeleteDays;
  DateTime autoDeleteAt;
  bool encrypted;
  String encryptionKey;
  bool shared;
  String shareLink;
  DateTime shareExpiresAt;
  int shareViewCount;
  bool allowCopy;
  bool allowExport;
  bool allowShare;
  bool allowEdit;
  bool allowDelete;
  String permission;
  List<String> sharedWith;
  List<String> editors;
  List<String viewers;
  String workspaceId;
  String folderId;
  int sortOrder;
  String status;
  String error;
  int retryCount;
  DateTime lastRetryAt;
  bool rateLimited;
  DateTime rateLimitResetAt;
  int requestsPerMinute;
  int requestsPerHour;
  int requestsPerDay;
  DateTime windowStart;
  bool quotaExceeded;
  String quotaType;
  DateTime quotaResetAt;
  int quotaLimit;
  int quotaUsed;
  double quotaPercent;
  bool notifyOnQuota;
  bool notifyOnError;
  bool notifyOnComplete;
  bool notifyOnMention;
  bool notifyOnReply;
  bool notifyOnReaction;
  bool notifyOnShare;
  bool notifyOnAssignment;
  bool notifyOnDueDate;
  bool notifyOnReminder;
  int unreadCount;
  DateTime lastReadAt;
  bool isRead;
  bool isMentioned;
  bool isReplied;
  bool isReacted;
  String draft;
  DateTime draftSavedAt;
  bool hasDraft;
  List<String> attachments;
  List<String> images;
  List<String> videos;
  List<String> audios;
  List<String> files;
  List<String> links;
  List<String> mentions;
  List<String> hashtags;
  List<String> emojis;
  String summary;
  List<String> keyPoints;
  List<String> actionItems;
  List<String> questions;
  List<String> answers;
  String sentiment;
  double sentimentScore;
  List<String> topics;
  List<String> entities;
  List<String> keywords;
  String language;
  double confidence;
  String modelVersion;
  String modelProvider;
  String modelEndpoint;
  int latencyMs;
  int firstTokenMs;
  int totalTimeMs;
  double tokensPerSecond;
  bool cached;
  String cacheKey;
  DateTime cachedAt;
  int cacheHits;
  int cacheMisses;
  double cacheHitRate;
  bool fallbackUsed;
  String fallbackModel;
  String fallbackReason;
  bool retryUsed;
  int retryAttempts;
  String retryReason;
  bool timeoutOccurred;
  int timeoutMs;
  bool rateLimitHit;
  int retryAfterMs;
  bool serverError;
  int statusCode;
  String errorCode;
  String errorMessage;
  String errorType;
  String errorDetail;
  String errorStack;
  DateTime errorAt;
  bool errorResolved;
  DateTime errorResolvedAt;
  String resolution;

  Conversation({
    required this.id, required this.title, required this.userId, required this.model, required this.systemPrompt, required this.temperature, required this.maxTokens, required this.streaming, required this.markdown, required this.codeHighlight, required this.autoTranslate, required this.targetLang, required this.ttsEnabled, required this.ttsVoice, required this.messageCount, required this.tokenCount, required this.promptTokens, required this.completionTokens, required this.cost, required this.lastMessage, required this.lastMessageAt, required this.isPinned, required this.isArchived, required this.isMuted, required this.isFavorite, required this.coverImage, required this.icon, required this.color, required this.category, required this.tags, required this.agentId, required this.agentEnabled, required this.knowledgeBaseId, required this.knowledgeEnabled, required this.webSearchEnabled, required this.codeInterpreter, required this.functionCalling, required this.enabledTools, required this.mode, required this.visionEnabled, required this.audioEnabled, required this.fileEnabled, required this.maxFileSize, required this.maxFiles, required this.allowedFileTypes, required this.createdAt, required this.updatedAt, required this.deletedAt, required this.isDeleted, required this.deleteReason, required this.autoDelete, required this.autoDeleteDays, required this.autoDeleteAt, required this.encrypted, required this.encryptionKey, required this.shared, required this.shareLink, required this.shareExpiresAt, required this.shareViewCount, required this.allowCopy, required this.allowExport, required this.allowShare, required this.allowEdit, required this.allowDelete, required this.permission, required this.sharedWith, required this.editors, required this.viewers, required this.workspaceId, required this.folderId, required this.sortOrder, required this.status, required this.error, required this.retryCount, required this.lastRetryAt, required this.rateLimited, required this.rateLimitResetAt, required this.requestsPerMinute, required this.requestsPerHour, required this.requestsPerDay, required this.windowStart, required this.quotaExceeded, required this.quotaType, required this.quotaResetAt, required this.quotaLimit, required this.quotaUsed, required this.quotaPercent, required this.notifyOnQuota, required this.notifyOnError, required this.notifyOnComplete, required this.notifyOnMention, required this.notifyOnReply, required this.notifyOnReaction, required this.notifyOnShare, required this.notifyOnAssignment, required this.notifyOnDueDate, required this.notifyOnReminder, required this.unreadCount, required this.lastReadAt, required this.isRead, required this.isMentioned, required this.isReplied, required this.isReacted, required this.draft, required this.draftSavedAt, required this.hasDraft, required this.attachments, required this.images, required this.videos, required this.audios, required this.files, required this.links, required this.mentions, required this.hashtags, required this.emojis, required this.summary, required this.keyPoints, required this.actionItems, required this.questions, required this.answers, required this.sentiment, required this.sentimentScore, required this.topics, required this.entities, required this.keywords, required this.language, required this.confidence, required this.modelVersion, required this.modelProvider, required this.modelEndpoint, required this.latencyMs, required this.firstTokenMs, required this.totalTimeMs, required this.tokensPerSecond, required this.cached, required this.cacheKey, required this.cachedAt, required this.cacheHits, required this.cacheMisses, required this.cacheHitRate, required this.fallbackUsed, required this.fallbackModel, required this.fallbackReason, required this.retryUsed, required this.retryAttempts, required this.retryReason, required this.timeoutOccurred, required this.timeoutMs, required this.rateLimitHit, required this.retryAfterMs, required this.serverError, required this.statusCode, required this.errorCode, required this.errorMessage, required this.errorType, required this.errorDetail, required this.errorStack, required this.errorAt, required this.errorResolved, required this.errorResolvedAt, required this.resolution,
  });

  factory Conversation.empty() => Conversation(
    id: '',
    title: '',
    userId: '',
    model: glm-4,
    systemPrompt: '',
    temperature: 0.7,
    maxTokens: 4096,
    streaming: true,
    markdown: true,
    codeHighlight: true,
    autoTranslate: false,
    targetLang: zh,
    ttsEnabled: false,
    ttsVoice: '',
    messageCount: 0,
    tokenCount: 0,
    promptTokens: 0,
    completionTokens: 0,
    cost: 0.0,
    lastMessage: '',
    lastMessageAt: DateTime.now(),
    isPinned: false,
    isArchived: false,
    isMuted: false,
    isFavorite: false,
    coverImage: '',
    icon: '',
    color: #FF6B9D,
    category: general,
    tags: [],
    agentId: '',
    agentEnabled: false,
    knowledgeBaseId: '',
    knowledgeEnabled: false,
    webSearchEnabled: false,
    codeInterpreter: false,
    functionCalling: true,
    enabledTools: [],
    mode: chat,
    visionEnabled: false,
    audioEnabled: false,
    fileEnabled: true,
    maxFileSize: 10485760,
    maxFiles: 10,
    allowedFileTypes: [],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    deletedAt: DateTime.now(),
    isDeleted: false,
    deleteReason: '',
    autoDelete: false,
    autoDeleteDays: 30,
    autoDeleteAt: DateTime.now(),
    encrypted: false,
    encryptionKey: '',
    shared: false,
    shareLink: '',
    shareExpiresAt: DateTime.now(),
    shareViewCount: 0,
    allowCopy: true,
    allowExport: true,
    allowShare: true,
    allowEdit: true,
    allowDelete: true,
    permission: private,
    sharedWith: [],
    editors: [],
    viewers: [],
    workspaceId: '',
    folderId: '',
    sortOrder: 0,
    status: active,
    error: '',
    retryCount: 0,
    lastRetryAt: DateTime.now(),
    rateLimited: false,
    rateLimitResetAt: DateTime.now(),
    requestsPerMinute: 0,
    requestsPerHour: 0,
    requestsPerDay: 0,
    windowStart: DateTime.now(),
    quotaExceeded: false,
    quotaType: '',
    quotaResetAt: DateTime.now(),
    quotaLimit: 0,
    quotaUsed: 0,
    quotaPercent: 0.0,
    notifyOnQuota: true,
    notifyOnError: true,
    notifyOnComplete: true,
    notifyOnMention: true,
    notifyOnReply: true,
    notifyOnReaction: true,
    notifyOnShare: true,
    notifyOnAssignment: true,
    notifyOnDueDate: true,
    notifyOnReminder: true,
    unreadCount: 0,
    lastReadAt: DateTime.now(),
    isRead: true,
    isMentioned: false,
    isReplied: false,
    isReacted: false,
    draft: '',
    draftSavedAt: DateTime.now(),
    hasDraft: false,
    attachments: [],
    images: [],
    videos: [],
    audios: [],
    files: [],
    links: [],
    mentions: [],
    hashtags: [],
    emojis: [],
    summary: '',
    keyPoints: [],
    actionItems: [],
    questions: [],
    answers: [],
    sentiment: neutral,
    sentimentScore: 0.0,
    topics: [],
    entities: [],
    keywords: [],
    language: zh,
    confidence: 0.0,
    modelVersion: '',
    modelProvider: '',
    modelEndpoint: '',
    latencyMs: 0,
    firstTokenMs: 0,
    totalTimeMs: 0,
    tokensPerSecond: 0.0,
    cached: false,
    cacheKey: '',
    cachedAt: DateTime.now(),
    cacheHits: 0,
    cacheMisses: 0,
    cacheHitRate: 0.0,
    fallbackUsed: false,
    fallbackModel: '',
    fallbackReason: '',
    retryUsed: false,
    retryAttempts: 0,
    retryReason: '',
    timeoutOccurred: false,
    timeoutMs: 0,
    rateLimitHit: false,
    retryAfterMs: 0,
    serverError: false,
    statusCode: 0,
    errorCode: '',
    errorMessage: '',
    errorType: '',
    errorDetail: '',
    errorStack: '',
    errorAt: DateTime.now(),
    errorResolved: false,
    errorResolvedAt: DateTime.now(),
    resolution: '',
  );

  factory Conversation.fromJson(Map<String, dynamic> json) => Conversation(
    id: json['id'] ?? '',
    title: json['title'] ?? '',
    userId: json['userId'] ?? '',
    model: json['model'] ?? '',
    systemPrompt: json['systemPrompt'] ?? '',
    temperature: (json['temperature'] ?? 0.0).toDouble(),
    maxTokens: json['maxTokens'] ?? 0,
    streaming: json['streaming'] ?? false,
    markdown: json['markdown'] ?? false,
    codeHighlight: json['codeHighlight'] ?? false,
    autoTranslate: json['autoTranslate'] ?? false,
    targetLang: json['targetLang'] ?? '',
    ttsEnabled: json['ttsEnabled'] ?? false,
    ttsVoice: json['ttsVoice'] ?? '',
    messageCount: json['messageCount'] ?? 0,
    tokenCount: json['tokenCount'] ?? 0,
    promptTokens: json['promptTokens'] ?? 0,
    completionTokens: json['completionTokens'] ?? 0,
    cost: (json['cost'] ?? 0.0).toDouble(),
    lastMessage: json['lastMessage'] ?? '',
    lastMessageAt: json['lastMessageAt'] != null ? DateTime.parse(json['lastMessageAt']) : DateTime.now(),
    isPinned: json['isPinned'] ?? false,
    isArchived: json['isArchived'] ?? false,
    isMuted: json['isMuted'] ?? false,
    isFavorite: json['isFavorite'] ?? false,
    coverImage: json['coverImage'] ?? '',
    icon: json['icon'] ?? '',
    color: json['color'] ?? '',
    category: json['category'] ?? '',
    tags: json['tags'] != null ? List<String>.from(json['tags']) : [],
    agentId: json['agentId'] ?? '',
    agentEnabled: json['agentEnabled'] ?? false,
    knowledgeBaseId: json['knowledgeBaseId'] ?? '',
    knowledgeEnabled: json['knowledgeEnabled'] ?? false,
    webSearchEnabled: json['webSearchEnabled'] ?? false,
    codeInterpreter: json['codeInterpreter'] ?? false,
    functionCalling: json['functionCalling'] ?? false,
    enabledTools: json['enabledTools'] != null ? List<String>.from(json['enabledTools']) : [],
    mode: json['mode'] ?? '',
    visionEnabled: json['visionEnabled'] ?? false,
    audioEnabled: json['audioEnabled'] ?? false,
    fileEnabled: json['fileEnabled'] ?? false,
    maxFileSize: json['maxFileSize'] ?? 0,
    maxFiles: json['maxFiles'] ?? 0,
    allowedFileTypes: json['allowedFileTypes'] != null ? List<String>.from(json['allowedFileTypes']) : [],
    createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : DateTime.now(),
    updatedAt: json['updatedAt'] != null ? DateTime.parse(json['updatedAt']) : DateTime.now(),
    deletedAt: json['deletedAt'] != null ? DateTime.parse(json['deletedAt']) : DateTime.now(),
    isDeleted: json['isDeleted'] ?? false,
    deleteReason: json['deleteReason'] ?? '',
    autoDelete: json['autoDelete'] ?? false,
    autoDeleteDays: json['autoDeleteDays'] ?? 0,
    autoDeleteAt: json['autoDeleteAt'] != null ? DateTime.parse(json['autoDeleteAt']) : DateTime.now(),
    encrypted: json['encrypted'] ?? false,
    encryptionKey: json['encryptionKey'] ?? '',
    shared: json['shared'] ?? false,
    shareLink: json['shareLink'] ?? '',
    shareExpiresAt: json['shareExpiresAt'] != null ? DateTime.parse(json['shareExpiresAt']) : DateTime.now(),
    shareViewCount: json['shareViewCount'] ?? 0,
    allowCopy: json['allowCopy'] ?? false,
    allowExport: json['allowExport'] ?? false,
    allowShare: json['allowShare'] ?? false,
    allowEdit: json['allowEdit'] ?? false,
    allowDelete: json['allowDelete'] ?? false,
    permission: json['permission'] ?? '',
    sharedWith: json['sharedWith'] != null ? List<String>.from(json['sharedWith']) : [],
    editors: json['editors'] != null ? List<String>.from(json['editors']) : [],
    viewers: json['viewers'] != null ? List<String>.from(json['viewers']) : [],
    workspaceId: json['workspaceId'] ?? '',
    folderId: json['folderId'] ?? '',
    sortOrder: json['sortOrder'] ?? 0,
    status: json['status'] ?? '',
    error: json['error'] ?? '',
    retryCount: json['retryCount'] ?? 0,
    lastRetryAt: json['lastRetryAt'] != null ? DateTime.parse(json['lastRetryAt']) : DateTime.now(),
    rateLimited: json['rateLimited'] ?? false,
    rateLimitResetAt: json['rateLimitResetAt'] != null ? DateTime.parse(json['rateLimitResetAt']) : DateTime.now(),
    requestsPerMinute: json['requestsPerMinute'] ?? 0,
    requestsPerHour: json['requestsPerHour'] ?? 0,
    requestsPerDay: json['requestsPerDay'] ?? 0,
    windowStart: json['windowStart'] != null ? DateTime.parse(json['windowStart']) : DateTime.now(),
    quotaExceeded: json['quotaExceeded'] ?? false,
    quotaType: json['quotaType'] ?? '',
    quotaResetAt: json['quotaResetAt'] != null ? DateTime.parse(json['quotaResetAt']) : DateTime.now(),
    quotaLimit: json['quotaLimit'] ?? 0,
    quotaUsed: json['quotaUsed'] ?? 0,
    quotaPercent: (json['quotaPercent'] ?? 0.0).toDouble(),
    notifyOnQuota: json['notifyOnQuota'] ?? false,
    notifyOnError: json['notifyOnError'] ?? false,
    notifyOnComplete: json['notifyOnComplete'] ?? false,
    notifyOnMention: json['notifyOnMention'] ?? false,
    notifyOnReply: json['notifyOnReply'] ?? false,
    notifyOnReaction: json['notifyOnReaction'] ?? false,
    notifyOnShare: json['notifyOnShare'] ?? false,
    notifyOnAssignment: json['notifyOnAssignment'] ?? false,
    notifyOnDueDate: json['notifyOnDueDate'] ?? false,
    notifyOnReminder: json['notifyOnReminder'] ?? false,
    unreadCount: json['unreadCount'] ?? 0,
    lastReadAt: json['lastReadAt'] != null ? DateTime.parse(json['lastReadAt']) : DateTime.now(),
    isRead: json['isRead'] ?? false,
    isMentioned: json['isMentioned'] ?? false,
    isReplied: json['isReplied'] ?? false,
    isReacted: json['isReacted'] ?? false,
    draft: json['draft'] ?? '',
    draftSavedAt: json['draftSavedAt'] != null ? DateTime.parse(json['draftSavedAt']) : DateTime.now(),
    hasDraft: json['hasDraft'] ?? false,
    attachments: json['attachments'] != null ? List<String>.from(json['attachments']) : [],
    images: json['images'] != null ? List<String>.from(json['images']) : [],
    videos: json['videos'] != null ? List<String>.from(json['videos']) : [],
    audios: json['audios'] != null ? List<String>.from(json['audios']) : [],
    files: json['files'] != null ? List<String>.from(json['files']) : [],
    links: json['links'] != null ? List<String>.from(json['links']) : [],
    mentions: json['mentions'] != null ? List<String>.from(json['mentions']) : [],
    hashtags: json['hashtags'] != null ? List<String>.from(json['hashtags']) : [],
    emojis: json['emojis'] != null ? List<String>.from(json['emojis']) : [],
    summary: json['summary'] ?? '',
    keyPoints: json['keyPoints'] != null ? List<String>.from(json['keyPoints']) : [],
    actionItems: json['actionItems'] != null ? List<String>.from(json['actionItems']) : [],
    questions: json['questions'] != null ? List<String>.from(json['questions']) : [],
    answers: json['answers'] != null ? List<String>.from(json['answers']) : [],
    sentiment: json['sentiment'] ?? '',
    sentimentScore: (json['sentimentScore'] ?? 0.0).toDouble(),
    topics: json['topics'] != null ? List<String>.from(json['topics']) : [],
    entities: json['entities'] != null ? List<String>.from(json['entities']) : [],
    keywords: json['keywords'] != null ? List<String>.from(json['keywords']) : [],
    language: json['language'] ?? '',
    confidence: (json['confidence'] ?? 0.0).toDouble(),
    modelVersion: json['modelVersion'] ?? '',
    modelProvider: json['modelProvider'] ?? '',
    modelEndpoint: json['modelEndpoint'] ?? '',
    latencyMs: json['latencyMs'] ?? 0,
    firstTokenMs: json['firstTokenMs'] ?? 0,
    totalTimeMs: json['totalTimeMs'] ?? 0,
    tokensPerSecond: (json['tokensPerSecond'] ?? 0.0).toDouble(),
    cached: json['cached'] ?? false,
    cacheKey: json['cacheKey'] ?? '',
    cachedAt: json['cachedAt'] != null ? DateTime.parse(json['cachedAt']) : DateTime.now(),
    cacheHits: json['cacheHits'] ?? 0,
    cacheMisses: json['cacheMisses'] ?? 0,
    cacheHitRate: (json['cacheHitRate'] ?? 0.0).toDouble(),
    fallbackUsed: json['fallbackUsed'] ?? false,
    fallbackModel: json['fallbackModel'] ?? '',
    fallbackReason: json['fallbackReason'] ?? '',
    retryUsed: json['retryUsed'] ?? false,
    retryAttempts: json['retryAttempts'] ?? 0,
    retryReason: json['retryReason'] ?? '',
    timeoutOccurred: json['timeoutOccurred'] ?? false,
    timeoutMs: json['timeoutMs'] ?? 0,
    rateLimitHit: json['rateLimitHit'] ?? false,
    retryAfterMs: json['retryAfterMs'] ?? 0,
    serverError: json['serverError'] ?? false,
    statusCode: json['statusCode'] ?? 0,
    errorCode: json['errorCode'] ?? '',
    errorMessage: json['errorMessage'] ?? '',
    errorType: json['errorType'] ?? '',
    errorDetail: json['errorDetail'] ?? '',
    errorStack: json['errorStack'] ?? '',
    errorAt: json['errorAt'] != null ? DateTime.parse(json['errorAt']) : DateTime.now(),
    errorResolved: json['errorResolved'] ?? false,
    errorResolvedAt: json['errorResolvedAt'] != null ? DateTime.parse(json['errorResolvedAt']) : DateTime.now(),
    resolution: json['resolution'] ?? '',
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'userId': userId,
    'model': model,
    'systemPrompt': systemPrompt,
    'temperature': temperature,
    'maxTokens': maxTokens,
    'streaming': streaming,
    'markdown': markdown,
    'codeHighlight': codeHighlight,
    'autoTranslate': autoTranslate,
    'targetLang': targetLang,
    'ttsEnabled': ttsEnabled,
    'ttsVoice': ttsVoice,
    'messageCount': messageCount,
    'tokenCount': tokenCount,
    'promptTokens': promptTokens,
    'completionTokens': completionTokens,
    'cost': cost,
    'lastMessage': lastMessage,
    'lastMessageAt': lastMessageAt.toIso8601String(),
    'isPinned': isPinned,
    'isArchived': isArchived,
    'isMuted': isMuted,
    'isFavorite': isFavorite,
    'coverImage': coverImage,
    'icon': icon,
    'color': color,
    'category': category,
    'tags': tags,
    'agentId': agentId,
    'agentEnabled': agentEnabled,
    'knowledgeBaseId': knowledgeBaseId,
    'knowledgeEnabled': knowledgeEnabled,
    'webSearchEnabled': webSearchEnabled,
    'codeInterpreter': codeInterpreter,
    'functionCalling': functionCalling,
    'enabledTools': enabledTools,
    'mode': mode,
    'visionEnabled': visionEnabled,
    'audioEnabled': audioEnabled,
    'fileEnabled': fileEnabled,
    'maxFileSize': maxFileSize,
    'maxFiles': maxFiles,
    'allowedFileTypes': allowedFileTypes,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'deletedAt': deletedAt.toIso8601String(),
    'isDeleted': isDeleted,
    'deleteReason': deleteReason,
    'autoDelete': autoDelete,
    'autoDeleteDays': autoDeleteDays,
    'autoDeleteAt': autoDeleteAt.toIso8601String(),
    'encrypted': encrypted,
    'encryptionKey': encryptionKey,
    'shared': shared,
    'shareLink': shareLink,
    'shareExpiresAt': shareExpiresAt.toIso8601String(),
    'shareViewCount': shareViewCount,
    'allowCopy': allowCopy,
    'allowExport': allowExport,
    'allowShare': allowShare,
    'allowEdit': allowEdit,
    'allowDelete': allowDelete,
    'permission': permission,
    'sharedWith': sharedWith,
    'editors': editors,
    'viewers': viewers,
    'workspaceId': workspaceId,
    'folderId': folderId,
    'sortOrder': sortOrder,
    'status': status,
    'error': error,
    'retryCount': retryCount,
    'lastRetryAt': lastRetryAt.toIso8601String(),
    'rateLimited': rateLimited,
    'rateLimitResetAt': rateLimitResetAt.toIso8601String(),
    'requestsPerMinute': requestsPerMinute,
    'requestsPerHour': requestsPerHour,
    'requestsPerDay': requestsPerDay,
    'windowStart': windowStart.toIso8601String(),
    'quotaExceeded': quotaExceeded,
    'quotaType': quotaType,
    'quotaResetAt': quotaResetAt.toIso8601String(),
    'quotaLimit': quotaLimit,
    'quotaUsed': quotaUsed,
    'quotaPercent': quotaPercent,
    'notifyOnQuota': notifyOnQuota,
    'notifyOnError': notifyOnError,
    'notifyOnComplete': notifyOnComplete,
    'notifyOnMention': notifyOnMention,
    'notifyOnReply': notifyOnReply,
    'notifyOnReaction': notifyOnReaction,
    'notifyOnShare': notifyOnShare,
    'notifyOnAssignment': notifyOnAssignment,
    'notifyOnDueDate': notifyOnDueDate,
    'notifyOnReminder': notifyOnReminder,
    'unreadCount': unreadCount,
    'lastReadAt': lastReadAt.toIso8601String(),
    'isRead': isRead,
    'isMentioned': isMentioned,
    'isReplied': isReplied,
    'isReacted': isReacted,
    'draft': draft,
    'draftSavedAt': draftSavedAt.toIso8601String(),
    'hasDraft': hasDraft,
    'attachments': attachments,
    'images': images,
    'videos': videos,
    'audios': audios,
    'files': files,
    'links': links,
    'mentions': mentions,
    'hashtags': hashtags,
    'emojis': emojis,
    'summary': summary,
    'keyPoints': keyPoints,
    'actionItems': actionItems,
    'questions': questions,
    'answers': answers,
    'sentiment': sentiment,
    'sentimentScore': sentimentScore,
    'topics': topics,
    'entities': entities,
    'keywords': keywords,
    'language': language,
    'confidence': confidence,
    'modelVersion': modelVersion,
    'modelProvider': modelProvider,
    'modelEndpoint': modelEndpoint,
    'latencyMs': latencyMs,
    'firstTokenMs': firstTokenMs,
    'totalTimeMs': totalTimeMs,
    'tokensPerSecond': tokensPerSecond,
    'cached': cached,
    'cacheKey': cacheKey,
    'cachedAt': cachedAt.toIso8601String(),
    'cacheHits': cacheHits,
    'cacheMisses': cacheMisses,
    'cacheHitRate': cacheHitRate,
    'fallbackUsed': fallbackUsed,
    'fallbackModel': fallbackModel,
    'fallbackReason': fallbackReason,
    'retryUsed': retryUsed,
    'retryAttempts': retryAttempts,
    'retryReason': retryReason,
    'timeoutOccurred': timeoutOccurred,
    'timeoutMs': timeoutMs,
    'rateLimitHit': rateLimitHit,
    'retryAfterMs': retryAfterMs,
    'serverError': serverError,
    'statusCode': statusCode,
    'errorCode': errorCode,
    'errorMessage': errorMessage,
    'errorType': errorType,
    'errorDetail': errorDetail,
    'errorStack': errorStack,
    'errorAt': errorAt.toIso8601String(),
    'errorResolved': errorResolved,
    'errorResolvedAt': errorResolvedAt.toIso8601String(),
    'resolution': resolution,
  };

  Conversation copyWith({
    String? id,
    String? title,
    String? userId,
    String? model,
    String? systemPrompt,
    double? temperature,
    int? maxTokens,
    bool? streaming,
    bool? markdown,
    bool? codeHighlight,
    bool? autoTranslate,
    String? targetLang,
    bool? ttsEnabled,
    String? ttsVoice,
    int? messageCount,
    int? tokenCount,
    int? promptTokens,
    int? completionTokens,
    double? cost,
    String? lastMessage,
    DateTime? lastMessageAt,
    bool? isPinned,
    bool? isArchived,
    bool? isMuted,
    bool? isFavorite,
    String? coverImage,
    String? icon,
    String? color,
    String? category,
    List<String>? tags,
    String? agentId,
    bool? agentEnabled,
    String? knowledgeBaseId,
    bool? knowledgeEnabled,
    bool? webSearchEnabled,
    bool? codeInterpreter,
    bool? functionCalling,
    List<String>? enabledTools,
    String? mode,
    bool? visionEnabled,
    bool? audioEnabled,
    bool? fileEnabled,
    int? maxFileSize,
    int? maxFiles,
    List<String>? allowedFileTypes,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? deletedAt,
    bool? isDeleted,
    String? deleteReason,
    bool? autoDelete,
    int? autoDeleteDays,
    DateTime? autoDeleteAt,
    bool? encrypted,
    String? encryptionKey,
    bool? shared,
    String? shareLink,
    DateTime? shareExpiresAt,
    int? shareViewCount,
    bool? allowCopy,
    bool? allowExport,
    bool? allowShare,
    bool? allowEdit,
    bool? allowDelete,
    String? permission,
    List<String>? sharedWith,
    List<String>? editors,
    List<String? viewers,
    String? workspaceId,
    String? folderId,
    int? sortOrder,
    String? status,
    String? error,
    int? retryCount,
    DateTime? lastRetryAt,
    bool? rateLimited,
    DateTime? rateLimitResetAt,
    int? requestsPerMinute,
    int? requestsPerHour,
    int? requestsPerDay,
    DateTime? windowStart,
    bool? quotaExceeded,
    String? quotaType,
    DateTime? quotaResetAt,
    int? quotaLimit,
    int? quotaUsed,
    double? quotaPercent,
    bool? notifyOnQuota,
    bool? notifyOnError,
    bool? notifyOnComplete,
    bool? notifyOnMention,
    bool? notifyOnReply,
    bool? notifyOnReaction,
    bool? notifyOnShare,
    bool? notifyOnAssignment,
    bool? notifyOnDueDate,
    bool? notifyOnReminder,
    int? unreadCount,
    DateTime? lastReadAt,
    bool? isRead,
    bool? isMentioned,
    bool? isReplied,
    bool? isReacted,
    String? draft,
    DateTime? draftSavedAt,
    bool? hasDraft,
    List<String>? attachments,
    List<String>? images,
    List<String>? videos,
    List<String>? audios,
    List<String>? files,
    List<String>? links,
    List<String>? mentions,
    List<String>? hashtags,
    List<String>? emojis,
    String? summary,
    List<String>? keyPoints,
    List<String>? actionItems,
    List<String>? questions,
    List<String>? answers,
    String? sentiment,
    double? sentimentScore,
    List<String>? topics,
    List<String>? entities,
    List<String>? keywords,
    String? language,
    double? confidence,
    String? modelVersion,
    String? modelProvider,
    String? modelEndpoint,
    int? latencyMs,
    int? firstTokenMs,
    int? totalTimeMs,
    double? tokensPerSecond,
    bool? cached,
    String? cacheKey,
    DateTime? cachedAt,
    int? cacheHits,
    int? cacheMisses,
    double? cacheHitRate,
    bool? fallbackUsed,
    String? fallbackModel,
    String? fallbackReason,
    bool? retryUsed,
    int? retryAttempts,
    String? retryReason,
    bool? timeoutOccurred,
    int? timeoutMs,
    bool? rateLimitHit,
    int? retryAfterMs,
    bool? serverError,
    int? statusCode,
    String? errorCode,
    String? errorMessage,
    String? errorType,
    String? errorDetail,
    String? errorStack,
    DateTime? errorAt,
    bool? errorResolved,
    DateTime? errorResolvedAt,
    String? resolution,
  }) => Conversation(
    id: id ?? this.id,
    title: title ?? this.title,
    userId: userId ?? this.userId,
    model: model ?? this.model,
    systemPrompt: systemPrompt ?? this.systemPrompt,
    temperature: temperature ?? this.temperature,
    maxTokens: maxTokens ?? this.maxTokens,
    streaming: streaming ?? this.streaming,
    markdown: markdown ?? this.markdown,
    codeHighlight: codeHighlight ?? this.codeHighlight,
    autoTranslate: autoTranslate ?? this.autoTranslate,
    targetLang: targetLang ?? this.targetLang,
    ttsEnabled: ttsEnabled ?? this.ttsEnabled,
    ttsVoice: ttsVoice ?? this.ttsVoice,
    messageCount: messageCount ?? this.messageCount,
    tokenCount: tokenCount ?? this.tokenCount,
    promptTokens: promptTokens ?? this.promptTokens,
    completionTokens: completionTokens ?? this.completionTokens,
    cost: cost ?? this.cost,
    lastMessage: lastMessage ?? this.lastMessage,
    lastMessageAt: lastMessageAt ?? this.lastMessageAt,
    isPinned: isPinned ?? this.isPinned,
    isArchived: isArchived ?? this.isArchived,
    isMuted: isMuted ?? this.isMuted,
    isFavorite: isFavorite ?? this.isFavorite,
    coverImage: coverImage ?? this.coverImage,
    icon: icon ?? this.icon,
    color: color ?? this.color,
    category: category ?? this.category,
    tags: tags ?? this.tags,
    agentId: agentId ?? this.agentId,
    agentEnabled: agentEnabled ?? this.agentEnabled,
    knowledgeBaseId: knowledgeBaseId ?? this.knowledgeBaseId,
    knowledgeEnabled: knowledgeEnabled ?? this.knowledgeEnabled,
    webSearchEnabled: webSearchEnabled ?? this.webSearchEnabled,
    codeInterpreter: codeInterpreter ?? this.codeInterpreter,
    functionCalling: functionCalling ?? this.functionCalling,
    enabledTools: enabledTools ?? this.enabledTools,
    mode: mode ?? this.mode,
    visionEnabled: visionEnabled ?? this.visionEnabled,
    audioEnabled: audioEnabled ?? this.audioEnabled,
    fileEnabled: fileEnabled ?? this.fileEnabled,
    maxFileSize: maxFileSize ?? this.maxFileSize,
    maxFiles: maxFiles ?? this.maxFiles,
    allowedFileTypes: allowedFileTypes ?? this.allowedFileTypes,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    deletedAt: deletedAt ?? this.deletedAt,
    isDeleted: isDeleted ?? this.isDeleted,
    deleteReason: deleteReason ?? this.deleteReason,
    autoDelete: autoDelete ?? this.autoDelete,
    autoDeleteDays: autoDeleteDays ?? this.autoDeleteDays,
    autoDeleteAt: autoDeleteAt ?? this.autoDeleteAt,
    encrypted: encrypted ?? this.encrypted,
    encryptionKey: encryptionKey ?? this.encryptionKey,
    shared: shared ?? this.shared,
    shareLink: shareLink ?? this.shareLink,
    shareExpiresAt: shareExpiresAt ?? this.shareExpiresAt,
    shareViewCount: shareViewCount ?? this.shareViewCount,
    allowCopy: allowCopy ?? this.allowCopy,
    allowExport: allowExport ?? this.allowExport,
    allowShare: allowShare ?? this.allowShare,
    allowEdit: allowEdit ?? this.allowEdit,
    allowDelete: allowDelete ?? this.allowDelete,
    permission: permission ?? this.permission,
    sharedWith: sharedWith ?? this.sharedWith,
    editors: editors ?? this.editors,
    viewers: viewers ?? this.viewers,
    workspaceId: workspaceId ?? this.workspaceId,
    folderId: folderId ?? this.folderId,
    sortOrder: sortOrder ?? this.sortOrder,
    status: status ?? this.status,
    error: error ?? this.error,
    retryCount: retryCount ?? this.retryCount,
    lastRetryAt: lastRetryAt ?? this.lastRetryAt,
    rateLimited: rateLimited ?? this.rateLimited,
    rateLimitResetAt: rateLimitResetAt ?? this.rateLimitResetAt,
    requestsPerMinute: requestsPerMinute ?? this.requestsPerMinute,
    requestsPerHour: requestsPerHour ?? this.requestsPerHour,
    requestsPerDay: requestsPerDay ?? this.requestsPerDay,
    windowStart: windowStart ?? this.windowStart,
    quotaExceeded: quotaExceeded ?? this.quotaExceeded,
    quotaType: quotaType ?? this.quotaType,
    quotaResetAt: quotaResetAt ?? this.quotaResetAt,
    quotaLimit: quotaLimit ?? this.quotaLimit,
    quotaUsed: quotaUsed ?? this.quotaUsed,
    quotaPercent: quotaPercent ?? this.quotaPercent,
    notifyOnQuota: notifyOnQuota ?? this.notifyOnQuota,
    notifyOnError: notifyOnError ?? this.notifyOnError,
    notifyOnComplete: notifyOnComplete ?? this.notifyOnComplete,
    notifyOnMention: notifyOnMention ?? this.notifyOnMention,
    notifyOnReply: notifyOnReply ?? this.notifyOnReply,
    notifyOnReaction: notifyOnReaction ?? this.notifyOnReaction,
    notifyOnShare: notifyOnShare ?? this.notifyOnShare,
    notifyOnAssignment: notifyOnAssignment ?? this.notifyOnAssignment,
    notifyOnDueDate: notifyOnDueDate ?? this.notifyOnDueDate,
    notifyOnReminder: notifyOnReminder ?? this.notifyOnReminder,
    unreadCount: unreadCount ?? this.unreadCount,
    lastReadAt: lastReadAt ?? this.lastReadAt,
    isRead: isRead ?? this.isRead,
    isMentioned: isMentioned ?? this.isMentioned,
    isReplied: isReplied ?? this.isReplied,
    isReacted: isReacted ?? this.isReacted,
    draft: draft ?? this.draft,
    draftSavedAt: draftSavedAt ?? this.draftSavedAt,
    hasDraft: hasDraft ?? this.hasDraft,
    attachments: attachments ?? this.attachments,
    images: images ?? this.images,
    videos: videos ?? this.videos,
    audios: audios ?? this.audios,
    files: files ?? this.files,
    links: links ?? this.links,
    mentions: mentions ?? this.mentions,
    hashtags: hashtags ?? this.hashtags,
    emojis: emojis ?? this.emojis,
    summary: summary ?? this.summary,
    keyPoints: keyPoints ?? this.keyPoints,
    actionItems: actionItems ?? this.actionItems,
    questions: questions ?? this.questions,
    answers: answers ?? this.answers,
    sentiment: sentiment ?? this.sentiment,
    sentimentScore: sentimentScore ?? this.sentimentScore,
    topics: topics ?? this.topics,
    entities: entities ?? this.entities,
    keywords: keywords ?? this.keywords,
    language: language ?? this.language,
    confidence: confidence ?? this.confidence,
    modelVersion: modelVersion ?? this.modelVersion,
    modelProvider: modelProvider ?? this.modelProvider,
    modelEndpoint: modelEndpoint ?? this.modelEndpoint,
    latencyMs: latencyMs ?? this.latencyMs,
    firstTokenMs: firstTokenMs ?? this.firstTokenMs,
    totalTimeMs: totalTimeMs ?? this.totalTimeMs,
    tokensPerSecond: tokensPerSecond ?? this.tokensPerSecond,
    cached: cached ?? this.cached,
    cacheKey: cacheKey ?? this.cacheKey,
    cachedAt: cachedAt ?? this.cachedAt,
    cacheHits: cacheHits ?? this.cacheHits,
    cacheMisses: cacheMisses ?? this.cacheMisses,
    cacheHitRate: cacheHitRate ?? this.cacheHitRate,
    fallbackUsed: fallbackUsed ?? this.fallbackUsed,
    fallbackModel: fallbackModel ?? this.fallbackModel,
    fallbackReason: fallbackReason ?? this.fallbackReason,
    retryUsed: retryUsed ?? this.retryUsed,
    retryAttempts: retryAttempts ?? this.retryAttempts,
    retryReason: retryReason ?? this.retryReason,
    timeoutOccurred: timeoutOccurred ?? this.timeoutOccurred,
    timeoutMs: timeoutMs ?? this.timeoutMs,
    rateLimitHit: rateLimitHit ?? this.rateLimitHit,
    retryAfterMs: retryAfterMs ?? this.retryAfterMs,
    serverError: serverError ?? this.serverError,
    statusCode: statusCode ?? this.statusCode,
    errorCode: errorCode ?? this.errorCode,
    errorMessage: errorMessage ?? this.errorMessage,
    errorType: errorType ?? this.errorType,
    errorDetail: errorDetail ?? this.errorDetail,
    errorStack: errorStack ?? this.errorStack,
    errorAt: errorAt ?? this.errorAt,
    errorResolved: errorResolved ?? this.errorResolved,
    errorResolvedAt: errorResolvedAt ?? this.errorResolvedAt,
    resolution: resolution ?? this.resolution,
  );

  Conversation merge(Conversation other) => copyWith(
    id: other.id,
    title: other.title,
    userId: other.userId,
    model: other.model,
    systemPrompt: other.systemPrompt,
    temperature: other.temperature,
    maxTokens: other.maxTokens,
    streaming: other.streaming,
    markdown: other.markdown,
    codeHighlight: other.codeHighlight,
    autoTranslate: other.autoTranslate,
    targetLang: other.targetLang,
    ttsEnabled: other.ttsEnabled,
    ttsVoice: other.ttsVoice,
    messageCount: other.messageCount,
    tokenCount: other.tokenCount,
    promptTokens: other.promptTokens,
    completionTokens: other.completionTokens,
    cost: other.cost,
    lastMessage: other.lastMessage,
    lastMessageAt: other.lastMessageAt,
    isPinned: other.isPinned,
    isArchived: other.isArchived,
    isMuted: other.isMuted,
    isFavorite: other.isFavorite,
    coverImage: other.coverImage,
    icon: other.icon,
    color: other.color,
    category: other.category,
    tags: other.tags,
    agentId: other.agentId,
    agentEnabled: other.agentEnabled,
    knowledgeBaseId: other.knowledgeBaseId,
    knowledgeEnabled: other.knowledgeEnabled,
    webSearchEnabled: other.webSearchEnabled,
    codeInterpreter: other.codeInterpreter,
    functionCalling: other.functionCalling,
    enabledTools: other.enabledTools,
    mode: other.mode,
    visionEnabled: other.visionEnabled,
    audioEnabled: other.audioEnabled,
    fileEnabled: other.fileEnabled,
    maxFileSize: other.maxFileSize,
    maxFiles: other.maxFiles,
    allowedFileTypes: other.allowedFileTypes,
    createdAt: other.createdAt,
    updatedAt: other.updatedAt,
    deletedAt: other.deletedAt,
    isDeleted: other.isDeleted,
    deleteReason: other.deleteReason,
    autoDelete: other.autoDelete,
    autoDeleteDays: other.autoDeleteDays,
    autoDeleteAt: other.autoDeleteAt,
    encrypted: other.encrypted,
    encryptionKey: other.encryptionKey,
    shared: other.shared,
    shareLink: other.shareLink,
    shareExpiresAt: other.shareExpiresAt,
    shareViewCount: other.shareViewCount,
    allowCopy: other.allowCopy,
    allowExport: other.allowExport,
    allowShare: other.allowShare,
    allowEdit: other.allowEdit,
    allowDelete: other.allowDelete,
    permission: other.permission,
    sharedWith: other.sharedWith,
    editors: other.editors,
    viewers: other.viewers,
    workspaceId: other.workspaceId,
    folderId: other.folderId,
    sortOrder: other.sortOrder,
    status: other.status,
    error: other.error,
    retryCount: other.retryCount,
    lastRetryAt: other.lastRetryAt,
    rateLimited: other.rateLimited,
    rateLimitResetAt: other.rateLimitResetAt,
    requestsPerMinute: other.requestsPerMinute,
    requestsPerHour: other.requestsPerHour,
    requestsPerDay: other.requestsPerDay,
    windowStart: other.windowStart,
    quotaExceeded: other.quotaExceeded,
    quotaType: other.quotaType,
    quotaResetAt: other.quotaResetAt,
    quotaLimit: other.quotaLimit,
    quotaUsed: other.quotaUsed,
    quotaPercent: other.quotaPercent,
    notifyOnQuota: other.notifyOnQuota,
    notifyOnError: other.notifyOnError,
    notifyOnComplete: other.notifyOnComplete,
    notifyOnMention: other.notifyOnMention,
    notifyOnReply: other.notifyOnReply,
    notifyOnReaction: other.notifyOnReaction,
    notifyOnShare: other.notifyOnShare,
    notifyOnAssignment: other.notifyOnAssignment,
    notifyOnDueDate: other.notifyOnDueDate,
    notifyOnReminder: other.notifyOnReminder,
    unreadCount: other.unreadCount,
    lastReadAt: other.lastReadAt,
    isRead: other.isRead,
    isMentioned: other.isMentioned,
    isReplied: other.isReplied,
    isReacted: other.isReacted,
    draft: other.draft,
    draftSavedAt: other.draftSavedAt,
    hasDraft: other.hasDraft,
    attachments: other.attachments,
    images: other.images,
    videos: other.videos,
    audios: other.audios,
    files: other.files,
    links: other.links,
    mentions: other.mentions,
    hashtags: other.hashtags,
    emojis: other.emojis,
    summary: other.summary,
    keyPoints: other.keyPoints,
    actionItems: other.actionItems,
    questions: other.questions,
    answers: other.answers,
    sentiment: other.sentiment,
    sentimentScore: other.sentimentScore,
    topics: other.topics,
    entities: other.entities,
    keywords: other.keywords,
    language: other.language,
    confidence: other.confidence,
    modelVersion: other.modelVersion,
    modelProvider: other.modelProvider,
    modelEndpoint: other.modelEndpoint,
    latencyMs: other.latencyMs,
    firstTokenMs: other.firstTokenMs,
    totalTimeMs: other.totalTimeMs,
    tokensPerSecond: other.tokensPerSecond,
    cached: other.cached,
    cacheKey: other.cacheKey,
    cachedAt: other.cachedAt,
    cacheHits: other.cacheHits,
    cacheMisses: other.cacheMisses,
    cacheHitRate: other.cacheHitRate,
    fallbackUsed: other.fallbackUsed,
    fallbackModel: other.fallbackModel,
    fallbackReason: other.fallbackReason,
    retryUsed: other.retryUsed,
    retryAttempts: other.retryAttempts,
    retryReason: other.retryReason,
    timeoutOccurred: other.timeoutOccurred,
    timeoutMs: other.timeoutMs,
    rateLimitHit: other.rateLimitHit,
    retryAfterMs: other.retryAfterMs,
    serverError: other.serverError,
    statusCode: other.statusCode,
    errorCode: other.errorCode,
    errorMessage: other.errorMessage,
    errorType: other.errorType,
    errorDetail: other.errorDetail,
    errorStack: other.errorStack,
    errorAt: other.errorAt,
    errorResolved: other.errorResolved,
    errorResolvedAt: other.errorResolvedAt,
    resolution: other.resolution,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Conversation && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Conversation(id: $id)';

  Conversation clone() => Conversation.fromJson(toJson());

  bool get isEmpty => id.isEmpty;
  bool get isNotEmpty => id.isNotEmpty;

}
