import 'dart:convert';

/// User 数据模型
class User {
  String id;
  String username;
  String nickname;
  String email;
  String phone;
  String avatar;
  String bio;
  String gender;
  String birthday;
  String location;
  String website;
  String language;
  String timezone;
  String theme;
  int points;
  int level;
  int exp;
  bool isVerified;
  bool isPremium;
  bool isAdmin;
  bool isBanned;
  DateTime createdAt;
  DateTime updatedAt;
  DateTime lastLoginAt;
  String lastLoginIp;
  String lastLoginDevice;
  int loginCount;
  int followerCount;
  int followingCount;
  int postCount;
  int chatCount;
  int imageGenCount;
  int videoGenCount;
  String githubId;
  String githubUsername;
  String githubAvatar;
  bool githubBound;
  String wechatId;
  bool wechatBound;
  String qqId;
  bool qqBound;
  String appleId;
  bool appleBound;
  bool twoFactorEnabled;
  String twoFactorMethod;
  bool emailVerified;
  bool phoneVerified;
  bool identityVerified;
  String realName;
  String idCard;
  String idCardType;
  DateTime identityVerifiedAt;
  String status;
  String accountType;
  DateTime premiumExpiresAt;
  String premiumPlan;
  bool autoRenew;
  int maxConversations;
  int maxMessagesPerDay;
  int maxImageGenPerDay;
  int maxVideoGenPerDay;
  int maxFileSize;
  int maxUploadsPerDay;
  String defaultModel;
  String defaultImageModel;
  String defaultVideoModel;
  double defaultTemperature;
  int defaultMaxTokens;
  bool streamingEnabled;
  bool markdownEnabled;
  bool codeHighlightEnabled;
  bool autoTranslate;
  String targetLanguage;
  bool ttsEnabled;
  String ttsVoice;
  double ttsRate;
  double ttsPitch;
  bool autoPlayVoice;
  bool voiceInputEnabled;
  String voiceInputLanguage;
  bool wakeWordEnabled;
  String wakeWord;
  bool alwaysOnDisplay;
  bool batteryOptimization;
  bool dataSaver;
  bool wifiOnlyDownloads;
  bool autoUpdate;
  bool betaUpdates;
  bool analyticsEnabled;
  bool crashReporting;
  bool personalizedAds;
  bool showOnlineStatus;
  bool showReadReceipts;
  bool allowDirectMessages;
  bool allowFriendRequests;
  bool publicProfile;
  bool showActivity;
  bool allowTagging;
  bool allowMentions;
  String contentFilter;
  bool safeSearch;
  bool matureContent;
  bool autoDeleteMessages;
  int autoDeleteDays;
  bool clearCacheOnExit;
  bool incognitoMode;
  bool doNotDisturb;
  DateTime dndStart;
  DateTime dndEnd;
  bool vibrateEnabled;
  bool soundEnabled;
  String notificationSound;
  bool ledEnabled;
  String ledColor;
  bool lockScreenNotifications;
  bool notificationPreview;
  int notificationPriority;
  bool badgeEnabled;
  bool headsUpEnabled;
  String fontFamily;
  double fontScale;
  String displayMode;
  bool amoledDark;
  bool reduceMotion;
  bool highContrast;
  bool largeText;
  bool screenReader;
  String accentColor;
  String backgroundColor;
  String cardColor;
  String textColor;
  String secondaryTextColor;
  double cornerRadius;
  double blurRadius;
  double shadowOpacity;
  bool neumorphism;
  bool glassmorphism;
  bool gradientBackground;
  bool animatedBackground;
  String wallpaper;
  double wallpaperOpacity;
  bool parallaxEffect;
  bool hapticFeedback;
  String hapticStrength;
  bool soundEffects;
  double soundVolume;
  bool pageTransitions;
  String transitionType;
  int transitionDuration;
  bool listAnimations;
  bool staggerAnimations;
  int staggerDelay;
  bool buttonAnimations;
  bool cardAnimations;
  bool dialogAnimations;
  bool loadingAnimations;
  String loadingStyle;
  bool shimmerEffect;
  bool skeletonLoading;
  bool pullToRefresh;
  bool infiniteScroll;
  int pageSize;
  bool cacheImages;
  int imageCacheSize;
  bool compressImages;
  int imageQuality;
  bool lazyLoadImages;
  bool webpFormat;
  bool autoRotateImages;
  bool saveToGallery;
  bool askBeforeSaving;
  String downloadPath;
  bool nomediaFile;
  bool showFileExtensions;
  bool sortByName;
  bool sortAscending;
  String viewMode;
  int gridColumns;
  bool showHiddenFiles;
  bool showThumbnails;
  int thumbnailSize;
  bool fastScroll;
  bool scrollbars;
  bool edgeToEdge;
  bool immersiveMode;
  bool hideStatusBar;
  bool hideNavigationBar;
  bool fullscreenMode;
  bool landscapeMode;
  bool autoRotate;
  String orientation;
  bool keepScreenOn;
  int screenTimeout;
  bool brightnessControl;
  double brightness;
  bool autoBrightness;
  bool nightMode;
  int nightModeStart;
  int nightModeEnd;
  double nightModeIntensity;
  bool blueLightFilter;
  double blueLightIntensity;
  bool grayscaleMode;
  bool colorInversion;
  bool colorCorrection;
  String colorCorrectionMode;
  double colorCorrectionIntensity;

  User({
    required this.id, required this.username, required this.nickname, required this.email, required this.phone, required this.avatar, required this.bio, required this.gender, required this.birthday, required this.location, required this.website, required this.language, required this.timezone, required this.theme, required this.points, required this.level, required this.exp, required this.isVerified, required this.isPremium, required this.isAdmin, required this.isBanned, required this.createdAt, required this.updatedAt, required this.lastLoginAt, required this.lastLoginIp, required this.lastLoginDevice, required this.loginCount, required this.followerCount, required this.followingCount, required this.postCount, required this.chatCount, required this.imageGenCount, required this.videoGenCount, required this.githubId, required this.githubUsername, required this.githubAvatar, required this.githubBound, required this.wechatId, required this.wechatBound, required this.qqId, required this.qqBound, required this.appleId, required this.appleBound, required this.twoFactorEnabled, required this.twoFactorMethod, required this.emailVerified, required this.phoneVerified, required this.identityVerified, required this.realName, required this.idCard, required this.idCardType, required this.identityVerifiedAt, required this.status, required this.accountType, required this.premiumExpiresAt, required this.premiumPlan, required this.autoRenew, required this.maxConversations, required this.maxMessagesPerDay, required this.maxImageGenPerDay, required this.maxVideoGenPerDay, required this.maxFileSize, required this.maxUploadsPerDay, required this.defaultModel, required this.defaultImageModel, required this.defaultVideoModel, required this.defaultTemperature, required this.defaultMaxTokens, required this.streamingEnabled, required this.markdownEnabled, required this.codeHighlightEnabled, required this.autoTranslate, required this.targetLanguage, required this.ttsEnabled, required this.ttsVoice, required this.ttsRate, required this.ttsPitch, required this.autoPlayVoice, required this.voiceInputEnabled, required this.voiceInputLanguage, required this.wakeWordEnabled, required this.wakeWord, required this.alwaysOnDisplay, required this.batteryOptimization, required this.dataSaver, required this.wifiOnlyDownloads, required this.autoUpdate, required this.betaUpdates, required this.analyticsEnabled, required this.crashReporting, required this.personalizedAds, required this.showOnlineStatus, required this.showReadReceipts, required this.allowDirectMessages, required this.allowFriendRequests, required this.publicProfile, required this.showActivity, required this.allowTagging, required this.allowMentions, required this.contentFilter, required this.safeSearch, required this.matureContent, required this.autoDeleteMessages, required this.autoDeleteDays, required this.clearCacheOnExit, required this.incognitoMode, required this.doNotDisturb, required this.dndStart, required this.dndEnd, required this.vibrateEnabled, required this.soundEnabled, required this.notificationSound, required this.ledEnabled, required this.ledColor, required this.lockScreenNotifications, required this.notificationPreview, required this.notificationPriority, required this.badgeEnabled, required this.headsUpEnabled, required this.fontFamily, required this.fontScale, required this.displayMode, required this.amoledDark, required this.reduceMotion, required this.highContrast, required this.largeText, required this.screenReader, required this.accentColor, required this.backgroundColor, required this.cardColor, required this.textColor, required this.secondaryTextColor, required this.cornerRadius, required this.blurRadius, required this.shadowOpacity, required this.neumorphism, required this.glassmorphism, required this.gradientBackground, required this.animatedBackground, required this.wallpaper, required this.wallpaperOpacity, required this.parallaxEffect, required this.hapticFeedback, required this.hapticStrength, required this.soundEffects, required this.soundVolume, required this.pageTransitions, required this.transitionType, required this.transitionDuration, required this.listAnimations, required this.staggerAnimations, required this.staggerDelay, required this.buttonAnimations, required this.cardAnimations, required this.dialogAnimations, required this.loadingAnimations, required this.loadingStyle, required this.shimmerEffect, required this.skeletonLoading, required this.pullToRefresh, required this.infiniteScroll, required this.pageSize, required this.cacheImages, required this.imageCacheSize, required this.compressImages, required this.imageQuality, required this.lazyLoadImages, required this.webpFormat, required this.autoRotateImages, required this.saveToGallery, required this.askBeforeSaving, required this.downloadPath, required this.nomediaFile, required this.showFileExtensions, required this.sortByName, required this.sortAscending, required this.viewMode, required this.gridColumns, required this.showHiddenFiles, required this.showThumbnails, required this.thumbnailSize, required this.fastScroll, required this.scrollbars, required this.edgeToEdge, required this.immersiveMode, required this.hideStatusBar, required this.hideNavigationBar, required this.fullscreenMode, required this.landscapeMode, required this.autoRotate, required this.orientation, required this.keepScreenOn, required this.screenTimeout, required this.brightnessControl, required this.brightness, required this.autoBrightness, required this.nightMode, required this.nightModeStart, required this.nightModeEnd, required this.nightModeIntensity, required this.blueLightFilter, required this.blueLightIntensity, required this.grayscaleMode, required this.colorInversion, required this.colorCorrection, required this.colorCorrectionMode, required this.colorCorrectionIntensity,
  });

  factory User.empty() => User(
    id: '',
    username: '',
    nickname: '',
    email: '',
    phone: '',
    avatar: '',
    bio: '',
    gender: '',
    birthday: '',
    location: '',
    website: '',
    language: zh_CN,
    timezone: Asia/Shanghai,
    theme: pink,
    points: 0,
    level: 1,
    exp: 0,
    isVerified: false,
    isPremium: false,
    isAdmin: false,
    isBanned: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    lastLoginAt: DateTime.now(),
    lastLoginIp: '',
    lastLoginDevice: '',
    loginCount: 0,
    followerCount: 0,
    followingCount: 0,
    postCount: 0,
    chatCount: 0,
    imageGenCount: 0,
    videoGenCount: 0,
    githubId: '',
    githubUsername: '',
    githubAvatar: '',
    githubBound: false,
    wechatId: '',
    wechatBound: false,
    qqId: '',
    qqBound: false,
    appleId: '',
    appleBound: false,
    twoFactorEnabled: false,
    twoFactorMethod: '',
    emailVerified: false,
    phoneVerified: false,
    identityVerified: false,
    realName: '',
    idCard: '',
    idCardType: '',
    identityVerifiedAt: DateTime.now(),
    status: active,
    accountType: normal,
    premiumExpiresAt: DateTime.now(),
    premiumPlan: '',
    autoRenew: false,
    maxConversations: 100,
    maxMessagesPerDay: 1000,
    maxImageGenPerDay: 50,
    maxVideoGenPerDay: 10,
    maxFileSize: 10485760,
    maxUploadsPerDay: 100,
    defaultModel: glm-4,
    defaultImageModel: seedream,
    defaultVideoModel: seedance,
    defaultTemperature: 0.7,
    defaultMaxTokens: 4096,
    streamingEnabled: true,
    markdownEnabled: true,
    codeHighlightEnabled: true,
    autoTranslate: false,
    targetLanguage: zh,
    ttsEnabled: false,
    ttsVoice: '',
    ttsRate: 1.0,
    ttsPitch: 1.0,
    autoPlayVoice: false,
    voiceInputEnabled: false,
    voiceInputLanguage: zh_CN,
    wakeWordEnabled: false,
    wakeWord: '',
    alwaysOnDisplay: false,
    batteryOptimization: true,
    dataSaver: false,
    wifiOnlyDownloads: false,
    autoUpdate: true,
    betaUpdates: false,
    analyticsEnabled: true,
    crashReporting: true,
    personalizedAds: false,
    showOnlineStatus: true,
    showReadReceipts: true,
    allowDirectMessages: true,
    allowFriendRequests: true,
    publicProfile: true,
    showActivity: true,
    allowTagging: true,
    allowMentions: true,
    contentFilter: moderate,
    safeSearch: true,
    matureContent: false,
    autoDeleteMessages: false,
    autoDeleteDays: 30,
    clearCacheOnExit: false,
    incognitoMode: false,
    doNotDisturb: false,
    dndStart: DateTime.now(),
    dndEnd: DateTime.now(),
    vibrateEnabled: true,
    soundEnabled: true,
    notificationSound: default,
    ledEnabled: true,
    ledColor: #FF6B9D,
    lockScreenNotifications: true,
    notificationPreview: true,
    notificationPriority: 2,
    badgeEnabled: true,
    headsUpEnabled: true,
    fontFamily: LXGW WenKai,
    fontScale: 1.0,
    displayMode: system,
    amoledDark: false,
    reduceMotion: false,
    highContrast: false,
    largeText: false,
    screenReader: false,
    accentColor: #FF6B9D,
    backgroundColor: #FFF0F5,
    cardColor: #FFFFFF,
    textColor: #2D1B2E,
    secondaryTextColor: #6B4D5E,
    cornerRadius: 16.0,
    blurRadius: 20.0,
    shadowOpacity: 0.15,
    neumorphism: false,
    glassmorphism: true,
    gradientBackground: true,
    animatedBackground: false,
    wallpaper: '',
    wallpaperOpacity: 0.3,
    parallaxEffect: true,
    hapticFeedback: true,
    hapticStrength: medium,
    soundEffects: true,
    soundVolume: 0.5,
    pageTransitions: true,
    transitionType: scale,
    transitionDuration: 300,
    listAnimations: true,
    staggerAnimations: true,
    staggerDelay: 50,
    buttonAnimations: true,
    cardAnimations: true,
    dialogAnimations: true,
    loadingAnimations: true,
    loadingStyle: spinner,
    shimmerEffect: true,
    skeletonLoading: true,
    pullToRefresh: true,
    infiniteScroll: true,
    pageSize: 20,
    cacheImages: true,
    imageCacheSize: 100,
    compressImages: true,
    imageQuality: 85,
    lazyLoadImages: true,
    webpFormat: true,
    autoRotateImages: true,
    saveToGallery: false,
    askBeforeSaving: true,
    downloadPath: '',
    nomediaFile: true,
    showFileExtensions: true,
    sortByName: true,
    sortAscending: true,
    viewMode: grid,
    gridColumns: 3,
    showHiddenFiles: false,
    showThumbnails: true,
    thumbnailSize: 200,
    fastScroll: true,
    scrollbars: true,
    edgeToEdge: true,
    immersiveMode: false,
    hideStatusBar: false,
    hideNavigationBar: false,
    fullscreenMode: false,
    landscapeMode: false,
    autoRotate: true,
    orientation: portrait,
    keepScreenOn: false,
    screenTimeout: 120,
    brightnessControl: true,
    brightness: 0.8,
    autoBrightness: true,
    nightMode: false,
    nightModeStart: 22,
    nightModeEnd: 6,
    nightModeIntensity: 0.3,
    blueLightFilter: false,
    blueLightIntensity: 0.5,
    grayscaleMode: false,
    colorInversion: false,
    colorCorrection: false,
    colorCorrectionMode: protanomaly,
    colorCorrectionIntensity: 0.5,
  );

  factory User.fromJson(Map<String, dynamic> json) => User(
    id: json['id'] ?? '',
    username: json['username'] ?? '',
    nickname: json['nickname'] ?? '',
    email: json['email'] ?? '',
    phone: json['phone'] ?? '',
    avatar: json['avatar'] ?? '',
    bio: json['bio'] ?? '',
    gender: json['gender'] ?? '',
    birthday: json['birthday'] ?? '',
    location: json['location'] ?? '',
    website: json['website'] ?? '',
    language: json['language'] ?? '',
    timezone: json['timezone'] ?? '',
    theme: json['theme'] ?? '',
    points: json['points'] ?? 0,
    level: json['level'] ?? 0,
    exp: json['exp'] ?? 0,
    isVerified: json['isVerified'] ?? false,
    isPremium: json['isPremium'] ?? false,
    isAdmin: json['isAdmin'] ?? false,
    isBanned: json['isBanned'] ?? false,
    createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : DateTime.now(),
    updatedAt: json['updatedAt'] != null ? DateTime.parse(json['updatedAt']) : DateTime.now(),
    lastLoginAt: json['lastLoginAt'] != null ? DateTime.parse(json['lastLoginAt']) : DateTime.now(),
    lastLoginIp: json['lastLoginIp'] ?? '',
    lastLoginDevice: json['lastLoginDevice'] ?? '',
    loginCount: json['loginCount'] ?? 0,
    followerCount: json['followerCount'] ?? 0,
    followingCount: json['followingCount'] ?? 0,
    postCount: json['postCount'] ?? 0,
    chatCount: json['chatCount'] ?? 0,
    imageGenCount: json['imageGenCount'] ?? 0,
    videoGenCount: json['videoGenCount'] ?? 0,
    githubId: json['githubId'] ?? '',
    githubUsername: json['githubUsername'] ?? '',
    githubAvatar: json['githubAvatar'] ?? '',
    githubBound: json['githubBound'] ?? false,
    wechatId: json['wechatId'] ?? '',
    wechatBound: json['wechatBound'] ?? false,
    qqId: json['qqId'] ?? '',
    qqBound: json['qqBound'] ?? false,
    appleId: json['appleId'] ?? '',
    appleBound: json['appleBound'] ?? false,
    twoFactorEnabled: json['twoFactorEnabled'] ?? false,
    twoFactorMethod: json['twoFactorMethod'] ?? '',
    emailVerified: json['emailVerified'] ?? false,
    phoneVerified: json['phoneVerified'] ?? false,
    identityVerified: json['identityVerified'] ?? false,
    realName: json['realName'] ?? '',
    idCard: json['idCard'] ?? '',
    idCardType: json['idCardType'] ?? '',
    identityVerifiedAt: json['identityVerifiedAt'] != null ? DateTime.parse(json['identityVerifiedAt']) : DateTime.now(),
    status: json['status'] ?? '',
    accountType: json['accountType'] ?? '',
    premiumExpiresAt: json['premiumExpiresAt'] != null ? DateTime.parse(json['premiumExpiresAt']) : DateTime.now(),
    premiumPlan: json['premiumPlan'] ?? '',
    autoRenew: json['autoRenew'] ?? false,
    maxConversations: json['maxConversations'] ?? 0,
    maxMessagesPerDay: json['maxMessagesPerDay'] ?? 0,
    maxImageGenPerDay: json['maxImageGenPerDay'] ?? 0,
    maxVideoGenPerDay: json['maxVideoGenPerDay'] ?? 0,
    maxFileSize: json['maxFileSize'] ?? 0,
    maxUploadsPerDay: json['maxUploadsPerDay'] ?? 0,
    defaultModel: json['defaultModel'] ?? '',
    defaultImageModel: json['defaultImageModel'] ?? '',
    defaultVideoModel: json['defaultVideoModel'] ?? '',
    defaultTemperature: (json['defaultTemperature'] ?? 0.0).toDouble(),
    defaultMaxTokens: json['defaultMaxTokens'] ?? 0,
    streamingEnabled: json['streamingEnabled'] ?? false,
    markdownEnabled: json['markdownEnabled'] ?? false,
    codeHighlightEnabled: json['codeHighlightEnabled'] ?? false,
    autoTranslate: json['autoTranslate'] ?? false,
    targetLanguage: json['targetLanguage'] ?? '',
    ttsEnabled: json['ttsEnabled'] ?? false,
    ttsVoice: json['ttsVoice'] ?? '',
    ttsRate: (json['ttsRate'] ?? 0.0).toDouble(),
    ttsPitch: (json['ttsPitch'] ?? 0.0).toDouble(),
    autoPlayVoice: json['autoPlayVoice'] ?? false,
    voiceInputEnabled: json['voiceInputEnabled'] ?? false,
    voiceInputLanguage: json['voiceInputLanguage'] ?? '',
    wakeWordEnabled: json['wakeWordEnabled'] ?? false,
    wakeWord: json['wakeWord'] ?? '',
    alwaysOnDisplay: json['alwaysOnDisplay'] ?? false,
    batteryOptimization: json['batteryOptimization'] ?? false,
    dataSaver: json['dataSaver'] ?? false,
    wifiOnlyDownloads: json['wifiOnlyDownloads'] ?? false,
    autoUpdate: json['autoUpdate'] ?? false,
    betaUpdates: json['betaUpdates'] ?? false,
    analyticsEnabled: json['analyticsEnabled'] ?? false,
    crashReporting: json['crashReporting'] ?? false,
    personalizedAds: json['personalizedAds'] ?? false,
    showOnlineStatus: json['showOnlineStatus'] ?? false,
    showReadReceipts: json['showReadReceipts'] ?? false,
    allowDirectMessages: json['allowDirectMessages'] ?? false,
    allowFriendRequests: json['allowFriendRequests'] ?? false,
    publicProfile: json['publicProfile'] ?? false,
    showActivity: json['showActivity'] ?? false,
    allowTagging: json['allowTagging'] ?? false,
    allowMentions: json['allowMentions'] ?? false,
    contentFilter: json['contentFilter'] ?? '',
    safeSearch: json['safeSearch'] ?? false,
    matureContent: json['matureContent'] ?? false,
    autoDeleteMessages: json['autoDeleteMessages'] ?? false,
    autoDeleteDays: json['autoDeleteDays'] ?? 0,
    clearCacheOnExit: json['clearCacheOnExit'] ?? false,
    incognitoMode: json['incognitoMode'] ?? false,
    doNotDisturb: json['doNotDisturb'] ?? false,
    dndStart: json['dndStart'] != null ? DateTime.parse(json['dndStart']) : DateTime.now(),
    dndEnd: json['dndEnd'] != null ? DateTime.parse(json['dndEnd']) : DateTime.now(),
    vibrateEnabled: json['vibrateEnabled'] ?? false,
    soundEnabled: json['soundEnabled'] ?? false,
    notificationSound: json['notificationSound'] ?? '',
    ledEnabled: json['ledEnabled'] ?? false,
    ledColor: json['ledColor'] ?? '',
    lockScreenNotifications: json['lockScreenNotifications'] ?? false,
    notificationPreview: json['notificationPreview'] ?? false,
    notificationPriority: json['notificationPriority'] ?? 0,
    badgeEnabled: json['badgeEnabled'] ?? false,
    headsUpEnabled: json['headsUpEnabled'] ?? false,
    fontFamily: json['fontFamily'] ?? '',
    fontScale: (json['fontScale'] ?? 0.0).toDouble(),
    displayMode: json['displayMode'] ?? '',
    amoledDark: json['amoledDark'] ?? false,
    reduceMotion: json['reduceMotion'] ?? false,
    highContrast: json['highContrast'] ?? false,
    largeText: json['largeText'] ?? false,
    screenReader: json['screenReader'] ?? false,
    accentColor: json['accentColor'] ?? '',
    backgroundColor: json['backgroundColor'] ?? '',
    cardColor: json['cardColor'] ?? '',
    textColor: json['textColor'] ?? '',
    secondaryTextColor: json['secondaryTextColor'] ?? '',
    cornerRadius: (json['cornerRadius'] ?? 0.0).toDouble(),
    blurRadius: (json['blurRadius'] ?? 0.0).toDouble(),
    shadowOpacity: (json['shadowOpacity'] ?? 0.0).toDouble(),
    neumorphism: json['neumorphism'] ?? false,
    glassmorphism: json['glassmorphism'] ?? false,
    gradientBackground: json['gradientBackground'] ?? false,
    animatedBackground: json['animatedBackground'] ?? false,
    wallpaper: json['wallpaper'] ?? '',
    wallpaperOpacity: (json['wallpaperOpacity'] ?? 0.0).toDouble(),
    parallaxEffect: json['parallaxEffect'] ?? false,
    hapticFeedback: json['hapticFeedback'] ?? false,
    hapticStrength: json['hapticStrength'] ?? '',
    soundEffects: json['soundEffects'] ?? false,
    soundVolume: (json['soundVolume'] ?? 0.0).toDouble(),
    pageTransitions: json['pageTransitions'] ?? false,
    transitionType: json['transitionType'] ?? '',
    transitionDuration: json['transitionDuration'] ?? 0,
    listAnimations: json['listAnimations'] ?? false,
    staggerAnimations: json['staggerAnimations'] ?? false,
    staggerDelay: json['staggerDelay'] ?? 0,
    buttonAnimations: json['buttonAnimations'] ?? false,
    cardAnimations: json['cardAnimations'] ?? false,
    dialogAnimations: json['dialogAnimations'] ?? false,
    loadingAnimations: json['loadingAnimations'] ?? false,
    loadingStyle: json['loadingStyle'] ?? '',
    shimmerEffect: json['shimmerEffect'] ?? false,
    skeletonLoading: json['skeletonLoading'] ?? false,
    pullToRefresh: json['pullToRefresh'] ?? false,
    infiniteScroll: json['infiniteScroll'] ?? false,
    pageSize: json['pageSize'] ?? 0,
    cacheImages: json['cacheImages'] ?? false,
    imageCacheSize: json['imageCacheSize'] ?? 0,
    compressImages: json['compressImages'] ?? false,
    imageQuality: json['imageQuality'] ?? 0,
    lazyLoadImages: json['lazyLoadImages'] ?? false,
    webpFormat: json['webpFormat'] ?? false,
    autoRotateImages: json['autoRotateImages'] ?? false,
    saveToGallery: json['saveToGallery'] ?? false,
    askBeforeSaving: json['askBeforeSaving'] ?? false,
    downloadPath: json['downloadPath'] ?? '',
    nomediaFile: json['nomediaFile'] ?? false,
    showFileExtensions: json['showFileExtensions'] ?? false,
    sortByName: json['sortByName'] ?? false,
    sortAscending: json['sortAscending'] ?? false,
    viewMode: json['viewMode'] ?? '',
    gridColumns: json['gridColumns'] ?? 0,
    showHiddenFiles: json['showHiddenFiles'] ?? false,
    showThumbnails: json['showThumbnails'] ?? false,
    thumbnailSize: json['thumbnailSize'] ?? 0,
    fastScroll: json['fastScroll'] ?? false,
    scrollbars: json['scrollbars'] ?? false,
    edgeToEdge: json['edgeToEdge'] ?? false,
    immersiveMode: json['immersiveMode'] ?? false,
    hideStatusBar: json['hideStatusBar'] ?? false,
    hideNavigationBar: json['hideNavigationBar'] ?? false,
    fullscreenMode: json['fullscreenMode'] ?? false,
    landscapeMode: json['landscapeMode'] ?? false,
    autoRotate: json['autoRotate'] ?? false,
    orientation: json['orientation'] ?? '',
    keepScreenOn: json['keepScreenOn'] ?? false,
    screenTimeout: json['screenTimeout'] ?? 0,
    brightnessControl: json['brightnessControl'] ?? false,
    brightness: (json['brightness'] ?? 0.0).toDouble(),
    autoBrightness: json['autoBrightness'] ?? false,
    nightMode: json['nightMode'] ?? false,
    nightModeStart: json['nightModeStart'] ?? 0,
    nightModeEnd: json['nightModeEnd'] ?? 0,
    nightModeIntensity: (json['nightModeIntensity'] ?? 0.0).toDouble(),
    blueLightFilter: json['blueLightFilter'] ?? false,
    blueLightIntensity: (json['blueLightIntensity'] ?? 0.0).toDouble(),
    grayscaleMode: json['grayscaleMode'] ?? false,
    colorInversion: json['colorInversion'] ?? false,
    colorCorrection: json['colorCorrection'] ?? false,
    colorCorrectionMode: json['colorCorrectionMode'] ?? '',
    colorCorrectionIntensity: (json['colorCorrectionIntensity'] ?? 0.0).toDouble(),
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'username': username,
    'nickname': nickname,
    'email': email,
    'phone': phone,
    'avatar': avatar,
    'bio': bio,
    'gender': gender,
    'birthday': birthday,
    'location': location,
    'website': website,
    'language': language,
    'timezone': timezone,
    'theme': theme,
    'points': points,
    'level': level,
    'exp': exp,
    'isVerified': isVerified,
    'isPremium': isPremium,
    'isAdmin': isAdmin,
    'isBanned': isBanned,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'lastLoginAt': lastLoginAt.toIso8601String(),
    'lastLoginIp': lastLoginIp,
    'lastLoginDevice': lastLoginDevice,
    'loginCount': loginCount,
    'followerCount': followerCount,
    'followingCount': followingCount,
    'postCount': postCount,
    'chatCount': chatCount,
    'imageGenCount': imageGenCount,
    'videoGenCount': videoGenCount,
    'githubId': githubId,
    'githubUsername': githubUsername,
    'githubAvatar': githubAvatar,
    'githubBound': githubBound,
    'wechatId': wechatId,
    'wechatBound': wechatBound,
    'qqId': qqId,
    'qqBound': qqBound,
    'appleId': appleId,
    'appleBound': appleBound,
    'twoFactorEnabled': twoFactorEnabled,
    'twoFactorMethod': twoFactorMethod,
    'emailVerified': emailVerified,
    'phoneVerified': phoneVerified,
    'identityVerified': identityVerified,
    'realName': realName,
    'idCard': idCard,
    'idCardType': idCardType,
    'identityVerifiedAt': identityVerifiedAt.toIso8601String(),
    'status': status,
    'accountType': accountType,
    'premiumExpiresAt': premiumExpiresAt.toIso8601String(),
    'premiumPlan': premiumPlan,
    'autoRenew': autoRenew,
    'maxConversations': maxConversations,
    'maxMessagesPerDay': maxMessagesPerDay,
    'maxImageGenPerDay': maxImageGenPerDay,
    'maxVideoGenPerDay': maxVideoGenPerDay,
    'maxFileSize': maxFileSize,
    'maxUploadsPerDay': maxUploadsPerDay,
    'defaultModel': defaultModel,
    'defaultImageModel': defaultImageModel,
    'defaultVideoModel': defaultVideoModel,
    'defaultTemperature': defaultTemperature,
    'defaultMaxTokens': defaultMaxTokens,
    'streamingEnabled': streamingEnabled,
    'markdownEnabled': markdownEnabled,
    'codeHighlightEnabled': codeHighlightEnabled,
    'autoTranslate': autoTranslate,
    'targetLanguage': targetLanguage,
    'ttsEnabled': ttsEnabled,
    'ttsVoice': ttsVoice,
    'ttsRate': ttsRate,
    'ttsPitch': ttsPitch,
    'autoPlayVoice': autoPlayVoice,
    'voiceInputEnabled': voiceInputEnabled,
    'voiceInputLanguage': voiceInputLanguage,
    'wakeWordEnabled': wakeWordEnabled,
    'wakeWord': wakeWord,
    'alwaysOnDisplay': alwaysOnDisplay,
    'batteryOptimization': batteryOptimization,
    'dataSaver': dataSaver,
    'wifiOnlyDownloads': wifiOnlyDownloads,
    'autoUpdate': autoUpdate,
    'betaUpdates': betaUpdates,
    'analyticsEnabled': analyticsEnabled,
    'crashReporting': crashReporting,
    'personalizedAds': personalizedAds,
    'showOnlineStatus': showOnlineStatus,
    'showReadReceipts': showReadReceipts,
    'allowDirectMessages': allowDirectMessages,
    'allowFriendRequests': allowFriendRequests,
    'publicProfile': publicProfile,
    'showActivity': showActivity,
    'allowTagging': allowTagging,
    'allowMentions': allowMentions,
    'contentFilter': contentFilter,
    'safeSearch': safeSearch,
    'matureContent': matureContent,
    'autoDeleteMessages': autoDeleteMessages,
    'autoDeleteDays': autoDeleteDays,
    'clearCacheOnExit': clearCacheOnExit,
    'incognitoMode': incognitoMode,
    'doNotDisturb': doNotDisturb,
    'dndStart': dndStart.toIso8601String(),
    'dndEnd': dndEnd.toIso8601String(),
    'vibrateEnabled': vibrateEnabled,
    'soundEnabled': soundEnabled,
    'notificationSound': notificationSound,
    'ledEnabled': ledEnabled,
    'ledColor': ledColor,
    'lockScreenNotifications': lockScreenNotifications,
    'notificationPreview': notificationPreview,
    'notificationPriority': notificationPriority,
    'badgeEnabled': badgeEnabled,
    'headsUpEnabled': headsUpEnabled,
    'fontFamily': fontFamily,
    'fontScale': fontScale,
    'displayMode': displayMode,
    'amoledDark': amoledDark,
    'reduceMotion': reduceMotion,
    'highContrast': highContrast,
    'largeText': largeText,
    'screenReader': screenReader,
    'accentColor': accentColor,
    'backgroundColor': backgroundColor,
    'cardColor': cardColor,
    'textColor': textColor,
    'secondaryTextColor': secondaryTextColor,
    'cornerRadius': cornerRadius,
    'blurRadius': blurRadius,
    'shadowOpacity': shadowOpacity,
    'neumorphism': neumorphism,
    'glassmorphism': glassmorphism,
    'gradientBackground': gradientBackground,
    'animatedBackground': animatedBackground,
    'wallpaper': wallpaper,
    'wallpaperOpacity': wallpaperOpacity,
    'parallaxEffect': parallaxEffect,
    'hapticFeedback': hapticFeedback,
    'hapticStrength': hapticStrength,
    'soundEffects': soundEffects,
    'soundVolume': soundVolume,
    'pageTransitions': pageTransitions,
    'transitionType': transitionType,
    'transitionDuration': transitionDuration,
    'listAnimations': listAnimations,
    'staggerAnimations': staggerAnimations,
    'staggerDelay': staggerDelay,
    'buttonAnimations': buttonAnimations,
    'cardAnimations': cardAnimations,
    'dialogAnimations': dialogAnimations,
    'loadingAnimations': loadingAnimations,
    'loadingStyle': loadingStyle,
    'shimmerEffect': shimmerEffect,
    'skeletonLoading': skeletonLoading,
    'pullToRefresh': pullToRefresh,
    'infiniteScroll': infiniteScroll,
    'pageSize': pageSize,
    'cacheImages': cacheImages,
    'imageCacheSize': imageCacheSize,
    'compressImages': compressImages,
    'imageQuality': imageQuality,
    'lazyLoadImages': lazyLoadImages,
    'webpFormat': webpFormat,
    'autoRotateImages': autoRotateImages,
    'saveToGallery': saveToGallery,
    'askBeforeSaving': askBeforeSaving,
    'downloadPath': downloadPath,
    'nomediaFile': nomediaFile,
    'showFileExtensions': showFileExtensions,
    'sortByName': sortByName,
    'sortAscending': sortAscending,
    'viewMode': viewMode,
    'gridColumns': gridColumns,
    'showHiddenFiles': showHiddenFiles,
    'showThumbnails': showThumbnails,
    'thumbnailSize': thumbnailSize,
    'fastScroll': fastScroll,
    'scrollbars': scrollbars,
    'edgeToEdge': edgeToEdge,
    'immersiveMode': immersiveMode,
    'hideStatusBar': hideStatusBar,
    'hideNavigationBar': hideNavigationBar,
    'fullscreenMode': fullscreenMode,
    'landscapeMode': landscapeMode,
    'autoRotate': autoRotate,
    'orientation': orientation,
    'keepScreenOn': keepScreenOn,
    'screenTimeout': screenTimeout,
    'brightnessControl': brightnessControl,
    'brightness': brightness,
    'autoBrightness': autoBrightness,
    'nightMode': nightMode,
    'nightModeStart': nightModeStart,
    'nightModeEnd': nightModeEnd,
    'nightModeIntensity': nightModeIntensity,
    'blueLightFilter': blueLightFilter,
    'blueLightIntensity': blueLightIntensity,
    'grayscaleMode': grayscaleMode,
    'colorInversion': colorInversion,
    'colorCorrection': colorCorrection,
    'colorCorrectionMode': colorCorrectionMode,
    'colorCorrectionIntensity': colorCorrectionIntensity,
  };

  User copyWith({
    String? id,
    String? username,
    String? nickname,
    String? email,
    String? phone,
    String? avatar,
    String? bio,
    String? gender,
    String? birthday,
    String? location,
    String? website,
    String? language,
    String? timezone,
    String? theme,
    int? points,
    int? level,
    int? exp,
    bool? isVerified,
    bool? isPremium,
    bool? isAdmin,
    bool? isBanned,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? lastLoginAt,
    String? lastLoginIp,
    String? lastLoginDevice,
    int? loginCount,
    int? followerCount,
    int? followingCount,
    int? postCount,
    int? chatCount,
    int? imageGenCount,
    int? videoGenCount,
    String? githubId,
    String? githubUsername,
    String? githubAvatar,
    bool? githubBound,
    String? wechatId,
    bool? wechatBound,
    String? qqId,
    bool? qqBound,
    String? appleId,
    bool? appleBound,
    bool? twoFactorEnabled,
    String? twoFactorMethod,
    bool? emailVerified,
    bool? phoneVerified,
    bool? identityVerified,
    String? realName,
    String? idCard,
    String? idCardType,
    DateTime? identityVerifiedAt,
    String? status,
    String? accountType,
    DateTime? premiumExpiresAt,
    String? premiumPlan,
    bool? autoRenew,
    int? maxConversations,
    int? maxMessagesPerDay,
    int? maxImageGenPerDay,
    int? maxVideoGenPerDay,
    int? maxFileSize,
    int? maxUploadsPerDay,
    String? defaultModel,
    String? defaultImageModel,
    String? defaultVideoModel,
    double? defaultTemperature,
    int? defaultMaxTokens,
    bool? streamingEnabled,
    bool? markdownEnabled,
    bool? codeHighlightEnabled,
    bool? autoTranslate,
    String? targetLanguage,
    bool? ttsEnabled,
    String? ttsVoice,
    double? ttsRate,
    double? ttsPitch,
    bool? autoPlayVoice,
    bool? voiceInputEnabled,
    String? voiceInputLanguage,
    bool? wakeWordEnabled,
    String? wakeWord,
    bool? alwaysOnDisplay,
    bool? batteryOptimization,
    bool? dataSaver,
    bool? wifiOnlyDownloads,
    bool? autoUpdate,
    bool? betaUpdates,
    bool? analyticsEnabled,
    bool? crashReporting,
    bool? personalizedAds,
    bool? showOnlineStatus,
    bool? showReadReceipts,
    bool? allowDirectMessages,
    bool? allowFriendRequests,
    bool? publicProfile,
    bool? showActivity,
    bool? allowTagging,
    bool? allowMentions,
    String? contentFilter,
    bool? safeSearch,
    bool? matureContent,
    bool? autoDeleteMessages,
    int? autoDeleteDays,
    bool? clearCacheOnExit,
    bool? incognitoMode,
    bool? doNotDisturb,
    DateTime? dndStart,
    DateTime? dndEnd,
    bool? vibrateEnabled,
    bool? soundEnabled,
    String? notificationSound,
    bool? ledEnabled,
    String? ledColor,
    bool? lockScreenNotifications,
    bool? notificationPreview,
    int? notificationPriority,
    bool? badgeEnabled,
    bool? headsUpEnabled,
    String? fontFamily,
    double? fontScale,
    String? displayMode,
    bool? amoledDark,
    bool? reduceMotion,
    bool? highContrast,
    bool? largeText,
    bool? screenReader,
    String? accentColor,
    String? backgroundColor,
    String? cardColor,
    String? textColor,
    String? secondaryTextColor,
    double? cornerRadius,
    double? blurRadius,
    double? shadowOpacity,
    bool? neumorphism,
    bool? glassmorphism,
    bool? gradientBackground,
    bool? animatedBackground,
    String? wallpaper,
    double? wallpaperOpacity,
    bool? parallaxEffect,
    bool? hapticFeedback,
    String? hapticStrength,
    bool? soundEffects,
    double? soundVolume,
    bool? pageTransitions,
    String? transitionType,
    int? transitionDuration,
    bool? listAnimations,
    bool? staggerAnimations,
    int? staggerDelay,
    bool? buttonAnimations,
    bool? cardAnimations,
    bool? dialogAnimations,
    bool? loadingAnimations,
    String? loadingStyle,
    bool? shimmerEffect,
    bool? skeletonLoading,
    bool? pullToRefresh,
    bool? infiniteScroll,
    int? pageSize,
    bool? cacheImages,
    int? imageCacheSize,
    bool? compressImages,
    int? imageQuality,
    bool? lazyLoadImages,
    bool? webpFormat,
    bool? autoRotateImages,
    bool? saveToGallery,
    bool? askBeforeSaving,
    String? downloadPath,
    bool? nomediaFile,
    bool? showFileExtensions,
    bool? sortByName,
    bool? sortAscending,
    String? viewMode,
    int? gridColumns,
    bool? showHiddenFiles,
    bool? showThumbnails,
    int? thumbnailSize,
    bool? fastScroll,
    bool? scrollbars,
    bool? edgeToEdge,
    bool? immersiveMode,
    bool? hideStatusBar,
    bool? hideNavigationBar,
    bool? fullscreenMode,
    bool? landscapeMode,
    bool? autoRotate,
    String? orientation,
    bool? keepScreenOn,
    int? screenTimeout,
    bool? brightnessControl,
    double? brightness,
    bool? autoBrightness,
    bool? nightMode,
    int? nightModeStart,
    int? nightModeEnd,
    double? nightModeIntensity,
    bool? blueLightFilter,
    double? blueLightIntensity,
    bool? grayscaleMode,
    bool? colorInversion,
    bool? colorCorrection,
    String? colorCorrectionMode,
    double? colorCorrectionIntensity,
  }) => User(
    id: id ?? this.id,
    username: username ?? this.username,
    nickname: nickname ?? this.nickname,
    email: email ?? this.email,
    phone: phone ?? this.phone,
    avatar: avatar ?? this.avatar,
    bio: bio ?? this.bio,
    gender: gender ?? this.gender,
    birthday: birthday ?? this.birthday,
    location: location ?? this.location,
    website: website ?? this.website,
    language: language ?? this.language,
    timezone: timezone ?? this.timezone,
    theme: theme ?? this.theme,
    points: points ?? this.points,
    level: level ?? this.level,
    exp: exp ?? this.exp,
    isVerified: isVerified ?? this.isVerified,
    isPremium: isPremium ?? this.isPremium,
    isAdmin: isAdmin ?? this.isAdmin,
    isBanned: isBanned ?? this.isBanned,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    lastLoginAt: lastLoginAt ?? this.lastLoginAt,
    lastLoginIp: lastLoginIp ?? this.lastLoginIp,
    lastLoginDevice: lastLoginDevice ?? this.lastLoginDevice,
    loginCount: loginCount ?? this.loginCount,
    followerCount: followerCount ?? this.followerCount,
    followingCount: followingCount ?? this.followingCount,
    postCount: postCount ?? this.postCount,
    chatCount: chatCount ?? this.chatCount,
    imageGenCount: imageGenCount ?? this.imageGenCount,
    videoGenCount: videoGenCount ?? this.videoGenCount,
    githubId: githubId ?? this.githubId,
    githubUsername: githubUsername ?? this.githubUsername,
    githubAvatar: githubAvatar ?? this.githubAvatar,
    githubBound: githubBound ?? this.githubBound,
    wechatId: wechatId ?? this.wechatId,
    wechatBound: wechatBound ?? this.wechatBound,
    qqId: qqId ?? this.qqId,
    qqBound: qqBound ?? this.qqBound,
    appleId: appleId ?? this.appleId,
    appleBound: appleBound ?? this.appleBound,
    twoFactorEnabled: twoFactorEnabled ?? this.twoFactorEnabled,
    twoFactorMethod: twoFactorMethod ?? this.twoFactorMethod,
    emailVerified: emailVerified ?? this.emailVerified,
    phoneVerified: phoneVerified ?? this.phoneVerified,
    identityVerified: identityVerified ?? this.identityVerified,
    realName: realName ?? this.realName,
    idCard: idCard ?? this.idCard,
    idCardType: idCardType ?? this.idCardType,
    identityVerifiedAt: identityVerifiedAt ?? this.identityVerifiedAt,
    status: status ?? this.status,
    accountType: accountType ?? this.accountType,
    premiumExpiresAt: premiumExpiresAt ?? this.premiumExpiresAt,
    premiumPlan: premiumPlan ?? this.premiumPlan,
    autoRenew: autoRenew ?? this.autoRenew,
    maxConversations: maxConversations ?? this.maxConversations,
    maxMessagesPerDay: maxMessagesPerDay ?? this.maxMessagesPerDay,
    maxImageGenPerDay: maxImageGenPerDay ?? this.maxImageGenPerDay,
    maxVideoGenPerDay: maxVideoGenPerDay ?? this.maxVideoGenPerDay,
    maxFileSize: maxFileSize ?? this.maxFileSize,
    maxUploadsPerDay: maxUploadsPerDay ?? this.maxUploadsPerDay,
    defaultModel: defaultModel ?? this.defaultModel,
    defaultImageModel: defaultImageModel ?? this.defaultImageModel,
    defaultVideoModel: defaultVideoModel ?? this.defaultVideoModel,
    defaultTemperature: defaultTemperature ?? this.defaultTemperature,
    defaultMaxTokens: defaultMaxTokens ?? this.defaultMaxTokens,
    streamingEnabled: streamingEnabled ?? this.streamingEnabled,
    markdownEnabled: markdownEnabled ?? this.markdownEnabled,
    codeHighlightEnabled: codeHighlightEnabled ?? this.codeHighlightEnabled,
    autoTranslate: autoTranslate ?? this.autoTranslate,
    targetLanguage: targetLanguage ?? this.targetLanguage,
    ttsEnabled: ttsEnabled ?? this.ttsEnabled,
    ttsVoice: ttsVoice ?? this.ttsVoice,
    ttsRate: ttsRate ?? this.ttsRate,
    ttsPitch: ttsPitch ?? this.ttsPitch,
    autoPlayVoice: autoPlayVoice ?? this.autoPlayVoice,
    voiceInputEnabled: voiceInputEnabled ?? this.voiceInputEnabled,
    voiceInputLanguage: voiceInputLanguage ?? this.voiceInputLanguage,
    wakeWordEnabled: wakeWordEnabled ?? this.wakeWordEnabled,
    wakeWord: wakeWord ?? this.wakeWord,
    alwaysOnDisplay: alwaysOnDisplay ?? this.alwaysOnDisplay,
    batteryOptimization: batteryOptimization ?? this.batteryOptimization,
    dataSaver: dataSaver ?? this.dataSaver,
    wifiOnlyDownloads: wifiOnlyDownloads ?? this.wifiOnlyDownloads,
    autoUpdate: autoUpdate ?? this.autoUpdate,
    betaUpdates: betaUpdates ?? this.betaUpdates,
    analyticsEnabled: analyticsEnabled ?? this.analyticsEnabled,
    crashReporting: crashReporting ?? this.crashReporting,
    personalizedAds: personalizedAds ?? this.personalizedAds,
    showOnlineStatus: showOnlineStatus ?? this.showOnlineStatus,
    showReadReceipts: showReadReceipts ?? this.showReadReceipts,
    allowDirectMessages: allowDirectMessages ?? this.allowDirectMessages,
    allowFriendRequests: allowFriendRequests ?? this.allowFriendRequests,
    publicProfile: publicProfile ?? this.publicProfile,
    showActivity: showActivity ?? this.showActivity,
    allowTagging: allowTagging ?? this.allowTagging,
    allowMentions: allowMentions ?? this.allowMentions,
    contentFilter: contentFilter ?? this.contentFilter,
    safeSearch: safeSearch ?? this.safeSearch,
    matureContent: matureContent ?? this.matureContent,
    autoDeleteMessages: autoDeleteMessages ?? this.autoDeleteMessages,
    autoDeleteDays: autoDeleteDays ?? this.autoDeleteDays,
    clearCacheOnExit: clearCacheOnExit ?? this.clearCacheOnExit,
    incognitoMode: incognitoMode ?? this.incognitoMode,
    doNotDisturb: doNotDisturb ?? this.doNotDisturb,
    dndStart: dndStart ?? this.dndStart,
    dndEnd: dndEnd ?? this.dndEnd,
    vibrateEnabled: vibrateEnabled ?? this.vibrateEnabled,
    soundEnabled: soundEnabled ?? this.soundEnabled,
    notificationSound: notificationSound ?? this.notificationSound,
    ledEnabled: ledEnabled ?? this.ledEnabled,
    ledColor: ledColor ?? this.ledColor,
    lockScreenNotifications: lockScreenNotifications ?? this.lockScreenNotifications,
    notificationPreview: notificationPreview ?? this.notificationPreview,
    notificationPriority: notificationPriority ?? this.notificationPriority,
    badgeEnabled: badgeEnabled ?? this.badgeEnabled,
    headsUpEnabled: headsUpEnabled ?? this.headsUpEnabled,
    fontFamily: fontFamily ?? this.fontFamily,
    fontScale: fontScale ?? this.fontScale,
    displayMode: displayMode ?? this.displayMode,
    amoledDark: amoledDark ?? this.amoledDark,
    reduceMotion: reduceMotion ?? this.reduceMotion,
    highContrast: highContrast ?? this.highContrast,
    largeText: largeText ?? this.largeText,
    screenReader: screenReader ?? this.screenReader,
    accentColor: accentColor ?? this.accentColor,
    backgroundColor: backgroundColor ?? this.backgroundColor,
    cardColor: cardColor ?? this.cardColor,
    textColor: textColor ?? this.textColor,
    secondaryTextColor: secondaryTextColor ?? this.secondaryTextColor,
    cornerRadius: cornerRadius ?? this.cornerRadius,
    blurRadius: blurRadius ?? this.blurRadius,
    shadowOpacity: shadowOpacity ?? this.shadowOpacity,
    neumorphism: neumorphism ?? this.neumorphism,
    glassmorphism: glassmorphism ?? this.glassmorphism,
    gradientBackground: gradientBackground ?? this.gradientBackground,
    animatedBackground: animatedBackground ?? this.animatedBackground,
    wallpaper: wallpaper ?? this.wallpaper,
    wallpaperOpacity: wallpaperOpacity ?? this.wallpaperOpacity,
    parallaxEffect: parallaxEffect ?? this.parallaxEffect,
    hapticFeedback: hapticFeedback ?? this.hapticFeedback,
    hapticStrength: hapticStrength ?? this.hapticStrength,
    soundEffects: soundEffects ?? this.soundEffects,
    soundVolume: soundVolume ?? this.soundVolume,
    pageTransitions: pageTransitions ?? this.pageTransitions,
    transitionType: transitionType ?? this.transitionType,
    transitionDuration: transitionDuration ?? this.transitionDuration,
    listAnimations: listAnimations ?? this.listAnimations,
    staggerAnimations: staggerAnimations ?? this.staggerAnimations,
    staggerDelay: staggerDelay ?? this.staggerDelay,
    buttonAnimations: buttonAnimations ?? this.buttonAnimations,
    cardAnimations: cardAnimations ?? this.cardAnimations,
    dialogAnimations: dialogAnimations ?? this.dialogAnimations,
    loadingAnimations: loadingAnimations ?? this.loadingAnimations,
    loadingStyle: loadingStyle ?? this.loadingStyle,
    shimmerEffect: shimmerEffect ?? this.shimmerEffect,
    skeletonLoading: skeletonLoading ?? this.skeletonLoading,
    pullToRefresh: pullToRefresh ?? this.pullToRefresh,
    infiniteScroll: infiniteScroll ?? this.infiniteScroll,
    pageSize: pageSize ?? this.pageSize,
    cacheImages: cacheImages ?? this.cacheImages,
    imageCacheSize: imageCacheSize ?? this.imageCacheSize,
    compressImages: compressImages ?? this.compressImages,
    imageQuality: imageQuality ?? this.imageQuality,
    lazyLoadImages: lazyLoadImages ?? this.lazyLoadImages,
    webpFormat: webpFormat ?? this.webpFormat,
    autoRotateImages: autoRotateImages ?? this.autoRotateImages,
    saveToGallery: saveToGallery ?? this.saveToGallery,
    askBeforeSaving: askBeforeSaving ?? this.askBeforeSaving,
    downloadPath: downloadPath ?? this.downloadPath,
    nomediaFile: nomediaFile ?? this.nomediaFile,
    showFileExtensions: showFileExtensions ?? this.showFileExtensions,
    sortByName: sortByName ?? this.sortByName,
    sortAscending: sortAscending ?? this.sortAscending,
    viewMode: viewMode ?? this.viewMode,
    gridColumns: gridColumns ?? this.gridColumns,
    showHiddenFiles: showHiddenFiles ?? this.showHiddenFiles,
    showThumbnails: showThumbnails ?? this.showThumbnails,
    thumbnailSize: thumbnailSize ?? this.thumbnailSize,
    fastScroll: fastScroll ?? this.fastScroll,
    scrollbars: scrollbars ?? this.scrollbars,
    edgeToEdge: edgeToEdge ?? this.edgeToEdge,
    immersiveMode: immersiveMode ?? this.immersiveMode,
    hideStatusBar: hideStatusBar ?? this.hideStatusBar,
    hideNavigationBar: hideNavigationBar ?? this.hideNavigationBar,
    fullscreenMode: fullscreenMode ?? this.fullscreenMode,
    landscapeMode: landscapeMode ?? this.landscapeMode,
    autoRotate: autoRotate ?? this.autoRotate,
    orientation: orientation ?? this.orientation,
    keepScreenOn: keepScreenOn ?? this.keepScreenOn,
    screenTimeout: screenTimeout ?? this.screenTimeout,
    brightnessControl: brightnessControl ?? this.brightnessControl,
    brightness: brightness ?? this.brightness,
    autoBrightness: autoBrightness ?? this.autoBrightness,
    nightMode: nightMode ?? this.nightMode,
    nightModeStart: nightModeStart ?? this.nightModeStart,
    nightModeEnd: nightModeEnd ?? this.nightModeEnd,
    nightModeIntensity: nightModeIntensity ?? this.nightModeIntensity,
    blueLightFilter: blueLightFilter ?? this.blueLightFilter,
    blueLightIntensity: blueLightIntensity ?? this.blueLightIntensity,
    grayscaleMode: grayscaleMode ?? this.grayscaleMode,
    colorInversion: colorInversion ?? this.colorInversion,
    colorCorrection: colorCorrection ?? this.colorCorrection,
    colorCorrectionMode: colorCorrectionMode ?? this.colorCorrectionMode,
    colorCorrectionIntensity: colorCorrectionIntensity ?? this.colorCorrectionIntensity,
  );

  User merge(User other) => copyWith(
    id: other.id,
    username: other.username,
    nickname: other.nickname,
    email: other.email,
    phone: other.phone,
    avatar: other.avatar,
    bio: other.bio,
    gender: other.gender,
    birthday: other.birthday,
    location: other.location,
    website: other.website,
    language: other.language,
    timezone: other.timezone,
    theme: other.theme,
    points: other.points,
    level: other.level,
    exp: other.exp,
    isVerified: other.isVerified,
    isPremium: other.isPremium,
    isAdmin: other.isAdmin,
    isBanned: other.isBanned,
    createdAt: other.createdAt,
    updatedAt: other.updatedAt,
    lastLoginAt: other.lastLoginAt,
    lastLoginIp: other.lastLoginIp,
    lastLoginDevice: other.lastLoginDevice,
    loginCount: other.loginCount,
    followerCount: other.followerCount,
    followingCount: other.followingCount,
    postCount: other.postCount,
    chatCount: other.chatCount,
    imageGenCount: other.imageGenCount,
    videoGenCount: other.videoGenCount,
    githubId: other.githubId,
    githubUsername: other.githubUsername,
    githubAvatar: other.githubAvatar,
    githubBound: other.githubBound,
    wechatId: other.wechatId,
    wechatBound: other.wechatBound,
    qqId: other.qqId,
    qqBound: other.qqBound,
    appleId: other.appleId,
    appleBound: other.appleBound,
    twoFactorEnabled: other.twoFactorEnabled,
    twoFactorMethod: other.twoFactorMethod,
    emailVerified: other.emailVerified,
    phoneVerified: other.phoneVerified,
    identityVerified: other.identityVerified,
    realName: other.realName,
    idCard: other.idCard,
    idCardType: other.idCardType,
    identityVerifiedAt: other.identityVerifiedAt,
    status: other.status,
    accountType: other.accountType,
    premiumExpiresAt: other.premiumExpiresAt,
    premiumPlan: other.premiumPlan,
    autoRenew: other.autoRenew,
    maxConversations: other.maxConversations,
    maxMessagesPerDay: other.maxMessagesPerDay,
    maxImageGenPerDay: other.maxImageGenPerDay,
    maxVideoGenPerDay: other.maxVideoGenPerDay,
    maxFileSize: other.maxFileSize,
    maxUploadsPerDay: other.maxUploadsPerDay,
    defaultModel: other.defaultModel,
    defaultImageModel: other.defaultImageModel,
    defaultVideoModel: other.defaultVideoModel,
    defaultTemperature: other.defaultTemperature,
    defaultMaxTokens: other.defaultMaxTokens,
    streamingEnabled: other.streamingEnabled,
    markdownEnabled: other.markdownEnabled,
    codeHighlightEnabled: other.codeHighlightEnabled,
    autoTranslate: other.autoTranslate,
    targetLanguage: other.targetLanguage,
    ttsEnabled: other.ttsEnabled,
    ttsVoice: other.ttsVoice,
    ttsRate: other.ttsRate,
    ttsPitch: other.ttsPitch,
    autoPlayVoice: other.autoPlayVoice,
    voiceInputEnabled: other.voiceInputEnabled,
    voiceInputLanguage: other.voiceInputLanguage,
    wakeWordEnabled: other.wakeWordEnabled,
    wakeWord: other.wakeWord,
    alwaysOnDisplay: other.alwaysOnDisplay,
    batteryOptimization: other.batteryOptimization,
    dataSaver: other.dataSaver,
    wifiOnlyDownloads: other.wifiOnlyDownloads,
    autoUpdate: other.autoUpdate,
    betaUpdates: other.betaUpdates,
    analyticsEnabled: other.analyticsEnabled,
    crashReporting: other.crashReporting,
    personalizedAds: other.personalizedAds,
    showOnlineStatus: other.showOnlineStatus,
    showReadReceipts: other.showReadReceipts,
    allowDirectMessages: other.allowDirectMessages,
    allowFriendRequests: other.allowFriendRequests,
    publicProfile: other.publicProfile,
    showActivity: other.showActivity,
    allowTagging: other.allowTagging,
    allowMentions: other.allowMentions,
    contentFilter: other.contentFilter,
    safeSearch: other.safeSearch,
    matureContent: other.matureContent,
    autoDeleteMessages: other.autoDeleteMessages,
    autoDeleteDays: other.autoDeleteDays,
    clearCacheOnExit: other.clearCacheOnExit,
    incognitoMode: other.incognitoMode,
    doNotDisturb: other.doNotDisturb,
    dndStart: other.dndStart,
    dndEnd: other.dndEnd,
    vibrateEnabled: other.vibrateEnabled,
    soundEnabled: other.soundEnabled,
    notificationSound: other.notificationSound,
    ledEnabled: other.ledEnabled,
    ledColor: other.ledColor,
    lockScreenNotifications: other.lockScreenNotifications,
    notificationPreview: other.notificationPreview,
    notificationPriority: other.notificationPriority,
    badgeEnabled: other.badgeEnabled,
    headsUpEnabled: other.headsUpEnabled,
    fontFamily: other.fontFamily,
    fontScale: other.fontScale,
    displayMode: other.displayMode,
    amoledDark: other.amoledDark,
    reduceMotion: other.reduceMotion,
    highContrast: other.highContrast,
    largeText: other.largeText,
    screenReader: other.screenReader,
    accentColor: other.accentColor,
    backgroundColor: other.backgroundColor,
    cardColor: other.cardColor,
    textColor: other.textColor,
    secondaryTextColor: other.secondaryTextColor,
    cornerRadius: other.cornerRadius,
    blurRadius: other.blurRadius,
    shadowOpacity: other.shadowOpacity,
    neumorphism: other.neumorphism,
    glassmorphism: other.glassmorphism,
    gradientBackground: other.gradientBackground,
    animatedBackground: other.animatedBackground,
    wallpaper: other.wallpaper,
    wallpaperOpacity: other.wallpaperOpacity,
    parallaxEffect: other.parallaxEffect,
    hapticFeedback: other.hapticFeedback,
    hapticStrength: other.hapticStrength,
    soundEffects: other.soundEffects,
    soundVolume: other.soundVolume,
    pageTransitions: other.pageTransitions,
    transitionType: other.transitionType,
    transitionDuration: other.transitionDuration,
    listAnimations: other.listAnimations,
    staggerAnimations: other.staggerAnimations,
    staggerDelay: other.staggerDelay,
    buttonAnimations: other.buttonAnimations,
    cardAnimations: other.cardAnimations,
    dialogAnimations: other.dialogAnimations,
    loadingAnimations: other.loadingAnimations,
    loadingStyle: other.loadingStyle,
    shimmerEffect: other.shimmerEffect,
    skeletonLoading: other.skeletonLoading,
    pullToRefresh: other.pullToRefresh,
    infiniteScroll: other.infiniteScroll,
    pageSize: other.pageSize,
    cacheImages: other.cacheImages,
    imageCacheSize: other.imageCacheSize,
    compressImages: other.compressImages,
    imageQuality: other.imageQuality,
    lazyLoadImages: other.lazyLoadImages,
    webpFormat: other.webpFormat,
    autoRotateImages: other.autoRotateImages,
    saveToGallery: other.saveToGallery,
    askBeforeSaving: other.askBeforeSaving,
    downloadPath: other.downloadPath,
    nomediaFile: other.nomediaFile,
    showFileExtensions: other.showFileExtensions,
    sortByName: other.sortByName,
    sortAscending: other.sortAscending,
    viewMode: other.viewMode,
    gridColumns: other.gridColumns,
    showHiddenFiles: other.showHiddenFiles,
    showThumbnails: other.showThumbnails,
    thumbnailSize: other.thumbnailSize,
    fastScroll: other.fastScroll,
    scrollbars: other.scrollbars,
    edgeToEdge: other.edgeToEdge,
    immersiveMode: other.immersiveMode,
    hideStatusBar: other.hideStatusBar,
    hideNavigationBar: other.hideNavigationBar,
    fullscreenMode: other.fullscreenMode,
    landscapeMode: other.landscapeMode,
    autoRotate: other.autoRotate,
    orientation: other.orientation,
    keepScreenOn: other.keepScreenOn,
    screenTimeout: other.screenTimeout,
    brightnessControl: other.brightnessControl,
    brightness: other.brightness,
    autoBrightness: other.autoBrightness,
    nightMode: other.nightMode,
    nightModeStart: other.nightModeStart,
    nightModeEnd: other.nightModeEnd,
    nightModeIntensity: other.nightModeIntensity,
    blueLightFilter: other.blueLightFilter,
    blueLightIntensity: other.blueLightIntensity,
    grayscaleMode: other.grayscaleMode,
    colorInversion: other.colorInversion,
    colorCorrection: other.colorCorrection,
    colorCorrectionMode: other.colorCorrectionMode,
    colorCorrectionIntensity: other.colorCorrectionIntensity,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'User(id: $id)';

  User clone() => User.fromJson(toJson());

  bool get isEmpty => id.isEmpty;
  bool get isNotEmpty => id.isNotEmpty;

}
